### ISSUE TITLE
When it will start or you have discontinued the project?

### ISSUE THREAD

**Issue by ghost** [kiwibrowser/src.next#1]
have u discontinued this kiwi project if so do tell us or people wont have faith on open source world. It is a while kiwi hasn't recieved a proper update.

Regards

**Comment by mikhoul** [comment]
https://github.com/kiwibrowser/src/issues/94#issuecomment-657156828

**Comment by ChiefMikeK** [comment]
# ❣🔜[kiwibrowser/src: Roadmap](https://github.com/kiwibrowser/src#roadmap)   

- Probably need an update 2 the README post 2020 `¯\_(ツ)_/¯`

**Comment by kiwibrowser** [comment]
There are a lot of changes / updates in Kiwi Browser getting updated from Chromium upstream so it may not make a separate repository (like src.next) to be needed but will see how it goes there

**Comment by d3ward** [comment]
Development has been resumed and builds are available in [releases](https://github.com/kiwibrowser/src.next/releases)
