### ISSUE TITLE
Feature Reques: Turn on tab switch on Tablets

### ISSUE THREAD

**Issue by dagaz** [kiwibrowser/src.next#100]
On big tablet displays (Smallest width >= 600) Chromium (and therefore Kiwi) sets the browser in "tablet mode". Then you can only select, close and rearrange tabs. But you can not use the tab switcher or the tab groups function.

That is (in my opinion) a very bad design decision from Google.

It would be really great if there were an option to enforce the "phone mode". It would be best if the "Smallest width" value would be ignored. But I do not know if that is easily possible (I am no programmer, sorry).

**Comment by MmyGgithubAaccount** [comment]
You can achieve this by increasing the "scale factor" for the browser. Details here: https://forum.xda-developers.com/t/how-to-load-full-desktop-websites-permanently-in-chrome-for-android.3771982/

**Comment by dagaz** [comment]
I think that the "scale factor" will result in "everything is bigger".
If I set "Smallest width" to "590" in the developer options then I will get a similar effect. And also: That might not be easy for most users. (Most people I know are already overextended when you just tell them to do anything in a console window - installing ADB would be "to complex" ;).)

What I meant is indeed a feature: Having the screen size of a tablet (for example my Pixel C has a 2560x1800 screen) but the usability of the "phone mode" - without scaling the application itself. I thought of a new option (maybe under Settings -> Accessibility) where the user can select "force phone mode" with a description like "The size of the screen will be ignored and Kiwi Browser is always in 'phone mode'. This is usefull for some users with big screen tablets who wants to use the 'tab groups' feature."

What would be necessary is that the "make it tablet mode"-Switch would be ignored when a screen with a "Smallest width" size of >= "600" is present. That would be easy to use and really useful.

**Comment by kyoyacchi** [comment]
@dagaz, Yep, that would be very good. I agree with you.

**Comment by d3ward** [comment]
#146

**Comment by RyanGreenup** [comment]
This can be acheived by enabling the following   [chrome://flags](chrome://flags):

- `#enable-tab-grid-layout`
- `#grid-tab-switcher-for-tablets`
- `#enable-tab-groups-for-tablets`

**Comment by chezhalcyonacres** [comment]
These flags no longer work in Kiwi. 
In Chrome, I can get the tab switcher, but the tab row is alos enabled, so not ideal.
