### ISSUE TITLE
Data Saver

### ISSUE THREAD

**Issue by d3ward** [kiwibrowser/src.next#108]
Implement a internet data saver feature in Kiwi
It should have a section in settings with some options :
 
- Skip loading all picture and video on website
- Button on what hidden picture you want to see
- Choose if data saver should work on wifi/data

**Comment by d3ward** [comment]
Similar feature is included in new Kiwi !
Settings->Lite Mode

**Comment by DefectiveByDesign** [comment]
Feature disappeared. What happened to it?
