### ISSUE TITLE
Revamp settings page 

### ISSUE THREAD

**Issue by d3ward** [kiwibrowser/src.next#109]
- Reorder options and categorize them 
- Add icon on each category

**Comment by d3ward** [comment]
<img width="557" alt="Schermata 2021-08-01 alle 18 58 56" src="https://user-images.githubusercontent.com/39910418/127779244-7dd370d7-f663-407f-80d2-808953f1f897.png">

**Comment by kiwibrowser** [comment]
This concept with icons is really great, once the UI is live on GitHub this is something that can be done I think

**Comment by karl-pae** [comment]
Hasn't this been implemented now. Should be closed. 😁
