### ISSUE TITLE
Github Workflow Update

### ISSUE THREAD

**Issue by nafoiw1410** [kiwibrowser/src.next#1120]
Could you provide a reason as to why the source code hosted on Github hasn't been updated in 2 years while keep having pre-built release every week and then?

**Comment by nafoiw1410** [comment]
UPDATE THE SOURCE CODE PLEASE YOU ARE JUST MISLEADING PEOPLE BY POSTING RELEASE AND NOT THE UPDATED SOURCE

**Comment by jason5545** [comment]
Read the release note, it's the chromium core got an update
