### ISSUE TITLE
[BUG] Bookmark logo on not bookmarked tabs is broken

### ISSUE THREAD

**Issue by ygz213** [kiwibrowser/src.next#116]
Latest state of [this issue](https://github.com/kiwibrowser/src/issues/375).

- **Not Bookmarked (Broken)**:

![broken_photo](https://user-images.githubusercontent.com/77006222/126783072-eb46f184-ff12-4bc3-9bbe-c044155f43a0.jpg)

- **Bookmarked**:

![fixed_photo](https://user-images.githubusercontent.com/77006222/126783186-5ca510e9-868d-48c0-ab92-14e9395d49dc.jpg)

**Comment by KaKi87** [comment]
What's wrong ?

**Comment by ygz213** [comment]
Bookmark logos isn't the same width and design.
Bookmark logo on not bookmarked tabs is more slim than bookmark logo on bookmarked tabs. ( As far as I see )

**Comment by Lartsch** [comment]
Might be true that there is a small difference, but can't see a real issue here
