### ISSUE TITLE
xvideos.com videos loading issue

### ISSUE THREAD

**Issue by vmz9poa5** [kiwibrowser/src.next#1175]
**Describe the bug**
Can't load any videos let alone play them. It will remain at loading 100% and stuck.

**To Reproduce**
Go to xvideos.com and test it yourself.

**Expected behavior**
Other browsers could load and play the videos without issues.

**Screenshots**
No screenshot is possible. Sorry.

**Smartphone (please complete the following information):**
 - Device: Realme
 - Android Version : A11
 - Kiwi Browser Version : 124.0.6327.4

**Additional context**
Kiwi is extremely buggy regarding videos playing on xvideos.com. I have been suffering from the bug that videos loading 100% then stopped with error. It's more likely to happen with some particular channels. For some videos, switching to full screen will stop them from playing.

**Comment by vmz9poa5** [comment]
Same problem with other porn sites, e.g: https://vlxx.lol/. It can't load the videos.

**Comment by kehrazy** [comment]
most definitely not a kiwi related issue.

**Comment by vmz9poa5** [comment]
> most definitely not a kiwi related issue.

It definitely is a kiwi issue! There is no such problem on other browsers.
