### ISSUE TITLE
Favorite sites shortcut bubbles blank

### ISSUE THREAD

**Issue by possom2009** [kiwibrowser/src.next#1206]
It seems https://logos.kiwibrowser.com is down causing the favorite site bubbles on the homepage to not load site icons.

**Comment by kiwibrowser** [comment]
Thanks! It has been resolved now, we had received millions of requests in addition per day (visibly not from Kiwi) with a weird pattern that didn't seem legitimate and Cloudflare didn't block them, so we manually added new filters (we process 20 million requests on a normal day to give some perspective).

**Comment by possom2009** [comment]
> Thanks! It has been resolved now, we had received millions of requests in addition per day (visibly not from Kiwi) with a weird pattern that didn't seem legitimate and Cloudflare didn't block them, so we manually added new filters (we process 20 million requests on a normal day to give some perspective).

I thought it might have been a cache problem at first, then I checked the site the icons are retrieved from and saw that it was down.
