### ISSUE TITLE
[Feature request] Slider menus

### ISSUE THREAD

**Issue by SlimF** [kiwibrowser/src.next#124]
Would something like Lightning browser's slider menus be possible to implement ? They are extremely convenient to use and I think that they would be a great addition to Kiwi. My English isn't the best, so I'll attach screenshots which show what I mean.
![screenshot_20181127-053144_lightning](https://user-images.githubusercontent.com/6482572/49056999-859a2f00-f206-11e8-98a6-156a0f576746.png)
![screenshot_20181127-053202_lightning](https://user-images.githubusercontent.com/6482572/49057000-859a2f00-f206-11e8-8587-23a899b73885.png)
![screenshot_20181127-053213_lightning](https://user-images.githubusercontent.com/6482572/49057001-8632c580-f206-11e8-8762-5875b498c3ca.png)

**Comment by d3ward** [comment]
Extensions are there from a while . So with some research it's possible to find extension that do exactly what the issue talk about ( sidebar with bookmarks or tabs )
