### ISSUE TITLE
Android autofill framework support

### ISSUE THREAD

**Issue by Raphire** [kiwibrowser/src.next#132]
The android autofill framework is a great new addition and basically essential if you use a third-party password manager such as lastpass, bitwarden or 1password. 

Kiwi Browser doesn't currently seem to support the android autofill framework. While a few other popular browsers do support this, such as brave and firefox focus.

Is there any reason why this does not yet work for kiwi browser?

**Comment by d3ward** [comment]
#64

**Comment by carlosmg2** [comment]
Yay, after latest update it works!!  Finally I can fully migrate to Kiwi. Thanks Devs

**Comment by Indranil012** [comment]
> Yay, after latest update it works!! Finally I can fully migrate to Kiwi. Thanks Devs

No, not fully working. Still broken on some site like xda, github

**Comment by carlosmg2** [comment]
> > Yay, after latest update it works!! Finally I can fully migrate to Kiwi. Thanks Devs
> 
> No, not fully working. Still broken on some site like xda, github

Works for me nice on those 2 sites too.

**Comment by Indranil012** [comment]
> > > Yay, after latest update it works!! Finally I can fully migrate to Kiwi. Thanks Devs
> > 
> > 
> > No, not fully working. Still broken on some site like xda, github
> 
> Works for me nice on those 2 sites too.

Does your accessibility autofill is turned on?

**Comment by carlosmg2** [comment]
> > > > Yay, after latest update it works!! Finally I can fully migrate to Kiwi. Thanks Devs
> > > 
> > > 
> > > No, not fully working. Still broken on some site like xda, github
> > 
> > 
> > Works for me nice on those 2 sites too.
> 
> Does your accessibility autofill is turned on?

Yes

**Comment by Indranil012** [comment]
> > > > > Yay, after latest update it works!! Finally I can fully migrate to Kiwi. Thanks Devs
> > > > 
> > > > 
> > > > No, not fully working. Still broken on some site like xda, github
> > > 
> > > 
> > > Works for me nice on those 2 sites too.
> > 
> > 
> > Does your accessibility autofill is turned on?
> 
> Yes

Then turn off and check!

**Comment by carlosmg2** [comment]
> > > Does your accessibility autofill is turned on?
> > 
> > 
> > Yes
> 
> Then turn off and check!

Disabled Dashlane accessibility, and those sites still working. Logged out, rebooted phone and logging to those sites still working nice.

**Comment by Indranil012** [comment]
> > Then turn off and check!
> 
> Disabled Dashlane accessibility, and those sites still working. Logged out, rebooted phone and logging to those sites still working nice.

I'm using bitwarden maybe it has some issue. But working fine on chrome
