### ISSUE TITLE
Disable incognito mode

### ISSUE THREAD

**Issue by czales** [kiwibrowser/src.next#135]
Hi,

is there any way how to disable incognito mode in kiwi browser on Android? We need kiosk browser with whitelist...but if anybody runs the incognito mode, whitelist doesn't work.

Thx

**Comment by d3ward** [comment]
If this issue has been resolved, please close the issue  @czales

**Comment by kiwibrowser** [comment]
Hello,

The issue isn't resolved as far as I understand, but I'm interested to hear about the case to see if there is a possible product improvement @czales  to do.
It seems to be a very rare feature request, so I'm intrigued to see if Kiwi could solve the case.

Though it was long time ago so probably not at all, but who knows :)
