### ISSUE TITLE
How to edit text labels below shortcuts/speed dials on home screen?

### ISSUE THREAD

**Issue by pstein** [kiwibrowser/src.next#138]
Assume I put some Shortcuts/Speed Dial thumbnails on home screen (first tab after launching kiwi browser).

Below each thumbnail there is a text label (=domain name).
How can I change this shortcut/speed dial thumbnail text label?

I miss an "edit" function.

At first I though I could export the shortcuts into *.json file, then edit this *.json file an re-import it as a workaround. But this seems not to work. Each entry offers only the domain name text field but no second, different text label.

Since I use a couple of shortcuts from the same domain I cannot distinguish between them on the home screen.

Is there a workaround for that?

Thank you
Peter

**Comment by d3ward** [comment]
Since that issue it's old and the default homepage will not undergo changes and implementation of new features, over time was born an alternative more customizable [NextNTP](https://github.com/d3ward/nextntp) which includes among other things the naming tiles

**Comment by kiwibrowser** [comment]
True, I think it should be considered during a NTP update / revamp but isn't urgent
