### ISSUE TITLE
Bitwarden app can't detect actual site to autofill

### ISSUE THREAD

**Issue by mycal123** [kiwibrowser/src.next#14]
When i choose autofill with Bitwarden...

Dialogue appear in bitwarden app as
"Items for com.kiwibrowser.browser.dev"
While in stable kiwibrowser it detect actual site

**Comment by Dark-Matter7232** [comment]
Post this issue on Bitwarden repo as they only have old kiwi browser package name [`hardcoded`](https://github.com/bitwarden/mobile/commit/ac027ee3a0516446434f78e9b9a71b1fbb89e920) in their app.

**Comment by kiwibrowser** [comment]
In a couple of days, the package will have ".dev" removed
