### ISSUE TITLE
Search for tabs from tab switcher

### ISSUE THREAD

**Issue by DragoCubed** [kiwibrowser/src.next#141]
Firefox for desktop lets you do this and lets you search just for tabs from the address bar (omnibox) by starting a query with %.
Here's the Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1052807

**Comment by d3ward** [comment]
#166

**Comment by Poopooracoocoo** [comment]
@d3ward I was about to open a new issue until I saw this. #166 was implemented by Google in Chromium for Android but it doesn't look like this will be added anytime soon. No Google developers have discussed added this to Android. Could you please reconsider?
