### ISSUE TITLE
[BUG] The icons of extensions are broken.

### ISSUE THREAD

**Issue by kyoyacchi** [kiwibrowser/src.next#142]
![IMG_20210723_200246_346](https://user-images.githubusercontent.com/63583961/126816672-cedce1cb-2c9a-4b21-b2a2-61744d71c282.JPG)

Same in Phone device(s).

**Comment by KaKi87** [comment]
@d3ward This is on purpose, right ?

Personally, I like it.

**Comment by kyoyacchi** [comment]
> @d3ward This is on purpose, right ?
> 
> Personally, I like it.

On purpose what?

**Comment by Lartsch** [comment]
Duplicate of #72

**Comment by kyoyacchi** [comment]
Tch.
