### ISSUE TITLE
Feature: Ability to open link in it's native app

### ISSUE THREAD

**Issue by 1Mark** [kiwibrowser/src.next#143]
Would be nice to have an option in the menu to open the current URL in it's app
This feature exists in Firefox on Android and I think it would be a really nice addition to Kiwi Browser
![image](https://user-images.githubusercontent.com/15360245/114318233-189c4100-9b04-11eb-96a1-a8f9770a8db6.png)

Please note having an all or nothing approach where you either open all links in their native app is not ideal since often you don't want this setting on for all URLs. Ideally, it would be nice to have a setting per site, but that would just be the cherry on top.

Current workaround is to use:
https://play.google.com/store/apps/details?id=com.tasomaniac.openwith&hl=en&gl=US

**Comment by d3ward** [comment]
Related to #96
