### ISSUE TITLE
Option to enable desktop/tablet layout on mobile

### ISSUE THREAD

**Issue by laem** [kiwibrowser/src.next#146]
Kiwi browser can be used on large monitors, e.g. tablets, Samsung Dex, Huawai desktop mode, or the upcomping LG desktop mode.

It would be nice to turn on desktop mode on these screens. It must be perfectly feasible, since the UI itself, e.g. tabs, already change according to the monitor.

Here is the mobile layout.
![Screenshot_20201208-140013_Kiwi Browser](https://user-images.githubusercontent.com/1177762/101487000-cbde0900-395d-11eb-9c5c-8f61224c1eda.jpg)

Here is the desktop layout, that switches on automatically.
![Screenshot_20201208-135952_Kiwi Browser](https://user-images.githubusercontent.com/1177762/101487009-cf719000-395d-11eb-9ea1-45605669ead2.jpg)

**Comment by dagaz** [comment]
Because #100 was merged with this issue:
I asked for the exact opposite: Enable phone mode (with tab switcher and groups) for Tablets.

Maybe it would be a good idea to bring an option with three selections:

1. device default
2. force phone mode
3. force tablet/desktop mode

**Comment by d3ward** [comment]
Github release Kiwi v116 finally got this ! You can enable it on Settings -> Tab switcher -> Desktop
