### ISSUE TITLE
"Allow in Incognito" doesn't work well

### ISSUE THREAD

**Issue by rururux** [kiwibrowser/src.next#148]
To run ublock in Incognito tab, it need to re-enable "Allow-" every time you start Incognito mode.
and only works network filter, element filter doesn't work. 
Other extensions work well in Incognito mode.

kiwi version:77.0.3865.92
ublock:1.24.4

**Comment by d3ward** [comment]
With new Kiwi the "Allow in Incognito" works for most extensions .
If there is any extension that doesn't work , open a specific issue about it
