### ISSUE TITLE
Bookmark all tabs

### ISSUE THREAD

**Issue by DragoCubed** [kiwibrowser/src.next#149]
People have wanted this in Chrome, Vivaldi, Edge, Brave, Bromite, DDG, Firefox and more. It's only possible on desktop browsers.

Here's the Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1026222
Bromite issue: https://github.com/bromite/bromite/issues/570
Ungoogled Chromium issue: https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/26

Bookmark all tabs would appear as a menu item in the tab switcher.
A new folder could be created without prompt and allow users to access it quickly from a snackbar button, much like bookmarking a page OR a dialog like the download prompt could show OR a full-screen page could be shown.

A great use case is incognito browsing. Running low on battery? Just bookmark all of your tabs!

**Comment by d3ward** [comment]
@DragoCubed extensions now can work in incognito .
And the extensions that works with tabs/bookmarks seems to be a better solution than a native solution . 
Also closing the issue as it doesn't seems to be any plan for such a feature

**Comment by Poopooracoocoo** [comment]
@d3ward Would it be possible to look at what Bromite does and do the same?
