### ISSUE TITLE
Notification when a new update is available

### ISSUE THREAD

**Issue by kiwibrowser** [kiwibrowser/src.next#153]
Quoting @rancidfrog kiwibrowser/src#230 

Ideally, a notification of new version option in settings would be great. Several open source projects have implemented update notification which takes you to github release section on click.

Newpipe ~ https://github.com/TeamNewPipe/NewPipe
Fairemail ~ https://github.com/M66B/FairEmail

**Comment by KaKi87** [comment]
Potentially related to #130
