### ISSUE TITLE
Please add generation label in About Kiwi

### ISSUE THREAD

**Issue by rancidfrog** [kiwibrowser/src.next#154]
Currently only Version Git201030 shows in About Kiwi, which is not ideal, since releases are using `Generation 338511068`

![](https://i.imgur.com/WoFInzs.jpg) 

Some type of consistency is needed, or adding Generation version to about section.

Ideally, a notification of new version option in settings would be great. Several open source projects have implemented update notification which takes you to github release section on click.
- Newpipe ~ https://github.com/TeamNewPipe/NewPipe
- Fairemail ~ https://github.com/M66B/FairEmail

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
Now the build show the Chromium version
