### ISSUE TITLE
How to change speed dial logos (from logos.kiwibrowser.com)

### ISSUE THREAD

**Issue by raniesantos** [kiwibrowser/src.next#158]
I have a problem with adding speed dials where a bunch of them are showing me the wrong website icon.

The source code says that all of them come from `logos.kiwibrowser.com`.

How do we change these? There doesn't seem to be a repo named logos under kiwibrowser.

**Comment by d3ward** [comment]
Since that issue it's old and the default homepage will not undergo changes and implementation of new features, over time was born an alternative more customizable [NextNTP](https://github.com/d3ward/nextntp) which includes among other things the editing of logo source

**Comment by raniesantos** [comment]
NextNTP is a web page right? Not a browser built-in feature?

**Comment by d3ward** [comment]
> NextNTP is a web page right? Not a browser built-in feature?

For now it's a webpage only . Built-in could be an option in future builds

**Comment by raniesantos** [comment]
Still no way to change a bad speed dial icon????
