### ISSUE TITLE
Scrolling Enhancement

### ISSUE THREAD

**Issue by Dev-i-l** [kiwibrowser/src.next#162]
Can you please add a scrolling button for a smooth scrolling experience like samsung browser, it would be a great addition to the near perfect kiwi browser

**Comment by d3ward** [comment]
There is no plan to include a feature like this in Kiwi. 
A solution can be using a custom script like [awesomeScroller](https://github.com/d3ward/scriptz/raw/master/src/awesomeScroller.user.js)
