### ISSUE TITLE
distinguish KIWI browser from Chrome browser 

### ISSUE THREAD

**Issue by chlegou** [kiwibrowser/src.next#164]
When asking why we need KIWI browser in Android?... Well, the response is quite Simple:  
-> because it support chrome extensions!

As a webmaster, when checking for the browser, we could know from where our browser was opened (Desktop / mobile / Android / IOS...). but does it support chrome extensions??

When it's opened from Android, Is it really the KIWI browser?? does it support extensions??

the Brave browser have did that, they added `"...Brave Chrome..."` in their `navigator.userAgent` result.

more details here: https://stackoverflow.com/a/56459333/4771750

I recommend adding `"...Kiwi Chrome..."` in the user agent, along with mobile, so when we check for it from a website, we know that it's opened in the KIWI mobile App.

Thank you, i hope you accept my idea.

**Comment by d3ward** [comment]
@erayd Recently Kiwi has been updated it's chromium version to latest.

Im also closing the issue  as it's very old

**Comment by erayd** [comment]
Thanks @d3ward. Really glad to see that it's been updated.

Going forward, will Kiwi now report its version accurately in the UA string?

**Comment by d3ward** [comment]
> Thanks @d3ward. Really glad to see that it's been updated.
> 
> Going forward, will Kiwi now report its version accurately in the UA string?

Yes, the user agent now it match the true Chromium version , the one that it's visible  Settings ->About and any UA test, which is v93

**Comment by erayd** [comment]
> Yes, the user agent now it match the true Chromium version , the one that it's visible Settings ->About and any UA test, which is v93

Perfect - thank you 😁.

**Comment by MTHS1901** [comment]
I did some tests comparing differences between "window" elements in Chrome PC/Android browser and Kiwi Browser, and for some reason in Kiwi Browser navigator.userAgentData.brands[2] is set to "undefined" so you could use the code below to set whether it is Kiwi browser or not.

`!!chrome && navigator.userAgentData.brands[2] == undefined`

!!chrome && !!chrome.runtime no longer works, after 106 update.

**Comment by bershanskiy** [comment]
@MTHS1901 
> for some reason in Kiwi Browser navigator.userAgentData.brands[2] is set to "undefined"

On my device (Samsung Galaxy S20 FE) I see:
```js
{
  brand: "Chromium",
  version: "107"
}, {
  brand: "Not=A?Brand",
  version: "24"
}
```
So since the array is too short to report a value so you get `undefined`. This still can be used for identification, since other browsers use different number of "brands", but it is not particularly reliable.

**Comment by MTHS1901** [comment]
> 



> @MTHS1901
> 
> > for some reason in Kiwi Browser navigator.userAgentData.brands[2] is set to "undefined"
> 
> On my device (Samsung Galaxy S20 FE) I see:
> 
> ```js
> {
>   brand: "Chromium",
>   version: "107"
> }, {
>   brand: "Not=A?Brand",
>   version: "24"
> }
> ```
> 
> So since the array is too short to report a value so you get `undefined`. This still can be used for identification, since other browsers use different number of "brands", but it is not particularly reliable.



> @MTHS1901
> 
> > for some reason in Kiwi Browser navigator.userAgentData.brands[2] is set to "undefined"
> 
> On my device (Samsung Galaxy S20 FE) I see:
> 
> ```js
> {
>   brand: "Chromium",
>   version: "107"
> }, {
>   brand: "Not=A?Brand",
>   version: "24"
> }
> ```
> 
> So since the array is too short to report a value so you get `undefined`. This still can be used for identification, since other browsers use different number of "brands", but it is not particularly reliable.

yes, this is not very reliable, but it works for now, i believe there will always be something to identify the kiwi, normally the browser reports:

0: {brand: 'Not?A_Brand', version: '8'}
1: {brand: 'Chromium', version: '108'}
2: {brand: 'Google Chrome', version: '108'}
length

in kiwi "2:" is undefined, I'm using this for now in my project and it works fine in the latest version of kiwi.

**Comment by MTHS1901** [comment]
yes, this is not very reliable, but it works for now, i believe there will always be something to identify the kiwi, normally the browser reports:

0: {brand: 'Not?A_Brand', version: '8'}
1: {brand: 'Chromium', version: '108'}
2: {brand: 'Google Chrome', version: '108'}
length

in kiwi "2:" is undefined, I'm using this for now in my project and it works fine in the latest version of kiwi.

**Comment by MTHS1901** [comment]
> [bershanskiy](/bershanskiy)

yes, this is not very reliable, but it works for now, i believe there will always be something to identify the kiwi, normally the browser reports:

0: {brand: 'Not?A_Brand', version: '8'}
1: {brand: 'Chromium', version: '108'}
2: {brand: 'Google Chrome', version: '108'}
length

in kiwi "2:" is undefined, I'm using this for now in my project and it works fine in the latest version of kiwi.

**Comment by fuweichin** [comment]
Given that 

> Kiwi Browser is an open-source browser for Android based on Chromium

and modern versions of Kiwi Browser support Browser Extensions.

So, to detect Kiwi Browser, here is the JavaScript

```js
if (window.chrome && window.chrome.app && navigator.userAgent.indexOf('Android') > -1) {
  console.log('You are using Kiwi Browser');
}
```
