### ISSUE TITLE
Sometimes a previous tab overlays over full-screen video

### ISSUE THREAD

**Issue by srvtsk** [kiwibrowser/src.next#165]
The browser shows a previous tab while I'm watching a video in the full-screen (horizontal mode). 

Please see the attached. Android 10, MIUI 11, Xiaomi Mi 9 Lite 6-128. In the left part of the screen, you see content from a tab, no matter if it was closed previously.

![IMAGE 2020-05-19 01:15:39](https://user-images.githubusercontent.com/33536302/82264976-9bf1f880-996e-11ea-8e6a-20cd19438167.jpg)

**Comment by KaKi87** [comment]
Also regularly happening to me, root cause remains unknown for now.

**Comment by d3ward** [comment]
Is this bug still there ? I think that with latest builds where is fixed a fullscreen video related bug may have solved this problem as well

**Comment by kiwibrowser** [comment]
This is a SurfaceControl typical bug, I think it is resolved because SurfaceControl is now disabled in Kiwi. It's the same type of bug you see in Chrome, when the bottom of the website is all garbled/mixed up.

**Comment by d3ward** [comment]
As no one reported a similar bug anymore , this is considered fixed until proven otherwise
