### ISSUE TITLE
Switch to tab (from omnibox)

### ISSUE THREAD

**Issue by DragoCubed** [kiwibrowser/src.next#166]
This is possible on desktop browsers and on Firefox. This helps prevent users from accidentally opening a duplicate tab. 
Here's the Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1043372

**Comment by d3ward** [comment]
Related to chromium, feature not available in chromium yet , when the feature will be implemented in chromium it will be "automatically" added in Kiwi
