### ISSUE TITLE
Autofill Broken with Password Store 

### ISSUE THREAD

**Issue by dfrost16** [kiwibrowser/src.next#168]
Kiwi Version 93.0.4577.9
Android Version: 11 
[Password Store ](https://github.com/android-password-store/Android-Password-Store) an open source password manager doesn't work on kiwi. Even if kiwi is [Supported](https://github.com/android-password-store/Android-Password-Store/blob/c60a2534d5f63d448f9c26d6ac8a933a74249d84/autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FeatureAndTrustDetection.kt#L83) 

> Intended Behaviour

![Screenshot_20210724-143208](https://user-images.githubusercontent.com/24663673/126863600-dc0ffa12-2b78-4761-a06e-28eaa01bfb08.png)

> On kiwi
![Screenshot_20210724-143236](https://user-images.githubusercontent.com/24663673/126863634-9b3a35b9-174b-4954-a09d-89bd8cd8cf6e.png)

**Comment by dfrost16** [comment]
I really look forward to kiwi as my default android browser. And replacing brave with it. Thanks for all the hardwork by the dev and the community for this.

**Comment by Lartsch** [comment]
Duplicate of #64. Please close and add your comment there.

**Comment by hbarsaiyan** [comment]
It is not related to kiwi but this is the fix. Change the package name in command to Kiwi's https://github.com/android-password-store/Android-Password-Store/discussions/1364#discussioncomment-556590

**Comment by KaKi87** [comment]
> Duplicate of #64.

Correct.
