### ISSUE TITLE
Magnifier While Selecting Texts

### ISSUE THREAD

**Issue by gitdebpro** [kiwibrowser/src.next#170]
While selecting texts from webpage the selection magnifier is not available also the copy, paste and other option box just appear over the selected texts which disables the user to adjust the selection further.

**Comment by Y-T-G** [comment]
The text is covered only if the bottom toolbar is visible. Instead of being pushed up, the context menu gets pushed downwards, i.e. it retains the original behavior that occurs when the toolbar is at the top.

**Comment by kiwibrowser** [comment]
Fixed
