### ISSUE TITLE
Critical bug! The text selection context menu (cut, copy,...) covers the selection

### ISSUE THREAD

**Issue by andruska** [kiwibrowser/src.next#172]
The bug makes it impossible to use selection handles and see the selection properly.
Also the zoom window, when moving selection handles, also covers the selection and zooms the wrong place.

Android 10, Magic 11
Huawei

Selected same time here, writing this bug description. 

![Screenshot_20210724_144143](https://user-images.githubusercontent.com/7129124/126867339-6ac70ae0-770a-450d-8b10-facf134743d4.jpg)

Zoomed here at the "Also the zoom window,...", but zoom window depicts "Magic 11“.

![Screenshot_20210724_144528](https://user-images.githubusercontent.com/7129124/126867499-d39fb416-dacd-482b-ae24-73dd08cc10fc.jpg)

**Comment by Lartsch** [comment]
Occured for me once as well. But it works most of the time.

**Comment by Lartsch** [comment]
Also, duplicate of #170 . Please close this issue and add your comment there.

**Comment by andruska** [comment]
Merged with #170.
