### ISSUE TITLE
Kiwi makes blue light filter app close

### ISSUE THREAD

**Issue by maggotb** [kiwibrowser/src.next#173]
Device : Galaxy Tab SM-T550, Android 7.1.1

Kiwi version : 93.0.4577.9

[App](https://play.google.com/store/apps/details?id=com.lunatouch.eyefilter.pro)

The blue light filter app that I use keeps closing when I use the latest version of Kiwi

**Comment by KaKi87** [comment]
I get a *not found* error when clicking your link.

**Comment by maggotb** [comment]
The link works for me, I tried opening it in a private tab and got the same error. I didn't notice it was discontinued since it still works, weird

**Comment by KaKi87** [comment]
In that case, the app might be crashing because it is using some feature that is discontinued and is therefore incompatible with the latest Kiwi.
I therefore suggest that you use an up to date alternative.
Thanks

**Comment by kiwibrowser** [comment]
Ah, the crash is on the blue light filter app, yes I tend to agree that it may not be caused by Kiwi directly but rather the app trying to bind to elements that don't exist in recent Chromium
