### ISSUE TITLE
[BUG] wrong URL address for share function for some site like youtube

### ISSUE THREAD

**Issue by computHome** [kiwibrowser/src.next#175]
tested version: 93.0.4577.9

if the web site has changed the URL after page reload, the share function would share the wrong address

**Comment by karl-pae** [comment]
For YouTube: If you are using Kiwi's share function the URL is trimmed to "youtube.com". The address of the video is removed. This also happens in Google Chrome. 

But instead using YouTube's share it does work.

**Comment by d3ward** [comment]
This issue it's fixed in recent builds , actually it's fixed since implementations of new hub share
