### ISSUE TITLE
Bring back horizontal tab switcher

### ISSUE THREAD

**Issue by Hermit-fh** [kiwibrowser/src.next#177]
**Horizontal tab switcher _chrome flag_** was present in old chromium base build, in new chromium build it's remove by google if possible bring back the feature.

**Comment by kiwibrowser** [comment]
yes should be there tomorrow I think

**Comment by araujorm** [comment]
It's back. You guys are awesome ;) Thanks

**Comment by kiwibrowser** [comment]
Oh it's just the Vertical tab switcher :)
There is Horizontal coming

**Comment by araujorm** [comment]
Oops my bad... I misinterpreted the issue. But this was the option I wanted, so you guys are still awesome. Keep up and thanks again.

**Comment by kiwibrowser** [comment]
Done, wait for the next build on GitHub

**Comment by Hermit-fh** [comment]
Awesome it's back
