### ISSUE TITLE
[BUG] No Undo Button

### ISSUE THREAD

**Issue by StreamerMLG** [kiwibrowser/src.next#179]
Version: 93.0.4577.11 (457701115)

When you remove a tab it doesn't show up fix it please because sometimes it's annoying because I accidentally remove a tab and cannot go back thank you.

**Comment by Lartsch** [comment]
Which tab view are you using? I'm using the grid layout and still get the "Undo" bar @StreamerMLG

**Comment by s1710335** [comment]
I am the same person as #183.
I'm using the old("original") Tab view and have a similar situation.
Also, the toolbar is located at the top.

**Comment by Lartsch** [comment]
Okay, I can confirm that ONLY with the "Original" tab style. Others are working fine. So this is an actual bug.
@s1710335 Would you mind closing your other issue to help keep this repo tidy? :)

**Comment by s1710335** [comment]
I understand. I'm sorry.

**Comment by Lartsch** [comment]
@s1710335 No worries! Thank you :)

**Comment by StreamerMLG** [comment]
> Okay, I can confirm that ONLY with the "Original" tab style no "Undo" button appears. Others are working fine. So this is an actual bug.
> @s1710335 Would you mind closing your other issue to help keep this repo tidy? :)

Yes i can confirm this default and original doesn't show undo button. Hope to get this fix in next version.

**Comment by kiwibrowser** [comment]
Triage: affects original and horizontal due to crash in UndoController

**Comment by StreamerMLG** [comment]
> Triage: affects original and horizontal due to crash in UndoController

Soo it's literally a bug thank you.

**Comment by kiwibrowser** [comment]
Fixed in upcoming build
