### ISSUE TITLE
The bottom toolbar doesn't hide while scrolling

### ISSUE THREAD

**Issue by s1-en** [kiwibrowser/src.next#182]
I saw a post on the src repo to post here instead so I'm posting this here but the issue is with the stable version released on Google Play Store, not the Next version here.

Anyway, the issue is that while scrolling, the toolbar at the toolbar (placed at the bottom) does not hide and stays open

**Comment by Lartsch** [comment]
@s1-en As far as I can tell, the Play Store version IS the "next" version already. Anyways, on what sites do you experience this? Other issues with the bottom bar aside, I had none with scrolling / hiding.

**Comment by s1-en** [comment]
@Lartsch it happens on all sites actually, on some few random occasions, it will hide properly, but most of the times, it doesn't regardless if I'm on the exact same site as before when it worked. If it helps, here are my accessibility settings:

![IMG_20210725_193340](https://user-images.githubusercontent.com/63731521/126897595-a463a092-229f-4602-aa6a-565d4cfc0e6f.jpg)

**Comment by Lartsch** [comment]
I also think there is some kind of bug with it, but I can't get it reproduced reliably. Maybe when other issues with the bottom address bar are addressed (like wrong click locations) this gets sorted out

**Comment by MmyGgithubAaccount** [comment]
Are you using some kind of accessibility service? Auto hide doesn't work if certain accessibility services are turned on. Not sure exactly what determines which accessibility service causes this, nor if this is a chromium or android issue

**Comment by s1-en** [comment]
@Lartsch Hopefully, it's not a big issue right now in portrait mode but gets rather cramped in landscape

@MmyGgithubAaccount I have a number of Accessibility services ranging from password manager to Tasker, to other small utilities, but I never had any problems with the previous 2020 version of Kiwi Browser

**Comment by MmyGgithubAaccount** [comment]
@s1-en check if you can replicate this behaviour in chrome. If yes then this change was most likely introduced after chromium 77. If not this might be a new kiwi specific issue

**Comment by s1-en** [comment]
@MmyGgithubAaccount Yes, it happens with Chrome as well, Bromite too which is just a slightly modified Chrome. I actually have never used Chrome as my browser on this phone, ever since I got it, I disabled Chrome immediately and downloaded Kiwi

**Comment by kiwibrowser** [comment]
When there are accessibility services to stuck toolbar is enabled. I think the setting is ignored in this case in Kiwi Next so could check that

**Comment by ayacnc** [comment]
Two phones with the same app version 93.0.4577.18
Redmi K30pro Android 11,with accessibility services on,"Toolbar always on screen" off,but the toolbar seems always on screen
Huawei P20 Android 10,with accessibility services on,"Toolbar always on screen" off,the toolbar can be auto hide normally

**Comment by d3ward** [comment]
Tested latest Kiwi v116 and the bottom toolbar hides properly when scrolling .

**Comment by Swap-File** [comment]
If anyone is curious, I've found that turning on either AutoInput or Macrodroid's accessibility service will stop the toolbar from hiding in Chrome and Kiwi.

AIO Launcher, Bitwarden, and Classic Power Menu will not prevent the toolbar from hiding.

It would be really nice to have a toggle somewhere to override the stuck toolbar.  

I don't want to give up my AutoInput automation, but I also want to hide the toolbar in my browser.  For now I think I'm going to start using both Kiwi and Fennec.

**Comment by debiedowner** [comment]
This issue is still present; I've found that enabling the accessibility service of Key Mapper causes this problem, Glimpse Notifications doesn't.
