### ISSUE TITLE
[BUG] Double-click to zoom not working

### ISSUE THREAD

**Issue by Lartsch** [kiwibrowser/src.next#185]
Hey,

apparently, the usual double click to zoom feature does not work in Kiwi on images after the rebase.

**Comment by KaKi87** [comment]
Does such feature exist on Chromium for Android ?

**Comment by Lartsch** [comment]
@KaKi87 I think this worked on previous Kiwi versions, yes.

**Comment by Lartsch** [comment]
This works as in earlier versions in the latest build.
