### ISSUE TITLE
Remove unneeded permissions

### ISSUE THREAD

**Issue by MrFeelgoood** [kiwibrowser/src.next#188]
I noticed that all browsers like brave, vivaldi, bromite and so on that are based on new chromium versions don't require contacts permission. Are contacts really needed for this new chromium based kiwi browser? I think it could be nice to remove unnecessary permissions if possible.

**Comment by kiwibrowser** [comment]
The contacts permission is upstream:
https://source.chromium.org/chromium/chromium/src/+/main:chrome/android/java/AndroidManifest.xml;l=59?q=android.permission.READ_CONTACTS&ss=chromium

On recent Android version, permissions are on-demand, so the contacts permission would trigger asking the user.

It's used in the contacts picker in Chromium: https://source.chromium.org/chromium/chromium/src/+/3fa1a096e48b6a6378831f8d5b61facdccd0045f
