### ISSUE TITLE
Brave Search Integration

### ISSUE THREAD

**Issue by gitdebpro** [kiwibrowser/src.next#19]
I can select brave Search as default search engine but on doing that search function crashes frequently.

**Comment by d3ward** [comment]
This bug has been fixed .

**Comment by d3ward** [comment]
Actually this is a persistent issue on latest builds , it make crash Kiwi and impossible to change back to another search engine

**Comment by KaKi87** [comment]
Has the issue been fixed ? Or is it a duplicate of another one ? If not, let's reopen that one.

**Comment by gitdebpro** [comment]
> Has the issue been fixed ? Or is it a duplicate of another one ? If not, let's reopen that one.

sorry it's fixed closing now

**Comment by kiwibrowser** [comment]
Yes it's fixed
