### ISSUE TITLE
A black bar appears at the top after long pressing on the address (on Xiaomi phones)

### ISSUE THREAD

**Issue by cbwee** [kiwibrowser/src.next#192]
The black bar appears after long pressing on the address in the address bar, and the only way to remove it is to close the browser and open it again.

It looks like this issue only exists on Xiaomi phones running MIUI 12/MIUI 12.5 with Android 10/Android 11.

This issue also exist in most Chromium-based browsers on Android, the only ones that do not have this issue on Android are Yandex Browser and Opera Browser.

I have already reported this issue to Google, since even Chrome itself has this issue, but they still have not fixed it.
https://bugs.chromium.org/p/chromium/issues/detail?id=1219369

Please see the screen recording below.

https://user-images.githubusercontent.com/34395942/126926808-63abdf9f-aac5-40f5-8411-b4d14d1c8043.mp4

**Comment by Lartsch** [comment]
Looks like another bottom bar issue. The vertical space that the black area occupies seems to fit to height of the address bar.

**Comment by d3ward** [comment]
@cbwee do tou still have that issue ?

**Comment by cbwee** [comment]
> @cbwee do you still have that issue ?

Yes, the black bar still appears in Kiwi 94.0.4606.56, running on MIUI 12, Android 10 (POCO M3).

But on another phone that runs MIUI 12, Android 9 (Redmi 6 Pro), this issue doesn't exist.

So this is an Android 10/Android 11 specific issue.

**Comment by d3ward** [comment]
@cbwee what about with recent v98 builds ? do you still have that black bar ?

**Comment by cbwee** [comment]
> do you still have that black bar ?

No, now the black bar doesn't appear in Kiwi Browser 96, or any other browser based on Chromium 96.

**Comment by cbwee** [comment]
I am not sure if it is because I have recently updated the UI/Android versions on my phone, so the black bar doesn't appear, or if it is already fixed in Chromium.
