### ISSUE TITLE
Bottom toolbar hides elements on some sites

### ISSUE THREAD

**Issue by geoslake** [kiwibrowser/src.next#199]
Hi

Im using the "bottom toolbar" option, and on youtube mobile website, links at the bottom "home / trending / subscriptions / library" become partly hidden and unclickable.
On the gmail mobile website, the toolbar that should appear at the bottom when you select multiple mails is totally hidden.

Thanks !!

**Comment by Lartsch** [comment]
Probably related to #90

**Comment by d3ward** [comment]
This problems has been fixed with updates for bottom bar improvements . Consider closing the issue if you don't have that bug anymore
