### ISSUE TITLE
i cant open any link in bookmark,with 'Desktop mode by default' checked .A serious bug in  latest 93.0.4577.11

### ISSUE THREAD

**Issue by rick999999** [kiwibrowser/src.next#200]
I've upgrade to 93.0.4577.11.

i cant open any link in bookmark,with 'Desktop mode by default' checked in 93.0.4577.11.

i have to long touch the link and choose to open it in new tab or I have to switch to mobile mode and then i can open any link in bookmark ....

plus,it even keeps jumping back to mobile mode time by time with 'Desktop mode by default' checked

as long as i keep the 'Desktop mode by default' checked,issues above exist

there were no such bugs in any git2001915 version and before
i tested two devices and they have the same bugs
android os: 6.0 and 8.0

thx in advance!

**Comment by KaKi87** [comment]
Can you provide accurate reproduction steps ?

Here's what I tried :
1. Open accessibility settings
2. Enable desktop mode by default
3. Open a new tab *(homepage loads in desktop mode)*
4. Open bookmarks
5. Click on bookmark *(bookark loads in desktop mode)*
6. Click on any link *(link loads in desktop mode)*

I encountered no issue during this test while running latest Kiwi Browser from Play Store.

**Comment by d3ward** [comment]
Quite old bug and pretty sure is fixed with latest Kiwi v116 . 
( @rick999999 Feel free to reopen if issue persist )
