### ISSUE TITLE
[Extension] Can't log in to google account when using Floccus.

### ISSUE THREAD

**Issue by Dodgexander** [kiwibrowser/src.next#202]
https://floccus.org/

Used to work with the old Kiwi browser but doesn't work since the chromium update. Hitting 'Login with google' after trying to setup a google drive sync does nothing.

Expected behavior: Login with google would open a browser window that lets you login, to successfully link accounts.

Here's an open issue with Floccus, where they pass the blame for Kiwi for not working, despite them listed Kiwi as one of their supported browsers:
https://github.com/floccusaddon/floccus/issues/921#issuecomment-886474011

**Comment by gcphym** [comment]
I can't log in either

**Comment by gcphym** [comment]
I have the same problem

**Comment by sd3993** [comment]
It's not just Floccus - The google sign in does not work with in others extensions either like Tab Session Manager.

This does seem to be a bug in the Kiwi Next source code.

**Comment by Dodgexander** [comment]
@kiwibrowser are you still aware of this issue? Was reported first on floccus' GitHub so wanted to make sure it's not lost.
Last comment in August was 'it will be fixed very soon'.

**Comment by catshitz** [comment]
same here, still got this issue 94.0.4606.56

**Comment by keiviv** [comment]
@kiwibrowser We all would be extremely grateful for the fix. The sad irony is that @d3ward just recently [recommended](https://github.com/kiwibrowser/sync/issues/2#issuecomment-943307918) Floccus as a substitute for the discontinued /sync project. 

I've already seen people whith bookmarks tattoos, save the humanity!

**Comment by ryanwwest** [comment]
Still a problem

**Comment by prono69** [comment]
Ya the issue still there :sweat:

**Comment by prono69** [comment]
> Still a problem

U can try the old kiwi browser (kiwibrowser clasic) and then export account config

**Comment by 424344** [comment]
workaround: login into floccus on a desktop browser (using gdrive option), then export the floccus config, copy the config file to phone, then import the config in floccus. I've tried some month ago and it was working.
