### ISSUE TITLE
[Feature Request] Page zoom control

### ISSUE THREAD

**Issue by Y-T-G** [kiwibrowser/src.next#203]
It would be nice to have an adjustable zoom control for each page like it exists for desktop chrome. I was previously using the [Zoom extension](https://chrome.google.com/webstore/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd?hl=en-GB) but it no longer seems to work (the CSS zoom feature) after the update. It would be better if it was natively supported and if it can also remember the last zoom value when revisiting the same site.

**Comment by gnadelwartz** [comment]
https://chrome.google.com/webstore/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd

his works fr me, in Addition there is now a feature request for zoom #227 

pls close isuue if addon fulfil your request

**Comment by d3ward** [comment]
I'll close that issue and we will keep the issue 227 as it is more detailed

**Comment by shadichy** [comment]
> https://chrome.google.com/webstore/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd
> 
> this works fine for me, in addition there is now a feature request for zoom #227
> 
> pls close issue if addon fulfill your request

not work as what i expected, as mentioned #227
