### ISSUE TITLE
Kiwi won't save selected theme after restart app

### ISSUE THREAD

**Issue by samlux04** [kiwibrowser/src.next#204]
Kiwi won't save selected theme. It's always turned back to "dark" after restart. Even though "dark" isn't even the default(?)

**Comment by kiwibrowser** [comment]
Thanks, I just fixed it, this is a bug in the settings migration process from classic to next that could make it happen multiple times.
The fix will be able with the upcoming build (likely tomorrow)

**Comment by samlux04** [comment]
Thanks. You don't need to rush to publish new update. Take your time.
