### ISSUE TITLE
In night mode backgrounds of native button and select inputs doesnt invert

### ISSUE THREAD

**Issue by andruska** [kiwibrowser/src.next#206]
Normal mode:

![Screenshot_20210727_032931](https://user-images.githubusercontent.com/7129124/127076159-8c80dfd3-f1e4-489e-ac38-2dc5b707aaee.jpg)

Night mode. Adjusting Night mode contrast doesnt help:

![Screenshot_20210727_032914](https://user-images.githubusercontent.com/7129124/127076262-48c64b03-36e4-4835-ba5c-93ed571182e7.jpg)

Night mode in Dark Reader in Firefox:

![Screenshot_20210727_033735](https://user-images.githubusercontent.com/7129124/127076664-ab8c85e5-081a-40f1-8c79-8262b0b62624.jpg)

Screenshots are taken from:
http://www.eki.ee/dict/evs/index.cgi?Q=Brauser&F=V&C06=en

**Comment by kiwibrowser** [comment]
Tere,

Noted, I'll make some adjustments in the coming days regarding inputs in night mode.

**Comment by d3ward** [comment]
It's been a while , but with latest Kiwi v116 this is not bugged anymore . Kiwi built-in night mode works properly on that site
