### ISSUE TITLE
[Bug] Bottom toolbar bar hides browser menu

### ISSUE THREAD

**Issue by joelocandol** [kiwibrowser/src.next#207]
When I active the bottom toolbar the menu appears like in the screenshot. The only way for it to appear correctly is open it with the keyboard showing up on the screen
![Screenshot_20210726-220216](https://user-images.githubusercontent.com/59028737/127083480-312b4999-5e4a-45f0-8590-cef812b5b68e.png)

**Comment by kiwibrowser** [comment]
Wow, this is crazy.
There are two possibilities:
1 ) 1st possibility: This means the menu is anchored at the wrong place. What phone do you have ?
2) 2nd possibility: This means the menu is partially empty. Can you scroll up this menu ?

**Comment by joelocandol** [comment]
Some unknown cheap brand: Oukitel CT
And, yes, i can scroll until the "translate" option, but I can still seeing the "add to the homescreen" option, but I can't reach it

**Comment by d3ward** [comment]
@joelocandol do you still face that issue ?

**Comment by joelocandol** [comment]
Yes, currently I'm in the version 93.0.4577.52 and the problem is still present
![Screenshot_20210821-144122](https://user-images.githubusercontent.com/59028737/130331910-a09880db-17da-44ef-bb63-8ba4830a97d5.png)

**Comment by dtitbd** [comment]
Will you ever fix this problem? Cause it's really stops me from using kiwi.

**Comment by d3ward** [comment]
> Will you ever fix this problem? Cause it really stops me from using kiwi.

You still have the bug even on latest 98v builds ?

**Comment by dtitbd** [comment]
@d3ward 
On the last version from GP (98.0.4758.60, updated today ) it's finally worked. Thanks a lot!

**Comment by dtitbd** [comment]
@d3ward 
Sorry for disturbing, but there are a couple of problems with bottom toolbar yet. 
Only one line with search suggestions is displayed. 
When scrolling up, the page freezes until toolbar is shown. Easier to see in the [video](https://cloud.mail.ru/public/FcJq/6rfJ17cHs).
Oh, and the menu opens only half the screen, not the whole.
Should I create a new issue or it's fine to talk here?

**Comment by d3ward** [comment]
@dtitbd any chance that with latest Kiwi v116 from Github everything is fixed for you ? This update brings a lot of bottom toolbar improvements

**Comment by d3ward** [comment]
A week has passed with no response. We will close this, assuming that the problem has been solved for the user. ( if not, @dtitbd you can reopen the ticket )
