### ISSUE TITLE
browser crash

### ISSUE THREAD

**Issue by isora0** [kiwibrowser/src.next#209]
browser fc if install extension from google store

**Comment by kiwibrowser** [comment]
which extension are you trying to install ?

**Comment by moe-lee** [comment]
ublock origin

**Comment by kiwibrowser** [comment]
Go to kiwi://crashes and press the Send report button
and then give me the version you are running ( kiwi://version )

**Comment by moe-lee** [comment]
ok,thank you for this great job

**Comment by moe-lee** [comment]
i have sent crash report /version(17) /wish you fix it

**Comment by d3ward** [comment]
@moe-lee Hello , do you still have the issue ?

**Comment by d3ward** [comment]
@isora0 I am closing this. Feel free to reopen if the problem still exists.
