### ISSUE TITLE
[BUGs] Some bugs on mobile & tablet

### ISSUE THREAD

**Issue by nostalgickd** [kiwibrowser/src.next#210]
Here are some bugs I've encountered on both, tablet and phone:

- When entering uBlock Origin's element picker mode, the browser jumps to the last opened tab & you have to manually navigate to the tab where the element picker is active.

- AMP Pages not opening from Google Search. [Test link](https://www.google.com/search?q=bbc+news&source=lmns&tbm=nws)

- OK/Cancel buttons not showing for HTML Select options
  The font color seems to be white, so it blends in. 
  Using default light theme. [Test link](https://tlgur.com/d/g577ob28)
  Same for HTML Color input element.

**Comment by d3ward** [comment]
- This seems to be fixed , check latest versions  
- AMP : #225
- The test link you provided , doesn't work + the standard HTML Select does not include buttons like OK/Cancel anywhere , the input color include the buttons . Maybe you are confusing the standard HTML components with probably custom ones ? Consider sharing a new working link
