### ISSUE TITLE
[BUG] Silent notification making sound.

### ISSUE THREAD

**Issue by DeKleineKobini** [kiwibrowser/src.next#212]
Notifications that have the `silent` attribute in options set to `true`, still make a sound.

Going to site settings and disabling sound for that url (service worker in this case), doesn't work either.

**Comment by d3ward** [comment]
Can you try with latest Kiwi v116 ? , I know it's been a while and not sure if you still use Kiwi. Closing this, but feel free to re-open if you still have the issue
