### ISSUE TITLE
Bring back autoplay policy or another means to block autoplay

### ISSUE THREAD

**Issue by Maxxee** [kiwibrowser/src.next#216]
This setting is more than needed for a mobile browser.

**Comment by edward5375** [comment]
Yup this is an essential feature

**Comment by jututt** [comment]
Tried Disable HTML5 Autoplay (Reloaded) extension but doesn't work

**Comment by jututt** [comment]
AutoplayStopper 1.9.4 extension seems to do the job for the moment - chromium 94

**Comment by d3ward** [comment]
#150
