### ISSUE TITLE
Add a shortcut to share option

### ISSUE THREAD

**Issue by naifqarni** [kiwibrowser/src.next#218]
Add a shortcut of the last used app to share
like chrome
Example:
![Screenshot_20210728-182818](https://user-images.githubusercontent.com/73849082/127350772-931a350e-79df-45be-a36c-b25522f942a0.png)

**Comment by karl-pae** [comment]
I think installing new builds resets this setting. It is available for me after I use share function once.

**Comment by Lartsch** [comment]
Agreeing with @karl-pae. I think this issue can be closed @naifqarni

**Comment by naifqarni** [comment]
> Agreeing with @karl-pae. I think this issue can be closed @naifqarni

Does it work when you share something that isn't in the chrome share sheet? I mean you press more then choose an app and see if it is there

**Comment by Lartsch** [comment]
@naifqarni You got a point there. When choosing an app after clicking "More", the share button resets its shortcut. Not sure if this is to be considered a bug but I guess so. Nice find!

**Comment by Lartsch** [comment]
@naifqarni I would suggest to close this issue and create a new one using the Bug Report template and a more appropriate title.

**Comment by naifqarni** [comment]
> @naifqarni I would suggest to close this issue and create a new one using the Bug Report template and a more appropriate title.
