### ISSUE TITLE
Disable automatic tab refreshing/discarding

### ISSUE THREAD

**Issue by hoiou** [kiwibrowser/src.next#219]
In the previous version of Kiwi tabs didn't refresh every time I switched to them, but they seem to do it without fail on the newest version.

**Comment by gnadelwartz** [comment]
@kiwibrowser 

FYI: I reported this problem also (by mail) for my Chrome tabet.
I had to wipe all Kiwi data becasue of ongoing chrashes and then reinstall all extension.

Suprise: refresh on tab/app change is gone!

**Comment by hoiou** [comment]
> @kiwibrowser
> 
> FYI: I reported this problem also (by mail) for my Chrome tabet.
> I had to wipe all Kiwi data becasue of ongoing chrashes and then reinstall all extension.
> 
> Suprise: refresh on tab/app change is gone!

Gave that a try and unfortuantely didn't work for me.

**Comment by gnadelwartz** [comment]
looks like there are many possible tiggers :-( 
some reports with specific settings enabled, others evertime regardless of settings and addons ... 

did you erase data from within kiwi or from android settings?
I did the latter one, this removes everthing except the app. its like the app was newly installed on a virgin device.

**Comment by gnadelwartz** [comment]
@kiwibrowser I can confirm that wiping/reinstall kiwi fix the relaed issue if it happen after an in place update.

 on 3 Devices the reload issue was fixed for me

    Mobile: Xiaomi Note 9 pro
   Tablet: Lenoveo iBook, ANdroid 7.1.1
   Chromebook: Acer convertible with lastes Chrome OS

fortunately I have all my Passords in Bitwarden :-)

**Comment by kiwibrowser** [comment]
Hello,

I made an adjustment in the tab discarding algorithm in the last build, if you are interested to try (otherwise it goes tomorrow or so on the Play Store)

**Comment by kiwibrowser** [comment]
@gnadelwartz your intuition about cache may be right as well, I'm intrigued by the results

**Comment by rdsylsq** [comment]
already fixed   com.kiwibrowser.browser-1087859047-arm-github.apk

**Comment by gnadelwartz** [comment]
@kiwibrowser  thank you for the latest update in Play Store, Kiwi feel much more responsive and refresh of tabs seems to be gone with desktop mode enabled also. Great Work!
