### ISSUE TITLE
Add : Hey there arnaud can you add resource sniffer/grabber

### ISSUE THREAD

**Issue by Raul1198** [kiwibrowser/src.next#220]
Resource sniffer/grabber  an option by which the browser could give an option to download media (video,gif..etc) when detected in the web page

**Comment by d3ward** [comment]
> Noted.
> 
> In the meantime, maybe kiwi://media-internals could be helpful for you to find media to download ?
> Otherwise, via extensions.

This seems to be the best solution for the issue , closing the issue
