### ISSUE TITLE
Do you plan to work on UI of the app? 

### ISSUE THREAD

**Issue by karl-pae** [kiwibrowser/src.next#221]
If yes, I was wondering if you can adopt some of the features from Samsung browser.

- Tabs list appears on bottom half of the screen and is scrollable

- Settings menu is short and easy to operate also like Microsoft Edge

- redesign homepage icons of the pinned website. e.g favicon sits in rectangular shape and is accessible from search bar.

For demo of above list, try Edge and Samsung Browser. They have done good job in this terms but since they do not provide bottom bar facility, I dislike those.

Lets make Kiwi Browser, mainstream browser ❤️❤️

**Comment by samlux04** [comment]
About tab list I'm thinking of Vivaldi. Which is nice in phone.
