### ISSUE TITLE
[Feature request] Ability to import passwords

### ISSUE THREAD

**Issue by Cyberavater** [kiwibrowser/src.next#223]
I don't want to manually check the passwords and type them in kiwi. How do I sync and use all saved passwords from Google Chrome directly in Kiwi.

If it's currently not possible please add the feature so that I can directly use passwords from Google as if I'm on the desktop.

**Comment by Manu99it** [comment]
Google removed the possibility to use Chrome Sync in chromium based browsers. Also, kiwi never had this feature. If you want to sync favourites you can do it with floccus or, if it will work in future, xBrowserSync. If you want to import password a feature to do so would be awesome, but syncing them is not supported. If you want you could use another password manager like BitWarden

**Comment by Cyberavater** [comment]
If it's not possible, then the best option would be to have an import passwords feature, I guess.

**Comment by gnadelwartz** [comment]
i second use of bitwarden as password storage. its cross browser, cross OS, has import/export and is free in both senses  (beer and open source.)

**Comment by d3ward** [comment]
Linking this to #122
