### ISSUE TITLE
The `Hide annoying ads` option is blocking articles on some websites

### ISSUE THREAD

**Issue by cbwee** [kiwibrowser/src.next#226]
**Describe the bug**
On some websites, articles are blocked after I enabled Hide annoying ads in the menu of Kiwi Browser.

**Expected behavior**
The articles should not be blocked when the option is enabled.

**Screenshots**
`https://www.kocpc.com.tw/archives/394990`

With the option disabled
<img src="https://user-images.githubusercontent.com/34395942/127594779-9f4e03c6-13f6-4e1f-8178-3b4729ab7f52.jpg" width="200"/>

With the option enabled
<img src="https://user-images.githubusercontent.com/34395942/127594796-1db0c9ac-8044-4d3c-b0c4-db93b8ead575.jpg" width="200"/>

**Smartphone (please complete the following information):**
 - Device: Xiaomi POCO M3
 - Android Version : Android 10
 - Kiwi Browser Version 93.0.4577.18

**Comment by gnadelwartz** [comment]
as its really hard to do ad blocking correnct for all websites (espefcially non latin languages) I suggest to use a adblocker addon. they usually has blocklists for different countries and languages plus simple opt out for individual sites.

e.g. ublock origin

**Comment by Oranko** [comment]
I too would strongly suggest you use ublock origin for this purpose

**Comment by Lartsch** [comment]
I agree with @gnadelwartz and @Oranko.
In fact, it could be discussed if Kiwi's ad blocking is actually a feature worth to maintain, considering the many options Kiwi offers by supporting extensions. @kiwibrowser

**Comment by d3ward** [comment]
Tested on Kiwi v116, as built-in adblock has been greatly improved, article is no longer blocked.
