### ISSUE TITLE
[Auto- Translate]

### ISSUE THREAD

**Issue by kryptobolt200528** [kiwibrowser/src.next#229]
Hey can you implement auto translate to english/any other language...

I know that the inbuilt translator can do that..
But that doesn't seem to be working on all pages

**Comment by Oranko** [comment]
Hey, can you give an example of such a page
I would like to try it out

**Comment by d3ward** [comment]
Please consider opening a new issue with the right template -> [New Issue](https://github.com/kiwibrowser/src.next/issues/new/choose)
