### ISSUE TITLE
[BUG] The browser displays two loading bars when opening web page "in app "

### ISSUE THREAD

**Issue by edward5375** [kiwibrowser/src.next#234]
When opening an url "in app" the browser shows two loading bars

The browse should display only one loading bar .

![Screenshot_2021-07-31-18-35-45-45](https://user-images.githubusercontent.com/88190002/127741101-f475ccad-faf4-44f3-bdf3-15bf24aeb13d.jpg)

 - Device: Realme x7 Max
 - Android Version : A11 
 - Kiwi Browser Version 90.0.4577.18

**Comment by Lartsch** [comment]
Duplicate of #79 . Please close this issue @edward5375
