### ISSUE TITLE
Bring back old edge swipe ( the new one seems to have bugs )

### ISSUE THREAD

**Issue by cauerego** [kiwibrowser/src.next#235]
is today first time we talk?

thanks so much for doing kiwi! if not for so many bugs, it would be my only browser...

latest update introduced a new feature that is making me think to demote it to secondary, though:

edge navigation.

previous version i could navigate back and forth anywhere on the page!

now it's conflicting with android navigation gestures, and it simply doesn't work anymore!! 😭

if this report is any good to you, and you can act on it to fix it for me, i can give you many more reports and improve the quality up to where you need.

thanks! 😘

**Comment by kiwibrowser** [comment]
Hey,

In the recent build, edge swipe has been improved. If you want to share the opinion on the GitHub build :)

**Comment by cauerego** [comment]
sure!

can you make the github build with different signature, so we can have both installed side by side?

**Comment by kiwibrowser** [comment]
There is, as a different package:
com.kiwibrowser.browser.[dev] will install separately

**Comment by cauerego** [comment]
sorry for the lazy questions!  😔

couldn't see any difference. how was it improved?

**Comment by d3ward** [comment]
Kiwi got updated so much since that issue. And latest v116 have edge swipe for moving forward/backward. Closing this as is very old
