### ISSUE TITLE
Getting a lot if 400 Bad Request

### ISSUE THREAD

**Issue by ballo** [kiwibrowser/src.next#237]
Previous version was giving me more of these than the initial version, but the latest version takes it to a new level. Can't access reddit, AliExpress, google store, and many, many others. As last time, using incognito seems to resolve this always (although not a work-around for installing plugins which I have to do manually). Disabling extensions doesn't help.
![Screenshot_20210726-183252_Kiwi Browser](https://user-images.githubusercontent.com/631311/127081036-b846965c-4c12-4868-886e-13e1b8193e51.jpg)

**Comment by d3ward** [comment]
@ballo did you still have the issue with latest builds ? Some users from India had a similar problem and now are saying that it's fixed

**Comment by ballo** [comment]
I'm not waiting data downloading test builds. I'm running the latest broken Google play store build (honestly you guys should switch to an app store that doesn't police your behavior like f-droid)

**Comment by ballo** [comment]
> Do you use a VPN or a proxy ?
> If you go to https://nyt.com and press the pad-lock, and then "Cookies" how many "Cookies" do you see ?
> If you refresh, then how many ?
> If you refresh a second time, then how many ?

I gave up trying to load that web site. It has to be several megabytes large.

**Comment by d3ward** [comment]
@ballo I'm closing this as it's quite old. Feel free to reopen it if the problem still exists.
