### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by moe-lee** [kiwibrowser/src.next#239]
1.download extension from google webstore still crash last github release (20) chrome://crashed reported did not fix
2.load extension from .crx files , i clear cache,extension  disappear...last github release
wait you fix it,thank you for this great job

**Comment by Lartsch** [comment]
You posted this issue two times, could you please close one of them? (#241) @moe-lee

**Comment by d3ward** [comment]
> You posted this issue two times, could you please close one of them? (#241) @moe-lee

than you

**Comment by moe-lee** [comment]
I'm so sorry,thank you for close it timely
