### ISSUE TITLE
Switch tabs automatically refresh in default desktop mode

### ISSUE THREAD

**Issue by rdsylsq** [kiwibrowser/src.next#242]
**Describe the bug**
 
Settings, accessibility, open the default desktop mode, when switching between several tabs, each tab will be automatically refreshed.  This switch will not refresh when in phone mode
**To Reproduce**

**Expected behavior**

I hope that it will not refresh automatically when switching tabs, just like the mobile phone mode, so as to maintain the smoothness of browsing
**Screenshots**

**Smartphone 
 - Device: Samsung s10
 - Android Version : android 11
 - Kiwi Browser Version [  90.0.4577.20 ]

**Additional context**

**Comment by gnadelwartz** [comment]
duplicate #219 pls close and comment there
