### ISSUE TITLE
Shaking screen when scrolling to video player

### ISSUE THREAD

**Issue by SylwesterDu** [kiwibrowser/src.next#249]
When scrolling to video player, window is shaking up and down rapidly and stops after about 2 seconds. Then window is shaking each time I try to scroll, making it unable to scroll anywhere so I need to restart app
 - Kiwi Browser Version 93.0.4577.17
 - Xiaomi Redmi note 10s

**Comment by Lartsch** [comment]
Could you screen record this issue and upload here? @SylwesterDu

**Comment by kiwibrowser** [comment]
Is text reflow / rewrap enabled ?

**Comment by SylwesterDu** [comment]
> Could you please screen record this issue and upload it here? @SylwesterDu

https://drive.google.com/file/d/1-Ze70k3pvzFwE7NzTZ0MiLawKMQrV21u/view?usp=drivesdk

> Is text reflow / rewrap enabled ?

No, it is disabled

Looks like this issue appears only in the site recorded on video. I think it is not site fault, other browsers, for example brave work correctly

**Comment by Lartsch** [comment]
No idea what's going wrong there, I think we would have to actually look into the site's source in terms of the video player to understand what's going on. A second site where this issue occurs would probably come in handy.

**Comment by SylwesterDu** [comment]
After updating to chromium 94 bug disappeared. Thanks for your work
