### ISSUE TITLE
omnibox issue

### ISSUE THREAD

**Issue by isora0** [kiwibrowser/src.next#250]
sometimes search from omnibox may no response or long time response,i believe my network is ok,and i test chromium browser,no this problem.

**Comment by Lartsch** [comment]
Could you elaborate further? @moe-lee For example with a screen record / screenshots.

**Comment by moe-lee** [comment]
ok,I will give you screen record with Telegram,Whats your Telegram ID?thank you.

**Comment by karl-pae** [comment]
Hi, download the latest build from here:
https://github.com/kiwibrowser/src.next/releases

Do you have any extension installed? This type of issue can occur due to extensions. You may try after disabling all and then check..

and revert if the issue still occurs, else you can close this issue.

**Comment by d3ward** [comment]
@isora0 I think this is no longer an issue, lots of updates since 2021 and improvements to the toolbar. If you still have a problem, feel free to reopen the issue with more details.
