### ISSUE TITLE
List tab switcher opens keyboard

### ISSUE THREAD

**Issue by MooShuOrc** [kiwibrowser/src.next#253]
When the tab switcher is set to List, every time a tab is selected (from the tab menu, not via swiping), the address bar ("omnibox") is selected and the keyboard opens.
If this is intended for some reason, please make it optional.

 - Device: LG Aristo 2
 - Android Version : 8.1
 - Kiwi Browser Version: 93.0.4577.22

**Comment by karl-pae** [comment]
Not happening with me. Are you on latest release? Also could you upload a video?

**Comment by MooShuOrc** [comment]
I don't have high-speed data, so no videos.
I don't know if 93.0.4577.20 is the latest ver., but it's the latest available in my Play Store.

**Comment by MooShuOrc** [comment]
Update: Still happening as of version 94.0.4606.54.

**Comment by MooShuOrc** [comment]
Still in 96.0.4664.46.

**Comment by karl-pae** [comment]
Hi, download the latest build from here:
https://github.com/kiwibrowser/src.next/releases

and revert if the issue still occurs, else you can close this issue.

**Comment by MooShuOrc** [comment]
I appreciate your attempt to clean up old bugs, but it's still not fixed.

**Comment by karl-pae** [comment]
I see no such issue. 🤔😕

**Comment by MooShuOrc** [comment]
It may only show up on Android 8.1, or on v7a executables, or it could be a side effect of LG bloatware screwing with things, or some combination thereof.

I don't have the programming skill to debug it, and it looks like it's an uncommon error, so I guess I'll just have to live with it.

**Comment by MooShuOrc** [comment]
I got a new phone (ARM64, A10), and the List tab switcher now works correctly for me.

It's likely that the issue is still affecting some small number of people out there, but if so, they don't care enough to comment. Since I no longer care about it, feel free to close the issue if you think it appropriate.

**Comment by MooShuOrc** [comment]
If anyone else is affected by this, they don't care enough to comment, so I'm closing it.
