### ISSUE TITLE
Some sites will not open in supported apps

### ISSUE THREAD

**Issue by s1710335** [kiwibrowser/src.next#255]
**Describe the bug**
Won't open in external apps, which many sites support. (e.g. Amazon, bilibili, pixiv, etc.)
※YouTube opens normally in external apps

**To Reproduce**
For example, you can search for "XX (product name)  Amazon" and display Amazon product links in the search results. Tapping on that link does not open the Amazon app; Chrome opens the Amazon app fine.
Also, pressing and holding the link and selecting "Open in external app" will not open the external app.

**Expected behavior**
I want links to automatically open in external apps when I tap them.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: GALAXY S20 FE 5g
 - Android Version :  A11
 - Kiwi Browser Version :93.0.4577.20(latest)

**Additional context**

**Comment by Lartsch** [comment]
Duplicate of #94 . Please close @s1710335

**Comment by s1710335** [comment]
I'm sorry. I didn't realize
