### ISSUE TITLE
New type of tab switcher

### ISSUE THREAD

**Issue by naifqarni** [kiwibrowser/src.next#257]
is it possible (and easy?) to make a variant of tab switcher that use the buttom bar as the only tab switcher with the buttom bar being permanent so you access tabs from the arrow button and creat a new tab from the + button?
![Screenshot_20210804-131854](https://user-images.githubusercontent.com/73849082/128165094-4ecac3e9-dc3b-4420-8796-0f15015befd0.png)

**Comment by kiwibrowser** [comment]
May actually be easier than it seems,
I think this "only" requires overriding the function "is in the same tab group" to always return true and to switch the arrow button to new tab.

My concern is more on the longevity of the feature, as Google plans to remove the tab strip as far as I understand.

**Comment by Lartsch** [comment]
What a bummer! I really enjoy the tab group navigation, at least for actual tab groups. Hope they decide not to remove it.

**Comment by kiwibrowser** [comment]
I'm not sure, just suspect it a lot based on this:

https://source.chromium.org/chromium/chromium/src/+/main:chrome/android/features/tab_ui/java/src/org/chromium/chrome/browser/tasks/tab_management/TabUiFeatureUtilities.java;l=158

**Comment by samlux04** [comment]
I actually love the visible tab button like Vivaldi. I think it's much easier to switch tab. If only you can add it to kiwi.

**Comment by d3ward** [comment]
Kiwi v116 got a new tab switcher layout which uses the desktop like with tabs. 
Also the tabstrip got improved a lot thanks to refactoring of bottom tab .
So we finally got a new type of tab switcher, @naifqarni  I know is little bit different from initial description but very close , let us know what you think
