### ISSUE TITLE
 Kiwi currently can't Open tabs in External Applications

### ISSUE THREAD

**Issue by okikio** [kiwibrowser/src.next#260]
## **Is your feature request related to a problem? Please describe.**

Right now to open links in an external application you need to find the link and long press and then select `Open in External Application`, but this leaves out situations where I open a tab and I want to switch to the native app e.g. I want to open a Youtube video in it's app. Right now Samsung Internet is the only browser I know of that actually has this feature.

## **Describe the solution you'd like**

A possible solution is too add `Open in external application` as a share option in Kiwi's share sheet, this would allow you to easily share tabs to their respective apps.

## **Describe alternatives you've considered**

Or Kiwi could go the Samsung Internet route and add an icon in the top right (the icon would that of the external app that support the current tabs url) when there is an App that supports opening that specific tab is installed on the phone, if there are multiple apps that support the tab, Kiwi would instead show a different icon.

![Screenshot_20210805-010352_Samsung Internet Beta_LI](https://user-images.githubusercontent.com/17222836/128293764-0ab11338-e61e-4261-b530-2b7a33ace961.jpg)
**Open 1 App Externally**

![Screenshot_20210805-010915_Samsung Internet Beta_LI](https://user-images.githubusercontent.com/17222836/128294370-b95e20cc-21b5-48a7-bc13-91da7497e839.jpg)
**Open Multiple Apps Externally**

## **Additional context**

This is seems similar to, but distinctly **different** from #243

**Comment by d3ward** [comment]
#94

**Comment by okikio** [comment]
@d3ward This is a different feature requwst

**Comment by d3ward** [comment]
You can long press on url and click on open in external application , isn't that. I closed as we have many issues related to the external links . And that seems to be very related as is direclty connecte to the opening in external app ( i think doesn't matter that it's automatic or from a shortcut click )

**Comment by okikio** [comment]
No, it's different because Kiwi currently doesn't support opening tabs in an external app, e.g. opening Youtube videos in the app, Samsung Internet supports this but Kiwi doesn't

**Comment by KaKi87** [comment]
Duplicate of #96

**Comment by okikio** [comment]
#96 was from 2 years ago and had not seen any progress, so I decided to repost

**Comment by KaKi87** [comment]
Don't do that.
However, you can say *"hello, any news on this?", which would be enough.

**Comment by okikio** [comment]
Oh, sorry about that

**Comment by KaKi87** [comment]
No problem !

**Comment by metronightly** [comment]
Instead of providing this in the share menu, I think it will be better if the "Open in App" option is provided in the 3 dot menu.

**Comment by okikio** [comment]
> Instead of providing this in the share menu, I think it will be better if the "Open in App" option is provided in the 3 dot menu.

This would also work

**Comment by BartmanEH** [comment]
> Instead of providing this in the share menu, I think it will be better if the "Open in App" option is provided in the 3 dot menu.
> 
> [Like in Firefox](https://user-images.githubusercontent.com/15360245/114318233-189c4100-9b04-11eb-96a1-a8f9770a8db6.png)

Then it won't be automatic and you have to use a menu item every time? That's not a good solution. Using the Share Menu system in Android lets you, the user, customize whether to open links every time in a specific app or not and is much more flexible. There are several external app options for many types of links, e.g. map links

**Comment by okikio** [comment]
@BartmanEH Actually, I like the way Samsung Internet currently handles it, read up on the details of this issue to understand what I mean.

**Comment by BartmanEH** [comment]
Still don't like it. It's too many clicks: first you open link in new tab then you click button to open in external app. This could be ADDED as an additional feature but not "Instead of providing this in the share menu" as suggested.

**Comment by okikio** [comment]
I think you've misunderstood. What I am suggesting would add the open tab in external app button, to the top bar similar to Samsung Internet. Or if people don't like that it could be added to the share menu or the 3 Dota menu, the main point is that Kiwi gain the ability to open tabs in external apps.

**Comment by metronightly** [comment]
> > Instead of providing this in the share menu, I think it will be better if the "Open in App" option is provided in the 3 dot menu.
> > [Like in Firefox](https://user-images.githubusercontent.com/15360245/114318233-189c4100-9b04-11eb-96a1-a8f9770a8db6.png)
> 
> Then it won't be automatic and you have to use a menu item every time? That's not a good solution. Using the Share Menu system in Android lets you, the user, customize whether to open links every time in a specific app or not and is much more flexible. There are several external app options for many types of links, e.g. map links

No, you have confused it with replacing the 'Prefee Native Application' option that is already present in Kiwi. What the OP suggested is an additional feature to open tabs in external apps from the share menu but I thought that option should be there in 3 Dot Menu.

We are not saying to remove or replace the current feature of automatically opening links on apps. The Open in App option on the 3 Dot Menu will be useful for those who don't want every link to open up the app. Both the feature can co exist like in Firefox.

**Comment by metronightly** [comment]
> Still don't like it. It's too many clicks: first you open link in new tab then you click button to open in external app. This could be ADDED as an additional feature but not "Instead of providing this in the share menu" as suggested.

Putting this additional feature as an option on Share menu means an extra click: 3 Dot Menu-Share-Open in App

Whereas my suggestion would have it like: 3 dot menu-Open in App.

**Comment by okikio** [comment]
@metronightly Oh, as in not in the 3 dot menu but just right beside it, similar to what Samsung internet does
