### ISSUE TITLE
user agent changer extension not working

### ISSUE THREAD

**Issue by hhjeremy** [kiwibrowser/src.next#27]
example extension that is not working:
https://chrome.google.com/webstore/detail/user-agent-switcher/dbclpoekepcmadpkeaelmhiheolhjflj

**Comment by kyoyacchi** [comment]
It may not work, but i use something else https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg this working well, give a try.

**Comment by d3ward** [comment]
There is o info of what/why is not working .
As there exist working alternatives , this issue will be closed
