### ISSUE TITLE
Can't open popup to login Facebook from third party website. 

### ISSUE THREAD

**Issue by samlux04** [kiwibrowser/src.next#274]
I can't login to Facebook from third party website that use Facebook comment plugin. The website is https://m.manganelo.com/genre-4
Also doesn't work with disqus comment.
https://www.foxaholic.com/novel/i-became-the-strongest-with-the-failure-frame%e3%80%90abnormal-state-skill%e3%80%91as-i-devastated-everything/

I already enable popup in site setting and disable all extensions. In Chrome even with popup blocked in site setting, it still could open a new window to login. It's opened in tab group.

What do? 

![Screenshot_2021-08-06-07-14-37-360_com kiwibrowser browser](https://user-images.githubusercontent.com/85811479/128433294-70a8a3e9-a49f-47db-8436-e3911b67adb2.png)

**Comment by kiwibrowser** [comment]
Fixed @ https://github.com/kiwibrowser/src.next/commit/782591a0d06547c52448795b2156b0140e5ed238

It will come with the upcoming (next) build

It's not ideal fix at all, as it's a relatively large whitelist but it should work for now (and based on the complains later, we can figure out if an heuristic is needed)

**Comment by samlux04** [comment]
Wasn't it kinda bad to have a hard-coded such common words? Some malicious ads popup can use these words as domain name.

**Comment by kiwibrowser** [comment]
It is wide but I doubt an advertisement named facebooknetwork.de ou googleofficial.nz doing popup ads would survive long on the internet because of the Certificate Transparency alerts that the companies have.
Seems better than a false positively blocked window

**Comment by samlux04** [comment]
Even when the chance is low there's still possibility. Maybe change the keyword to something more definite like facebook\.\w+$
