### ISSUE TITLE
just wanted to say... thank you!!! 

### ISSUE THREAD

**Issue by hltdev8642** [kiwibrowser/src.next#275]
I just had to tell the developers how incredibly grateful I am for the fact that you incorporated a fix for the completely RIDICULOUS omnibox clipboard url "feature" that Google at some point decided to force on everyone... 

I have been staying on old chromium versions for what feels like forever now, all because I simply cannot get used to having to press that silly pencil button every time I want to edit a url. 

Referring to this:

![Screenshot_20210805-210927](https://user-images.githubusercontent.com/39349712/128440860-721d8b89-f1a5-450f-8da8-89772b5e7ae2.png)

No issue, will mark it resolved right away if possible. Too bad there isn't a resolution tab on githib Lol 😂!

But really thank you, I can finally use a version of Chrome that's not a million years old...

**Comment by kiwibrowser** [comment]
Oh it's really kind from you ! 🥇  This omnibox, even with the new setting, still gave questions recently on how the setting should be done.
Like, should the text be selected in blue, or should the text non-selected and just the caret (character editor: | at the end) placed at the end ?

(the second solution seemed the best).

Glad you liked it!

**Comment by gnadelwartz** [comment]
Cool! did not notice, exactly what I was looking for. BTW @kiwibrowser how can we contribute translations for kiwi only features like this where no chrome translation exists?

**Comment by kiwibrowser** [comment]
https://crowdin.com/project/kiwibrowser
(the link is in the README)

**Comment by gnadelwartz** [comment]
> https://crowdin.com/project/kiwibrowser
> (the link is in the README)

thank you.

are all strings there? I didn't find e.g. 'do not delete adress bar content' but may be I overlooked it ...

**Comment by kiwibrowser** [comment]
I just updated the file manually.

In the future, ideally GitHub->CrowdIn should be automated ( https://support.crowdin.com/api/add-file/ ) but this is going to take time. For now only CrowdIn->GitHub is automated.

**Comment by gnadelwartz** [comment]
> I just updated the file manually.
> 
> In the future, ideally GitHub->CrowdIn should be automated ( https://support.crowdin.com/api/add-file/ ) but this is going to take time. For now only CrowdIn->GitHub is automated.

german translation done ...

**Comment by kiwibrowser** [comment]
Thank you it's now there in chrome/android/java/res/values-de/strings.xml

https://github.com/kiwibrowser/src.next/blob/kiwi/chrome/android/java/res/values-de/strings.xml

**Comment by kryptobolt200528** [comment]
> Oh it's really kind from you ! 🥇 This omnibox, even with the new setting, still gave questions recently on how the setting should be done.
> Like, should the text be selected in blue, or should the text non-selected and just the caret (character editor: | at the end) placed at the end ?
> 
> (the second solution seemed the best).
> 
> Glad you liked it!

Really thank you for that that was annoying as hell....
