### ISSUE TITLE
ClearURLs extension not working in Kiwi Browser

### ISSUE THREAD

**Issue by cbwee** [kiwibrowser/src.next#276]
**Describe the bug**
When the ClearURLs extension is installed in Kiwi Browser, the browser gives an error message `ERR_BLOCKED_BY_CLIENT` in Google Images search results.

**To Reproduce**
1. Install [ClearURLs for Chrome](https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk) in Kiwi Browser.
2. Search anything on Google in the browser.
3. Go to `Images` in search results.
4. Try to click on any of the links of the images.
5. An error message `ERR_BLOCKED_BY_CLIENT` appears.

**Expected behavior**
The link should be opened without giving an error message.

**Smartphone:**
 - Device: Xiaomi Redmi 4X
 - Android Version : Android 7.1.2
 - Kiwi Browser Version 93.0.4577.22

**Additional context**
I have tried the same steps in Brave Browser in Windows 10, with a mobile user agent, and this error message does not appear.

I have also tried the same steps in Yandex Browser Alpha in Android, and this error message does not appear, either.

So I can confirm that this issue only exists in Kiwi Browser.

**Comment by kiwibrowser** [comment]
For information, ERR_BLOCKED_BY_CLIENT means that the browser (Hide annoying ads) or a browser extension has blocked the resource.
Do you have any active extension ?

**Comment by cbwee** [comment]
I just tried disabling all other extensions I installed in the browser, and `Hide annoying ads` is disabled, when ClearURLs is the only extension that is enabled, this error message still appears.

**Comment by d3ward** [comment]
Is this bug still there ? I have clearURLs too and i can view images without any problem

**Comment by cbwee** [comment]
> Is this bug still there ?

Yes, please try the steps to reproduce again, and make sure you click on the links that open the websites.

Because when I tried it, I could also view images in the search results, but the error only appeared after I tried to open any of the links in the images search results (of the website where the image is in).

**Comment by cbwee** [comment]
I installed the extension again in Kiwi Browser 98 and now it works without the error message, closing this issue.
