### ISSUE TITLE
Magnet-URLs: Protocol handler does not ask for application

### ISSUE THREAD

**Issue by dagaz** [kiwibrowser/src.next#277]
**Describe the bug**

Magnet-URLs are opened by Kiwi not by the native app. The protocol handler does not ask for the application to handle the protocoll.

**To Reproduce**

Install a BitTorrent client software like "[qBittorrent Controller](https://play.google.com/store/apps/details?id=com.lgallardo.qbittorrentclient)".

In chrome://setiings/handlers set the option to "allow sites..." 

Open a site with magnet links (Example: https://fosstorrents.com/distributions/arch-linux/ ) in Kiwi and click on the magnet link.
(Yes, *there* is also a torrent file download but many sites with magnet links do not offer a liked torrent file.)

The "side loading"-stautsbar right below the tab list flikers but the site is not asking how to handle the magnet-URL.

**Expected behavior**

There should open a window asking which application should handle the URL and where you can select qBittorrent Controller.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - Android Version : LineageOS 18.1 Builddate 2021-07-28 (Android 11)
 - Kiwi Browser Version 90.0.4577.22 (latest Google Play Version)

**Additional context**
The Bug also happens on other sites with magnet URLs.

**Comment by Lartsch** [comment]
Related to #94

**Comment by dagaz** [comment]
Issue seems solved.

**Comment by kiwibrowser** [comment]
Thank you for confirming
