### ISSUE TITLE
cant set up sync on Violentmonkey

### ISSUE THREAD

**Issue by GeorgeRudd** [kiwibrowser/src.next#278]
kiwi 93 
Violentmonkey extension

after the last step of the authorization(google drive/onedrive). it returns an error page

used to work well on old kiwi...

![Screenshot_20210806-155106_Kiwi Browser](https://user-images.githubusercontent.com/40507943/128483979-7fe1a74f-54ed-463a-9815-9e93f40c6924.jpg)

![Screenshot_20210806-155131_Kiwi Browser](https://user-images.githubusercontent.com/40507943/128484009-4dfc5d12-9673-4131-9ed0-f4e7bf65a27e.jpg)

**Comment by KaKi87** [comment]
You can actually visualize this error page everywhere.
It seems that although those oauth2 redirect URIs does not really exist, Violentmonkey has a way to listen to those redirections and get the oauth token back.
When testing on desktop, the extension instantly closes the tab after this fake redirection so end users would not see the 404.
For some reason, this no longer works on Kiwi (if it ever worked at all) and the rest of the redirection stuff doesn't either.

Hey @tophf, could you help us understand your process so we can debug this faster ? Thanks.

**Comment by tophf** [comment]
https://github.com/violentmonkey/violentmonkey/blob/63f7364f9842f8363a6bed560c4b714aa24b3070/src/background/sync/index.js#L23-L25

It uses browser.tabs.onUpdated event to listen to the change of URL in all tabs and if a matching one is found, the tab is immediately closed. Maybe Kiwi doesn't like that it happens too soon e.g. the tab is still undergoing some internal initialization?

**Comment by kiwibrowser** [comment]
I'll find a solution in the coming days @tophf - thank you for the time spent on it so far. I suspect it is the same issue floccus has (which is also around Google identity management within the browser) but once I try in live I will be able to understand better

**Comment by d3ward** [comment]
With latest Kiwi v116 the sync with Google issues on extensions has been fixed , including Violentmonkey
