### ISSUE TITLE
Ublock Origin (normal or kiwi specific version) fail to block YouTube ads

### ISSUE THREAD

**Issue by Doc-4** [kiwibrowser/src.next#281]
**Describe the bug**
These extensions seem to work correctly as a whole other than not blocking YouTube ads like they would on either a Firefox based mobile or either FF or chromium based desktop browser.

**To Reproduce**
Install a version of UB:O, navigate to YouTube

**Expected behavior**
Ads blocked as expected

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: e.g. OnePlus 7T Pro
 - Android Version : A10
 - Kiwi Browser Version 93.0.4577.18

**Comment by Delphox** [comment]
Works fine for me (although I'm more of a Youtube Vanced user). Make sure to disable the built-in adblocker if you have uBlock origin installed, as they may conflict and compromise each other.

Additionally, what country are you from? I do remember a Dutch friend having problem with uBo not blocking ads for a while even on desktop, so I think ads from certain regions may slip through the cracks sometimes.

**Comment by Doc-4** [comment]
I use vanced and newpipe outside of the browser, but I have noticed regardless that sometimes ads show up anyway, often in incognito tabs. I do in fact have the extension set to work in said tabs, so it should be working afaik. I live in USA.

**Comment by Delphox** [comment]
> I use vanced and newpipe outside of the browser, but I have noticed regardless that sometimes ads show up anyway, often in incognito tabs. I do in fact have the extension set to work in said tabs, so it should be working afaik. I live in USA.

Oh, the Incognito part explains it. Extensions have been bugged on Incognito for a while, they don't start properly. While it's not fixed, an workaround is simply opening Devtools once in the incognito session, that unlocks the extensions you currently have enabled to work in incognito. A better fix is on the to-do list.

**Comment by Doc-4** [comment]
I see, thanks for the information.
