### ISSUE TITLE
Extension can't be used in incognito mode

### ISSUE THREAD

**Issue by tfkhdyt** [kiwibrowser/src.next#289]
**Describe the bug**
the extension is not usable in incognito mode even though the "allow in incognito mode" option is enabled in the extension menu
![Screenshot_2021-08-07-16-48-47-88_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/47195537/128596517-01a8899e-e3ec-4f5e-bdb7-3e232ea00839.jpg)
![Screenshot_2021-08-07-16-49-33-39_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/47195537/128596531-e7020bce-9cfc-4693-b4be-27c487031049.jpg)

**To Reproduce**
1. Enter incognito mode
2. Click on the extension icon
![Screenshot_2021-08-07-16-58-20-55](https://user-images.githubusercontent.com/47195537/128596542-fbe7337b-ece1-42f6-a403-c9635c7fd648.jpg)

**Expected behavior**
Extension page should appear normally like this, and the extension features should work normally as well
![Screenshot_2021-08-07-16-59-48-60_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/47195537/128596552-0cc9ca60-ba0c-4960-b65f-de34458bd6b5.jpg)

**Smartphone (please complete the following information):**
 - Device: Realme 3 Pro
 - Android Version : Android 10
 - Kiwi Browser Version : 93.0.4577.22

**Comment by Delphox** [comment]
As a temporary workaround, when you start an Incognito Session, open Devtools once, it will unlock the extensions you allowed on Incognito for that session.

@kiwibrowser will investigate the behavior soon.

**Comment by tfkhdyt** [comment]
@Delphox thanks, it works now
I hope the dev fix this bug soon

**Comment by kiwibrowser** [comment]
As per https://stackoverflow.com/questions/23527454/chrome-extension-incognito-mode-check-if-activated-or-start-with-a-button

The issue is that in incognito profile, the split extensions don't boot properly.
@Delphox found a cool workaround to force extensions to load.

The solution is to load split extensions when the incognito profile is started.
(though I'm not sure how yet)

**Comment by HelixAngler** [comment]
Pasting the URL then enter also unlock the extension. There must be something going on between when typing keyword to search and when entering the URL directly.
