### ISSUE TITLE
Two down swipes to refresh with Botton Toolbar Autohide setting On

### ISSUE THREAD

**Issue by malaguer** [kiwibrowser/src.next#290]
**Describe the bug**
Whenever Botton Toolbar is hided, if I click on a 'Scroll to top' shortcut, I have to swipe down once to make the toolbar appears, and another time to be able to refresh the page.

**To Reproduce**
- Bottom Toolbar Autohided settting on.
- Scroll to toolbar extension installed (but it also happens in any site with a 'Scrool to top' element')
- I scroll down the page, so the Toolbar disappears.
- I click on Scroll to top (toolbar is hided)
- I swipe down to refresh the page, but it doesn't refresh. Instead, it first make toolbar reappears. So, I have to swipe a second time to refresh the page.

- Site example (with Go to the top shortcut): https://d3ward.github.io/

**Expected behavior**
Whenever top offset value is '0' the swipe down gesture should always refresh the page.

**Smartphone (please complete the following information):**
 - Device: Honor 8x
 - Android Version : A10
 - Kiwi Browser Version: v93.0.4577.22

**Comment by d3ward** [comment]
This issue has been fixed with the recent Kiwi v116 updates.
