### ISSUE TITLE
Doesn't open reddit links in external app

### ISSUE THREAD

**Issue by SylwesterDu** [kiwibrowser/src.next#297]
**Describe the bug**
Tried with installed official reddit app and boost for reddit 

**To Reproduce**
Just google random subreddit and tap on link

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Redmi note 10s]
 - Android Version : [A11 MIUI 12.5.8]
 - Kiwi Browser Version [93.0.4577.22 ]

**Comment by gnadelwartz** [comment]
duplicate #260

**Comment by SylwesterDu** [comment]
> duplicate #260 

In my case every link opens in external app correctly. The only exception is reddit, so I think it might be another issue

**Comment by DUOLabs333** [comment]
Huh, interestingly enough, turning on "Open links in external applications" fixed the problem of reddit always reverting to AMP. Will have to look into this.

**Comment by DUOLabs333** [comment]
Hey @kiwibrowser, how does tracing work, so I can see what's going on?

**Comment by KaKi87** [comment]
Duplicate of #225.
