### ISSUE TITLE
unable to trigger "swipe up to open tab switcher"

### ISSUE THREAD

**Issue by TsXor** [kiwibrowser/src.next#298]
**Describe the bug**
When I swipe up from the bottom, I can't open tab switcher most of the time. 
**To Reproduce**
1.Open Kiwi browser.
2.Enable "swipe up to open tab switcher"
3.Swipe up.

**Expected behavior**
When I swipe up from the bottom, I can open tab switcher.

**Screenshots**
![nbuzv-h3oil](https://user-images.githubusercontent.com/74352334/128674742-2c999430-f14e-41b0-b7ee-619c9ba8a5f4.gif)

**Smartphone (please complete the following information):**
 - Device: Honor V9
 - Android Version : Android 9
 - Kiwi Browser Version : 93.0.4577.25

**Additional context**
However, there's a very small possibility to open tab switcher. So I guess the area to trigger this action is not appropriate.

**Comment by gnadelwartz** [comment]
similar to #282 ??

**Comment by d3ward** [comment]
Closing it as there is already an issue related to "swipe to open tab switcher"
