### ISSUE TITLE
Apk release exploding

### ISSUE THREAD

**Issue by jututt** [kiwibrowser/src.next#3]
Can you briefly explain what causes release apk size to go from 50 mb of `src` to 180 mb of `src.next`?
Thanks

**Comment by Lartsch** [comment]
Kiwi has been rebased on a much newer version of chromium, which is the main reason for the apk size increase, I think.

**Comment by d3ward** [comment]
If you download the app from PlayStore you will get the version that is less than 50mb . The version from GitHub it's like raw apk with no compression or split of resources
