### ISSUE TITLE
Can't do `adb backup` on Kiwi Browser

### ISSUE THREAD

**Issue by DUOLabs333** [kiwibrowser/src.next#306]
Since I'm not root, I'm trying to use `adb backup` to backup app data. But when I do, all I'm left with is a 37 byte file.

**Comment by DUOLabs333** [comment]
This seems to be because `allowBackup` is set to `false`. Was this manually added in, or was it from the rebate?

**Comment by kiwibrowser** [comment]
It's following what is Chromium, this one is a bit tricky, I wonder if it could security issues, this is why allowBackup is not enabled, and it requires serious investigation before turning this flag on (as it could eventually otherwise allow all passwords to be "backuped" by third-party app)

**Comment by DUOLabs333** [comment]
However, to backup, you need to expressly give the app permission. There's no way to do it in the background. Or maybe make it a toggle?

**Comment by DUOLabs333** [comment]
Wait, really? Oh, that's going to be a problem (I was doing backups using `adb` for a while). Ok, yeah, you could try making a zip folder of all the pertinent folders (it should be found in the other backup thread).

**Comment by DUOLabs333** [comment]
How would you add a button in the settings to do an action?

**Comment by kiwibrowser** [comment]
```    <Preference
        android:key="captions"
        android:title="@string/accessibility_captions_title"/>
```

This is a button in the "Setting" screen.

To add the translation string and the preference in the layout (xml): https://github.com/kiwibrowser/src.next#adding-a-new-setting

To bind an action on-click:
https://github.com/kiwibrowser/src.next/blob/kiwi/chrome/android/java/src/org/chromium/chrome/browser/accessibility/settings/AccessibilitySettings.java#L111

Btw @DUOLabs333 you have build access already (in your repo, you just have to do, `Any branch: Build apk`)

You can try with Accessibility Settings, as it's easy to experiment there, but it is possible to do the same with main_settings too

**Comment by kiwibrowser** [comment]
Even better than in Accessibility Settings:

To add in the Main Settings (home of the "Settings" screen), actually it's there:
https://github.com/kiwibrowser/src.next/blob/kiwi/chrome/android/java/src/org/chromium/chrome/browser/settings/MainSettings.java#L161

and
https://github.com/kiwibrowser/src.next/blob/kiwi/chrome/android/java/res/xml/main_preferences.xml

**Comment by DUOLabs333** [comment]
I can't figure out how to make a page appear when clicked on the "Export" button. Best I found was to open a system setting page.

**Comment by kiwibrowser** [comment]
getTabModel/getTabCreator
https://github.com/kiwibrowser/src.next/blob/258c95b5c85c8b806f33d0aaac5b241a2b9e975f/chrome/android/java/src/org/chromium/chrome/browser/ChromeTabbedActivity.java#L767

(if you mean an HTML page)

**Comment by DUOLabs333** [comment]
@kiwibrowser I saw your most recent commit, but it's still not very clear what to do. Where are the other setting screens located, so I could use that as a base?

**Comment by kiwibrowser** [comment]
Oh, I added it today actually (because I realized I forgot a file):
https://github.com/kiwibrowser/src.next/blob/9669e9f9b7d380f1bde9098fc8e1efb8749a197b/chrome/android/java/src/org/chromium/chrome/browser/settings/RadioButtonGroupTabSwitcherPreference.java + https://github.com/kiwibrowser/src.next/blob/4696cda1eb1df3805e6c7484604f16c301daac0e/chrome/android/java/res/xml/tabswitcher_preferences.xml + https://github.com/kiwibrowser/src.next/blob/kiwi/chrome/android/java/res/xml/main_preferences.xml#L107 + https://github.com/kiwibrowser/src.next/blob/3318188de825fbc79d1d17f7273bf168f649fb8e/chrome/android/java/src/org/chromium/chrome/browser/settings/TabSwitcherSettings.java

android:fragment="org.chromium.chrome.browser.settings.TabSwitcherSettings" 
=> to open the fragment called org.chromium.chrome.browser.settings.TabSwitcherSettings

So I think this is what you are looking for ("opening a fragment", it's a PreferenceFragmentCompat)

**Comment by DUOLabs333** [comment]
I'm trying to merge it to my fork, but there are a bunch of merge conflicts, even though I only changed the main settings xml, and I have no idea why.

**Comment by DUOLabs333** [comment]
And even though you just added the files, "Tab Switcher" still works on my fork.

**Comment by kiwibrowser** [comment]
It's because with @d3ward  we fixed a lot and a lot and a lot of things in the last days and had to do a couple of force pushes.

To solve this:

```
git switch kiwi
git remote add upstream https://github.com/kiwibrowser/src.next.git
git fetch upstream
git pull upstream --rebase kiwi
(or if it doesn't work: git rebase -i upstream/kiwi)
git push origin --force
```

**Comment by kiwibrowser** [comment]
If you already have it in the workflow, you can use "Actions"
`\_ Forked kiwi: Rebase on top of kiwibrowser:kiwi branch `
and that will do it for you :)

**Comment by DUOLabs333** [comment]
Wow, you really have though of everything, huh?

**Comment by DUOLabs333** [comment]
Oh, I have to add it manually.

**Comment by kiwibrowser** [comment]
It will come once you are rebased / in sync with upstream.
It's a recent addition.

Sorry for all this mess, but I was testing (and still testing) the automatic rebase and this broke a bit the commit history.
But if you run the commands it should be fine.

You are among the pioneers :)

**Comment by DUOLabs333** [comment]
I tried to run it, failed at `error: could not apply 3078529... Create rebase_kiwi_on_top_of_kiwi.yml` (I had to add the file manually).

**Comment by kiwibrowser** [comment]
Ah, you created rebase_kiwi_on_top_of_kiwi.yml - so now it's conflict with upstream
You can just give me write access to the repo and I can solve it for you just by running the commands.

**Comment by DUOLabs333** [comment]
Invited you.

**Comment by kiwibrowser** [comment]
Voila, all fixed :)

**Comment by DUOLabs333** [comment]
Perfect

**Comment by kiwibrowser** [comment]
This sync system is a bit tricky and going to improve next week I think.
In summary:

[kiwibrowser:kiwi]
is sitting on top of
[kiwibrowser:chromium]

however we often change the commit where [kiwibrowser:kiwi] starts from (because we change [kiwibrowser:chromium] at every new version).
So as a result, all the commits in [kiwibrowser:kiwi] often get new IDs, and this easily confuses Git. As Git is not really a rebase-first platform, but rather a merge tool.

However, if we merge kiwi and chromium everything would be easier for forks, but to upgrade the chromium version would be very difficult, because kiwi and chromium code would be blended together.

Though maybe this will be a solution, who knows.

This is just to explain, why your fork couldn't find a why to attach to the main repository kiwibrowser:kiwi, and why this special action exists (to reattach/rebase on top of kiwibrowser:kiwi)

**Comment by kiwibrowser** [comment]
I understood there is a problem:
1) The build is broken (I fixed, I broke it yesterday accidentally)
2) You need to have a way to add a java file in the build

**Comment by kiwibrowser** [comment]
About 2) I think I can fix it in a few hours

**Comment by DUOLabs333** [comment]
That may be why my changes aren't compiling -- or that I messed something up :) Is it fixed in the main repository?

**Comment by DUOLabs333** [comment]
I'm trying to make a settings page for ExportImport.java (instead of having it split into two files like the Tab Switcher). I'm planning on getting the basics before customizing it, but it wouldn't compile. It may be because of an error (I'm more comfortable with Python), or something else:
[ExportImport.txt](https://github.com/kiwibrowser/src.next/files/6987381/ExportImport.txt)

**Comment by kiwibrowser** [comment]
As surprising as it may seems, you are the first user to try to add a .java file :)
so I need to add the file where you can select what are the .java files that are packed and compiled in the APK.

Your changes weren't compiling because there was a bug in the deployment script (that was unrelated)

**Comment by kiwibrowser** [comment]
In a couple of hours I'll point you to the right file where you need to add your resources + java file :)
and then you'll be able to compile and it'll work

**Comment by DUOLabs333** [comment]
```
Error: Found files not listed in the sources list of the BUILD.gn target:
../../components/browser_ui/styles/android/java/res/drawable-hdpi/ic_devtools.png
../../components/browser_ui/styles/android/java/res/drawable-mdpi/ic_devtools.png
../../components/browser_ui/styles/android/java/res/drawable-xhdpi/ic_devtools.png
../../components/browser_ui/styles/android/java/res/drawable-xxhdpi/ic_devtools.png
../../components/browser_ui/styles/android/java/res/drawable-xxxhdpi/ic_devtools.png
```

**Comment by kiwibrowser** [comment]
I'm working on fixing this + adding the possibility to add java files and custom ressources

**Comment by kiwibrowser** [comment]
I fixed the build script

chrome/android/chrome_java_resources.gni -> to add a png file
chrome/android/chrome_java_sources.gni -> to add a java file

If you can try @DUOLabs333  :)

**Comment by kiwibrowser** [comment]
and you can just run build apk and it should be working fine now :)
before, you need to rebase on top of `\_ Forked kiwi: Rebase on top of kiwibrowser:kiwi branch`

**Comment by DUOLabs333** [comment]
Yeah, I tried about an hour ago and it failed (could you please stop rewriting history :)). I could give you access if needed.

**Comment by kiwibrowser** [comment]
Yes, let's do that :)

**Comment by DUOLabs333** [comment]
Added.

**Comment by kiwibrowser** [comment]
@DUOLabs333 finally fixed!

Now it's good and nice, and as I promised (just with a couple of hours late)

I fixed the build, plus I unified everything in 2 files that are easy to manipulate:
https://github.com/kiwibrowser/src.next/tree/kiwi/chrome/android

If you need to add a resource: chrome/android/chrome_java_resources.gni
If you need to add a new java class: chrome/android/chrome_java_sources.gni

If you want the latest changes of kiwibrowser:src.next, you can run the action `\_ Forked kiwi: Rebase on top of kiwibrowser:kiwi branch` and it will do everything for you.

Thank you very much (again!) for being one of the early user of this system and my apologies on blocking your workflow, your help is very appreciated.

**Comment by DUOLabs333** [comment]
Why does `Build APK` fail with
```
../../chrome/android/java/src/org/chromium/chrome/browser/settings/RadioButtonGroupExportImport.java:68: error: invalid method declaration; return type required
    public RadioButtonGroupExportImport(Context context, AttributeSet attrs) {
           ^
```
when `RadioButtonGroupTabSwitcherPreference.java` is allowed through, even though most of the code is copied from it?

**Comment by kiwibrowser** [comment]
This is because your class is named
`public final class RadioButtonExportImport`
and it should be
`public final class RadioButtonGroupExportImport`

(always the same as the filename and always the same as the constructor)

when you write `public RadioButtonGroupExportImport` the compiler thought you wanted to create a new method inside the class (it didn't know it was a constructor), so it asked you to add a return type to have like `public some_type method_name`.

However, this is just a confusing error message because the real issue is not with the constructor, but rather that the class name was not correct.

**Comment by DUOLabs333** [comment]
Ah, must have overlooked it -- thanks.

**Comment by kiwibrowser** [comment]
Well it took me time to realize too :D

As a side-note: It is a quite complicated task what you are trying to achieve but I think it's doable 100% from Android native if you are looking to take a snapshot of the profile.

You may find more satisfaction (in terms of people feeling grateful) by taking small issues as they are +/- instant gratification (and get familiar with the codebase)

During the next days I'm going to make importing new files from Chromium easier, and work on an interactive rebase solution (to be able to resolve conflicts either from Chromium, or with other Kiwi repos).

For now, if you want to fetch the latest kiwibrowser:src.next changes in your repo you can use "\_ Fork: Rebase on top of kiwibrowser:src.next"

**Comment by kiwibrowser** [comment]
Profile = user profile, settings, passwords and extensions.

About protecting the export functionality, you can see in the Passwords settings screen (3 dots menu), when you press Export password, there is a very cool PIN protected export example (you can find the code and cs.chromium.org )

**Comment by DUOLabs333** [comment]
Ah, I understand. But for some reason, no matter what I do, I can't get my page to show up. Is there an option for error logs?

**Comment by kiwibrowser** [comment]
For now via:
adb logcat

(But this requires a computer connected to the phone or a rooted phone but maybe there is a better way?)

**Comment by DUOLabs333** [comment]
That could work, but a lot of it will have the noise of Android processes.

**Comment by Delphox** [comment]
> (But this requires a computer connected to the phone or a rooted phone but maybe there is a better way?)

If you're on android 11 you can use [LADB](https://github.com/tytydraco/ladb) (it's 3 dollars on playstore but you can compile the source if you want) and maybe Shizuku (you launch Termux with adb permissions or something, not really knowledgeable about it). They take advantage of the Wirelesss ADB feature and create a local adb server in the phone itself that connects to it.

**Comment by kiwibrowser** [comment]
I think there may be a possibility to create kiwi://adb or kiwi://logs
I'm looking into it

**Comment by Delphox** [comment]
> If you're on android 11 you can use [LADB](https://github.com/tytydraco/ladb) (it's 3 dollars on playstore but you can compile the source if you want) and maybe Shizuku (you launch Termux with adb permissions or something, not really knowledgeable about it). They take advantage of the Wirelesss ADB feature and create a local adb server in the phone itself that connects to it.

Update on this, I was looking through the LADB forks and someone already made an environment to build it through github actions [here](https://github.com/berlin4apk/LADB), so you can just fork it and do any commit and it'll auto build it for you. 😀

**Comment by kiwibrowser** [comment]
Very cool discovery @Delphox !
