### ISSUE TITLE
Swipe Up to Open Tab Switcher Not Working

### ISSUE THREAD

**Issue by gitdebpro** [kiwibrowser/src.next#31]
Swipe Up to Open Tab Switcher Not Working when address bar is at bottom but it's working fine when address bar is at top.

**Comment by K1DV5** [comment]
@d3ward I came here to post this issue here after kiwibrowser/src#206 was closed and found this. But in my case it's the same as the old version, it doesn't work both ways. I'm now on Android 10 go (old issue was on Android 8.1 go).
