### ISSUE TITLE
Kiwi Browser doesn't using Disqus's new comments UI (?)

### ISSUE THREAD

**Issue by kyoyacchi** [kiwibrowser/src.next#318]
In Brave Browser:  (Disqus comments section)
![CollageMaker_20210813_222712227](https://user-images.githubusercontent.com/63583961/129409652-e3b48bdf-7ec6-48b1-8943-28e2b5444852.jpg)
In Kiwi Browser: 
![CollageMaker_20210813_222933169](https://user-images.githubusercontent.com/63583961/129409701-f8739a2a-4f47-4ca3-bc29-a5ecb07f6193.jpg)

I don't know if it's related with browser or something.
I scratched names and comments for some reason.

**Comment by kiwibrowser** [comment]
Wow, it's interesting!
Thank you for sharing, yes it's a big mystery for now... I never saw the new UI, maybe they are progressively rolling-out a new version and you got it in cache

**Comment by samlux04** [comment]
What's the difference? Reply button? 
I get consistent ui across various browser. Brave, kiwi, chrome, old firefox(fennec).

**Comment by kyoyacchi** [comment]
@samlux04 , In Brave Browser it lets to see who's upvoted or who's downvoted comments,and there's an "share" button, i'll send uncensored version of pics tomorrow, if i can.
