### ISSUE TITLE
Tripadvisor: user reviews not shown

### ISSUE THREAD

**Issue by alleluia20** [kiwibrowser/src.next#328]
This is a strange issue... If you browse Tripadvisor on Kiwi browser, and select a hotel, the main information of that hotel is shown, but the user reviews are missing (the average rating is shown, but no reviews are displayed).

I tried Chrome on the same device, and Chrome does show user reviews.

Regards.

**Comment by gnadelwartz** [comment]
@alleluia20  sorry to say: 

All Bugs you reported works on my Device
do you have the latest version from Play Store installed or a dev version?

#328 -> user review is shown
#326 -> suggestion while typing are shown
#325 -> klick on phone number opens skype (no explicit call button)

can you provide more context please? e.g.:
 
Screenshots:
Device:
OS:
Kiwi Version:

popup blocker enabled , Addblock enabled, plugins  ...

**Comment by didounet13** [comment]
You have to uncheck the ads

**Comment by kiwibrowser** [comment]
Issue probably in layout_object.cc (third_party/blink) that is hiding too many elements

**Comment by alleluia20** [comment]
Hello,

This bug (not the other two) was fixed by disabling "hide ads" in the main
menu. But this makes me think about two additional bugs:

a) I already had the built-in adblocker disabled on settings. Why is there
an additional "hide ads" option in the menu? How can both options be
"desynchronised" (one disabled and the other enabled)?
b) Why is Kiwi mistakenly considering the Tripadvisor reviews as ads?

Regarding #326 <https://github.com/kiwibrowser/src.next/issues/326>, I
still get no suggestions while typing.

Regarding #325 <https://github.com/kiwibrowser/src.next/issues/325>, are
you using Google for searching? If Google can find the business, it
typically shows the buttons: call, get there, share, save. Tapping on
"call" does nothing.

I have the latest version of Play Store, and not a developer version as far
as I know (at least, I did not choose that).

I have the latest update of Kiwi (version 93.0.4577.39) and the OS is MIUI
12.5.3 (but, again, the bugs do not happen with other browsers on the same
device). They persist with the extensions disabled.

Regards.

**Comment by gnadelwartz** [comment]
> b) Why is Kiwi mistakenly considering the Tripadvisor reviews as ads?

As ads are usually not marked as ads kiwi must use  (simple) ad detection algorizthm which can not compete with the masses of ads (or not ads) out there i  the wild. This is the job of a "real" addblocker with big country specific lists developed by volunteers and offer many configuration options to adjust to your individual profile.

Therefore I reecommend to use ublock origin or similar #332

**Comment by DUOLabs333** [comment]
Maybe we should just remove the in-built adblocker? It seems to cause more problems than it solves, and a big draw of Kiwi is that you can run extensions, so why not use it to our **ad**vantage?

**Comment by gnadelwartz** [comment]
@DUOLabs333 i second this or at least make clear it's best effort for selected websites and point ro extensions for more features.

**Comment by d3ward** [comment]
With recent v116 , built-in adblocker has been improved a lot . This issue is fixed
