### ISSUE TITLE
Text scaling issue

### ISSUE THREAD

**Issue by gokulraam** [kiwibrowser/src.next#331]
**Describe the bug**
Increase text scaling from the accessibility. Not all text on the webpage are scaled evenly.

**To Reproduce**
1. Update text scaling.
2. See any webpage for example github.

**Expected behavior**
All texts in the webpage scaled evenly.

**Screenshots**
![Screenshot_20210814-144445](https://user-images.githubusercontent.com/40225391/129441187-b6308334-a678-48c7-a1d2-b11beb958ba5.png)
![Screenshot_20210814-144452](https://user-images.githubusercontent.com/40225391/129441189-defc2e4e-075b-4c72-a7ae-eceec538fec9.png)

**Smartphone (please complete the following information):**
 - Device: Moto G40
 - Android Version : 11
 - Kiwi Browser Version - 93.0.4577.22, downloaded from play store.

**Additional context**
All chromium browsers like brave, Vivaldi have this problem. Web view browsers do better on this regard.

**Comment by kiwibrowser** [comment]
The test scaling is actually different on Kiwi. If you check Google or Wikipedia. You can see that more text is scaled-up than in other browsers.

The reason for not scaling up everything is to keep the page usable.

Otherwise it's more the Text rewrap / Reflow functionality in the Settings that is more meant to be used

**Comment by gnadelwartz** [comment]
@gokulraam you can try https://chrome.google.com/webstore/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd

**Comment by gokulraam** [comment]
Text scaling works fine for simple text/paragraph based. Not scalable enough for not so simple layouts/interfaces.

@gnadelwartz Thanks the extension seems to fulfill the need by scaling all text.

**Comment by gnadelwartz** [comment]
you can set the default and in Addition for each domain if deafult doesn't fit

**Comment by gokulraam** [comment]
It was accessible from options in extensions page and it worked.

Closing issue as the desired behavior achieved by using the extension.
