### ISSUE TITLE
[Idea] List of recommended extensions

### ISSUE THREAD

**Issue by gnadelwartz** [kiwibrowser/src.next#332]
Kiwi has out of the box nice features like blocking ads, text zoom, password store etc, some  "bug  reports" here ask for changed behaivoir of built in functionality. Some are real bugs, others can be solved by using existing extensions.

Therefore I want  to collect a small list of "recomended extensions" as replacement for builtin functionality if a user want more features or  flexibility.

My favorite examples:

- ad blocker -> [ublock origin](https://www.stefanvd.net/project/zoom/browser/options.html)
- password store -> [bitwarden](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb)
-  text zoom -> [Zoom for Google Chrome](https://chrome.google.com/webstore/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd?hl=en)
- EU GDPR cookie banners -> [I don't care about Cookies](https://chrome.google.com/webstore/detail/i-dont-care-about-cookies/fihnjjcciajhdojfnbdddfaoknhalnja?hl=en)

of course they should (must) work with Kiwi Browser ...

**Comment by d3ward** [comment]
I like what you did here with that list , but it's better if you comment on respective issues with you suggested solutions

**Comment by gnadelwartz** [comment]
Which I always do, of course :-) , and also pointing to this issue as reference whre to download  the mentioned extension

**Comment by kiwibrowser** [comment]
https://data.firefox.com/dashboard/usage-behavior

This "top add-ons" list that Firefox compiled (per country!) may be interesting to explore

**Comment by gnadelwartz** [comment]
adblocker seems to be the top extensions worldwide and in my country Germany also.

but can't believe that globally 65% use no extensions at all!
