### ISSUE TITLE
Problem With Direct Apps

### ISSUE THREAD

**Issue by Zorosan17** [kiwibrowser/src.next#334]
Link to apps not direct to app, instead to playstore

Lets say i want to open link mega.nz to app mega, the link not direct to app mega, but instead direct to playstore ( i have install app mega on my device)

https://user-images.githubusercontent.com/88958226/129468044-856aa14d-026c-47a8-893e-e1b4b03c3e47.mp4

 - Device: Redmi Note 8 Pro
 - Android Version : A11
 - Kiwi Browser Version 93.0.4577.39

This problem not happen on old version.

**Comment by DUOLabs333** [comment]
Can you give an example link to test on?

**Comment by Zorosan17** [comment]
Here;
https://mega.nz/file/5YNGyTjA#3bPFUvFQfWSSKI2OdTHj9TUPNmiDfN5HQN64x7PzP_0

This problem effect on other apps like reddit too

**Comment by DUOLabs333** [comment]
Ok, I can confirm that this is a bug. I'll look into it once the build a scripts work again.
