### ISSUE TITLE
dark theme more grey

### ISSUE THREAD

**Issue by skupi20** [kiwibrowser/src.next#335]
in latest version you add more black colors to dark theme. i prefer more grey like were before. For daylight its better to use grey colors. Night mode already has black colors, why you change it for dark theme. Is it possible to get those grey colors before latest update?
Maybe give additional option. Thx in advance.

**Comment by DUOLabs333** [comment]
I actually like it the way it is, but maybe there could be configuration. Chrome, especially mobile, does not allow for a lot of customization, so it would be lot of work to add it in.

**Comment by d3ward** [comment]
#101
