### ISSUE TITLE
iOS (Jailbreak-Only) App Support

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [kiwibrowser/src.next#339]
**Is your feature request related to a problem? Please describe.**
There is no any browser with extension support on iOS and iPadOS devices (even if we jailbroken)
**Describe the solution you'd like**
Getting a kiwi or any browser based on full chromium to get crx extension support or any based browser with any extension support

**Describe alternatives you've considered**
/
**Additional context**
/

**Comment by DUOLabs333** [comment]
iOS is a beast in of itself, and would require basically a whole other team. iOS apps aren't even written in Java, so it would require basically a rewrite.

**Comment by gnadelwartz** [comment]
an other option may an Android Emulator for iOS, there seems some on Cydia ...

**Comment by DUOLabs333** [comment]
Should be closed as a wontfix.
