### ISSUE TITLE
Battery draining issue

### ISSUE THREAD

**Issue by Subbarao6338** [kiwibrowser/src.next#341]
I am battery draining issue since last update.

**Comment by DUOLabs333** [comment]
This is very unclear, and can be due to any number of reasons. Could you be more specific?

**Comment by rdsylsq** [comment]
Installing too many plugins and scripts will lead to excessive power consumption

**Comment by d3ward** [comment]
@Subbarao6338 I'm closing this as it's quite old. Feel free to reopen it if the problem still exists.
