### ISSUE TITLE
ChromePie doesn't work with 93.x

### ISSUE THREAD

**Issue by kkuhle** [kiwibrowser/src.next#345]
**Describe the bug**
Xposed module ChromePie for Chromium browsers does not work on new versions

**To Reproduce**
1. Have xposed on a device with the ChromePie module enabled for KiwiBrowser [version Git210216Gen570536402 (2102162)] (activation of ChromePie works)
2. Upgrade to a newer version (93.x+) of KiwiBrowser from the Play Store
3. Observe ChromePie no longer works

**Expected behavior**
ChromePie should be able to activate.  It works on all other Chromium browsers (including the old KiwiBrowser) that I've tested.

**Screenshots**

- old kiwibrowser works
<img src="https://user-images.githubusercontent.com/11251306/129792170-42cf459f-376d-41fa-b177-34e3c5540def.jpg" width="350">

- new kiwibrowser doesn't work
<img src="https://user-images.githubusercontent.com/11251306/129792172-ef191684-d5f1-4ba5-8a91-32952b2b24b1.jpg" width="350">

- enabled in lsposed along with some other Chromium browsers that work
<img src="https://user-images.githubusercontent.com/11251306/129792169-3a46ad70-36fe-4c3a-93e1-df912f696a67.jpg" width="350">

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T running Havoc OS
- Application version
Kiwi Browser 93.0.4577.39
- Operating system
Android 11; ONEPLUS A6013 Build/RQ2A.210405.005

**Additional context**
Digging through the settings, I wonder if it could have anything to do with `Settings > Accessibility > Edge swipe` configuration.  Either value I use to configure this, ChromePie will not activate.  When I use Google Chrome, the pie function activates, but occasionally I still see the little arrow (annoying).

When I turn off `Swipe Navigation` in Edge (Settings > Browsing options > Swipe Navigation) the pie still works.  It also still works with it on.  Anyway, considering the results in Edge, maybe the setting makes no difference, but I thought it was worth mentioning.

One other point that might be worth mentioning is that every other modern Android Chromium browser I've tested is 92.x whereas KiwiBrowser is 93.x.  Perhaps this version is breaking ChromePie's ability to activate.

Edit: I tested Google Chrome Beta which gives me an **Application Version** of `Chrome Beta 93.0.4577.37` so I don't think this is it (I also tested all other KiwiBrowser versions on 93 with no different result)

**Comment by gnadelwartz** [comment]
Chrome pie seems not to be simply a Chrome extension, at least from what I understand what I found on a google search.
as kiwi can not adjust to every external framework, it may help to file a bug request on their github repository (also)

**Comment by kkuhle** [comment]
You're right, @gnadelwartz it isn't a Chrome extension at all.  It's a really nice Xposed module that hasn't been updated/maintained since Jul 22, 2018.  I can file a bug request on the repo https://github.com/JayT5/ChromePie but I believe it's been totally abandoned.  I will do it anyway in case the developer decides to pick it up again.

ChromePie works on every other Android Chromium browser I've tried, so I'm suspicious about some changed in the latest KiwiBrowser versions (like maybe how gesture navigation has been modified) that prevent it from working.

Moving the toolbar down to the bottom of the screen is a very useful feature, but then I can't swipe across the address bar to quickly change tabs (maybe I could without Android 11 gesture navigation) or easily swipe down to show the tab switcher (instead, we can swipe up, but I find myself accidentally going home too often to use this setting).  

Additionally, ChromePie vs using the Chromium menu is just a lot quicker and I don't fumble around like I do in the Chromium menu trying to find things that may have moved because of a recent extension I added, etc.

**Comment by d3ward** [comment]
As this seems to be more a framework bug rather than Kiwi , the issue will be closed

**Comment by kkuhle** [comment]
This seems to be fixed with the September 21st update.  I noticed the browser looks like kiwibrowser classic where the bug was not present.  Wondering if the API level was decreased to avoid some bugs such as [325](https://github.com/kiwibrowser/src.next/issues/325).  Not complaining.  Glad that it's working
