### ISSUE TITLE
Adguard settings page bug

### ISSUE THREAD

**Issue by Jerry-1984** [kiwibrowser/src.next#348]
**Describe the bug**

The display of the adguard extension setting page is incomplete and the page cannot be dragged, so it cannot be used normally!

**To Reproduce**
Access the adguard extension settings page

**Smartphone (please complete the following information):**
 - Device: [mi mix3]
 - Android Version : [10]
 - Kiwi Browser Version [93.0.4577.39]

**Comment by d3ward** [comment]
This is fixed. Tested on the latest 112 builds
