### ISSUE TITLE
Cannot access Google Extensions Store.

### ISSUE THREAD

**Issue by Oppa-YA** [kiwibrowser/src.next#35]
Cannot access Google Extensions Store. Seems like Google Store recognizes this NEXT version of browser as mobile browser and not desktop. I also tried desktop mode but it does not help. Here is the screenshot: [https://i.imgur.com/5MCZJkQ.png](url)

**Comment by Xi-PP** [comment]
https://chrome.google.com/webstore
Try again. After I removed the unsupported word form link manually. It's working fine

**Comment by kiwibrowser** [comment]
Thanks @Xi-PP  for the diagnostic.
@Oppa-YA I have added a fix in the latest version of src.next so /unsupported redirects to the main web store.

It will be there at the next build.

**Comment by Oppa-YA** [comment]
> https://chrome.google.com/webstore
> Try again. After I removed the unsupported word form link manually. It's working fine

Thanks, it helped!

**Comment by Oppa-YA** [comment]
> Thanks @Xi-PP  for the diagnostic.
> @Oppa-YA I have added a fix in the latest version of src.next so /unsupported redirects to the main web store.
> 
> It will be there at the next build.

Thank you! Waiting for next build's and release!
