### ISSUE TITLE
National Flags Vector Images Inverted Colours in Dark Mode

### ISSUE THREAD

**Issue by jututt** [kiwibrowser/src.next#352]
See screenshot, as per title, applies to .svg vector graphics, thanks.
White renders in black, other dark colors render in a lighter shade
![Screenshot_2021-08-20-07-02-26-557_com kiwibrowser browser](https://user-images.githubusercontent.com/29811680/130182365-6f4cec72-a445-44ff-b6dd-303a441ffbd2.jpg)

**Comment by samlux04** [comment]
it also happens on chan. tho the flag is PNG.

**Comment by jututt** [comment]
closed with v.98
