### ISSUE TITLE
Download notifications cannot be dismissed do not finish and do not react to pause or cancel

### ISSUE THREAD

**Issue by colinardo** [kiwibrowser/src.next#353]
After the latest update, Download notifications stay open permanently also after the download has finished. They stay open in an unusable state, do not react to pause or cancel actions anymore and cannot be dismissed. To clear the notifications you have to forcefully close Kiwi browser in the system settings. Closing Kiwi via Exit Button does not help.
I am using a OnePlus 5 with Android 9.

@colinardo

**Comment by KaKi87** [comment]
I cannot reproduce your issue using the latest Kiwi Browser version from the Play Store, please provide an example link if you can reproduce it.

**Comment by colinardo** [comment]
> 
> 
> I cannot reproduce your issue using the latest Kiwi Browser version from the Play Store, please provide an example link if you can reproduce it.
I have tested it again with then current version (some updates since the last time i tested this problem), and now it works again, the issue seems to be fixed. Thanks!
