### ISSUE TITLE
Stuck when returning from a background task

### ISSUE THREAD

**Issue by huazhaozhe** [kiwibrowser/src.next#355]
Occasionally, kiwi returns from the background to the foreground, the application is stuck, the screen is blank, and it cannot be operated, so I have to cross out the task and reopen kiwi.

redmi k40(POCO f3) Android11 MIUI12.5/21.8.10

**Comment by karl-pae** [comment]
Have you tried recent release? https://github.com/kiwibrowser/src.next/releases

**Comment by huazhaozhe** [comment]
> Have you tried recent release? https://github.com/kiwibrowser/src.next/releases

Yes now it's getting better
