### ISSUE TITLE
Chromium 94

### ISSUE THREAD

**Issue by kryptobolt200528** [kiwibrowser/src.next#356]
Hey chromium 94 implementation would be good👍

**Comment by Dark-Matter7232** [comment]
Do not worry, it will get rebased automatically.

**Comment by karl-pae** [comment]
From the readme file:
> Source-code for Kiwi Next, a Kiwi Browser auto-rebased with latest Chromium.

You may close this.

**Comment by kiwibrowser** [comment]
Today will be a build based on 94.0.4606.25

**Comment by karl-pae** [comment]
> Today will be a build based on 94.0.4606.25

(Does it really matter) What is the time period for auto rebase after new chromium release?

**Comment by kiwibrowser** [comment]
The goal is to stay +/- 1 major version about Chromium stable but it's difficult to say how it will be.
The timing really depends mostly on how stable is Chromium. The main point to verify are potential regressions in Chromium (about 1 month ago, 94 was in a very unstable state), as Kiwi itself is now mostly stabilized

**Comment by karl-pae** [comment]
Today new build released with V94

close this 🙂

**Comment by karl-pae** [comment]
Close this issue now @kryptobolt200528 

cc: @d3ward
