### ISSUE TITLE
The extension icons are still broken in Android 5

### ISSUE THREAD

**Issue by kyoyacchi** [kiwibrowser/src.next#369]
https://user-images.githubusercontent.com/63583961/131389354-bd2d282a-e664-459c-a900-7c9f7761ba33.mp4

here is the proof with video.

is it relevant with android version or not?

**Comment by kyoyacchi** [comment]
@kiwibrowser what do you think?

**Comment by kiwibrowser** [comment]
I don't really understand even with the video ? What do you mean by saying broken?

**Comment by metronightly** [comment]
> I don't really understand even with the video ? What do you mean by saying broken?

I think what they mean is that the extension icon don't show up in colors at the beginning, the colors appear after a few seconds.

**Comment by kyoyacchi** [comment]
@metronightly , Yes i meant that.

**Comment by d3ward** [comment]
@kyoyacchi Does this problem still exist? I know it's been a while, but I feel the issue has been fixed by a recent update, if not feel free to reopen the issue with details
