### ISSUE TITLE
YouTube BG Auto Pause Issue

### ISSUE THREAD

**Issue by Xi-PP** [kiwibrowser/src.next#37]
I'm using https://github.com/kiwibrowser/android/issues/60#issue-442779973 this one for YouTube background playback. Background playback is working but if I switch tabs I have to **resume from notification panel**.
I think that it's easy to fix since it's **working properly on stable version [Old Kiwi]** of Kiwi Browser.  Please fix this. I don't want to Pause the playback.❤️

**Comment by kiwibrowser** [comment]
<img width="462" alt="Screenshot 2021-07-11 at 17 40 17" src="https://user-images.githubusercontent.com/40272275/125199488-0fd81a00-e26f-11eb-98eb-6f13b6f6d748.png">

We did a poll today about this
A fix will come today

**Comment by Xi-PP** [comment]
Great Sir ❤️

**Comment by kiwibrowser** [comment]
Done, will be there upcoming build

**Comment by sudo-nautilus** [comment]
I don't know it's fair to ask it here,
But anyway,
@Xi-PP are you still alive?
And why you just deleted your Telegram account?
