### ISSUE TITLE
[BUG] DevTools tabs hidden under status bar when bottom toolbar is enabled

### ISSUE THREAD

**Issue by Y-T-G** [kiwibrowser/src.next#38]
The tabs appear momentarily in the beginning and then disappears under the status bar.

![Screenshot_20210712-011137_Kiwi_Browser_(Next)](https://user-images.githubusercontent.com/32206511/125204164-6e70b880-e2ae-11eb-9964-ddc3ab4d6457.png)

**Comment by kiwibrowser** [comment]
This is a serious issue and will be fixed in the upcoming days, one workaround is to use the hand button from the bottom toolbar) to catch the top of the page

**Comment by kiwibrowser** [comment]
(the hand button is off on your screenshot)

**Comment by kiwibrowser** [comment]
Hello,

The issue has been resolved in past builds, this was due to incorrect viewport calculation.
