### ISSUE TITLE
Block websites from changing toolbar color in light theme

### ISSUE THREAD

**Issue by karl-pae** [kiwibrowser/src.next#388]
**Is your feature request related to a problem? Please describe.**
Many websites change the toolbar and status bar color while using light theme, it should be white. Further, with bottom toolbar enabled, it looks ugly. On contrary, while using dark theme, the toolbar and status bar color doesn't change and remains black.

**Describe the solution you'd like**
The light theme should adopt the property of dark theme.

**Describe alternatives you've considered**
Some people like this color change so instead a toggle [prevent toolbar color change] can be provided in settings without changing the property of light theme. Just like Remove AMP.

**Additional context**
I like all white, I like reading blacks on whites so I have to use light theme. You know, if dark mode is enabled then websites will load in dark mode. It will be great if these changes are implemented soon with upcoming builds. 😍

Edit:
Light theme has pink colour on top and bottom, looks ugly. Dark theme has no effect, remains black.
![Screenshot_20210922-041909](https://user-images.githubusercontent.com/83178186/134258218-6e8ff0d3-144d-4666-b4f6-742f611f58d0.jpg)
![Screenshot_20210922-041926](https://user-images.githubusercontent.com/83178186/134258223-54c5ee3e-f433-4505-83c7-f2e056b6079d.jpg)

**Comment by metronightly** [comment]
This would be a great addition.

**Comment by karl-pae** [comment]
@metronightly Yup. I am. :)
