### ISSUE TITLE
Support High Refresh Rate Displays

### ISSUE THREAD

**Issue by karl-pae** [kiwibrowser/src.next#389]
**Describe the bug**
Kiwi browser doesn't utilise system high refresh rate

**To Reproduce**
Open testufo.com
Set count of UFOs to 1

**Expected behavior**
Should get 90fps on 90Hz screen

**Smartphone (please complete the following information):**
 - Device: [OnePlus 7T]
 - Android Version : [Android 11 ]
 - Kiwi Browser Version [ 94.0.4606.54  ]

**Additional context**
Chrome and Microsoft Edge gets 90fps.

**Comment by tancysam** [comment]
If I'm not wrong, only browsers whitelisted by Oneplus can be used at high refresh rates. Try using AutoHz instead to force 90hz on Kiwi.

**Comment by karl-pae** [comment]
... it does seem to be a OnePlus specific issue. Closing.
