### ISSUE TITLE
[BUG] Deprecate Android file system permission & in-app browser crash

### ISSUE THREAD

**Issue by MrPurple666** [kiwibrowser/src.next#39]
On Android 11 file permission was changed because of scoped storage, Kiwi Browser (NEXT) is using deprecated permission making it unable to read external HTML (and others) that is in internal memory be read.
When opening a link within an app that contains the "in-app browser" function (I don't know the correct name for this function so I called it that) by clicking on the three dots in the upper right corner the Kiwi Browser crashes.

![2021_07_11_23_56_42](https://user-images.githubusercontent.com/78635632/125224425-fdc49e80-e2a3-11eb-8628-177e3c752869.gif)

**Comment by d3ward** [comment]
Hi , do you still face that issue ? seems to be fixed with recent builds

**Comment by MrPurple666** [comment]
> Hi , do you still face that issue ? seems to be fixed with recent builds

currently the problem that existed in "in-app" browser has been fully corrected and no longer happens crash. About the problem with scoped storage (reading HTML and the like) hasn't been solved yet :(
Anyway, as I currently use Android 11 if you decompile the APK or build from source with this permission ( `<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />` )
this is fixed on Android 11 (Android 10 and below works fine without this):

**Comment by d3ward** [comment]
@kiwibrowser take a look at this ☝️

**Comment by MrPurple666** [comment]
The aforementioned bugs have been resolved.
