### ISSUE TITLE
Minor branding issue

### ISSUE THREAD

**Issue by MooShuOrc** [kiwibrowser/src.next#393]
In Settings > Privacy and security > Safe Browsing, there are a number of claims that Safe Browsing (and other services) are provided by Geometry. I'm fairly sure this is a Google service. You should be clear and accurate about to whom the users' data is being sent (Geometry, Google or both?).

In any event, this part is definitely wrong: "...other Geometry services, like Gmail..." If Google catches you (accidentally) claiming to own Gmail, they won't be happy.

Just a heads up.

**Comment by kiwibrowser** [comment]
It's pretty obvious (even for Google) that this is a translation issue and that it comes from the auto-replacement of Google by Geometry (in order, exactly for this, to not create confusion).
Obviously Safe Browsing is Google service, and this SafeBrowsing screen is so deep in the UI that it was forgotten, but you know it :)

It's fixed.
![Screenshot_20210923-024419](https://user-images.githubusercontent.com/40272275/134436227-823c7737-6cde-496b-9934-6dbca72948f2.jpg)

**Comment by MooShuOrc** [comment]
As of 95.0.4638.75 it's back.

If you run the same Find/Replace for every release, it's time to change the habit.
