### ISSUE TITLE
Hand button adds extra margin on top

### ISSUE THREAD

**Issue by karl-pae** [kiwibrowser/src.next#395]
**Describe the bug**
If I tap hand button, it takes me to top of the page but also adds extra space on top.  

**To Reproduce**
Reference: watch the video

**Expected behavior**
It should remain like the original page without adding top margin

**Screenshots**

https://user-images.githubusercontent.com/83178186/134565712-a782dd65-a0a9-4088-a65c-d2d9a7379c27.mp4

**Smartphone (please complete the following information):**
 - Device: [ OnePlus 7T ]
 - Android Version : [ A11 ]
 - Kiwi Browser Version [ 94.0.4606.56 ]

**Additional context**

**Comment by d3ward** [comment]
That is not a bug, is how hand button works.
Hand button is not intended to just go on top, but to make website usable with one hand.
It shift the page to half so you can reach the top, if you click again will be back to normal
