### ISSUE TITLE
How to change back to the view of the new label of the original style?

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src.next#4]
In the next version, it is shown as Figure 1. In the old version, it is shown as Figure 2. The operation of Figure 2 is better than that of Figure 1.
Hope to add options to support Figure 2.

![Screenshot_20210630_211215_com kiwibrowser browse](https://user-images.githubusercontent.com/55195642/123967736-2f5a8180-d9e9-11eb-92a0-a09c288584eb.jpg)
![Screenshot_20210630_211209_com kiwibrowser browse](https://user-images.githubusercontent.com/55195642/123967744-308bae80-d9e9-11eb-842b-09bcac85957e.jpg)

**Comment by d3ward** [comment]
In new Kiwi builds , you have to go on Settings>Tab Switcher and choose the "Vertical" view
