### ISSUE TITLE
manifest v2 support

### ISSUE THREAD

**Issue by tortino** [kiwibrowser/src.next#403]
Please continue to support manifest v2 after google will remove it from chrome in 2023.
For me the main reason to use Kiwi is extensions support, and in particular ability to run ublock origin.
Without manifest v2 ublock won't work.
Thank you.

**Comment by gnadelwartz** [comment]
currently it's not planned to drop v2 support on kiwi, nevertheless after google drop there may not many active maintained extensions left ...
