### ISSUE TITLE
Add backup feature like as in Soul Browser.

### ISSUE THREAD

**Issue by kyoyacchi** [kiwibrowser/src.next#404]
It would be really good to backup our settings to device and restore it, right?

Like this

![Screenshot_2021-09-29-21-59-25](https://user-images.githubusercontent.com/63583961/135332021-db13b1a0-0778-43dd-bda9-97299c2b8b42.png)
![Screenshot_2021-09-29-21-59-29](https://user-images.githubusercontent.com/63583961/135332025-a063fb2a-025a-4352-8e48-26136e640c96.png)

**Comment by KaKi87** [comment]
Duplicate of #122

**Comment by kyoyacchi** [comment]
> Duplicate of #122

What makes you think that this issue is "duplicate"?

**Comment by KaKi87** [comment]
Because it's the same feature request.
