### ISSUE TITLE
unable to login Facebook comments plugin

### ISSUE THREAD

**Issue by samlux04** [kiwibrowser/src.next#405]
after clicking login it open a new tab to login. login successfully and closed automatically, back to previous tab. it reload the fb iframe but it still unlogged. then it open a new tab again and closed automatically then reload the iframe. repeated indefinitely.
already disabled all extension, data saver. 

https://m.manganelo.com/genre-4

**Comment by kyoyacchi** [comment]
Hmm? Interesting. I tried it but it worked. I have Privacy Badger as Extension, after i give permission to let the m.facebook.com, and www.facebook.com in Privacy Badger, it did work. Did you tried with Privacy Badger? It may work by any chance.

![Screenshot_2021-10-01-23-48-54~2](https://user-images.githubusercontent.com/63583961/135684756-5c0047bf-490f-4cda-9239-73b7bd552774.png)

**Comment by samlux04** [comment]
I didn't. But it should work by default without any change or extensions, else there's a bug.

**Comment by d3ward** [comment]
@samlux04 I know it's been a while, but is this still a thing? Kiwi has been updated and improved since this issue was created. Feel free to reopen the issue if the problem persists.
