### ISSUE TITLE
Bottom Bar - Open tabs visibility isssue

### ISSUE THREAD

**Issue by b1ackfa1c0n** [kiwibrowser/src.next#41]
Open tabs switch isn't displayed properly while using bottom toolbar

Not using bottom toolbar: 
![20210712_180752](https://user-images.githubusercontent.com/66196864/125320784-b6dab580-e344-11eb-9891-91ea9d0c0aaf.jpg)

Using bottom toolbar:
![20210712_180630](https://user-images.githubusercontent.com/66196864/125321032-f6090680-e344-11eb-8541-afaf46d4acb1.jpg)

**Comment by d3ward** [comment]
Issues related to bottom bar has been fixed and looks like tabstrip is deprecated ? can't find any option to enable that
