### ISSUE TITLE
Search engine "Qwant" is not available in Turkey.

### ISSUE THREAD

**Issue by kyoyacchi** [kiwibrowser/src.next#412]
![Screenshot_2021-10-07-14-17-51](https://user-images.githubusercontent.com/63583961/136374301-faecd71b-8103-46e6-846a-14fe024a4c07.png)

It says "_yet_", but i don't think they'll make it available in Turkey _again_ .

So, i think that search engine should not visible for that does not available countries.
or idk...

Lite one is working well.

**Comment by karl-pae** [comment]
This issue is not related to Kiwi Browser. 

Close this @d3ward

**Comment by kyoyacchi** [comment]
> This issue is not related to Kiwi Browser.
> 
> Close this @d3ward

Bruh. So it's related with what then?

**Comment by d3ward** [comment]
> Bruh. So it's related with what then?

It's related to the search engine not to the Kiwi Browser. As the page says , _Qwant is not available in your country_
