### ISSUE TITLE
MediaCodec decode failed on some device

### ISSUE THREAD

**Issue by Apollo2nd** [kiwibrowser/src.next#415]
**Describe the bug**
The web media players play video failed on some device, latest release 94.0.4606.56. 
Meamwhile, They all work well with elder release 93.0.4577.39.
Look from logcat, the root cause of this issue looks like that the OMX allocate too many buffer and device doesn't support.

**To Reproduce**
Play web video on some amlogic set-top-box.

**Expected behavior**
Web media player works well, video playback OK.

**Screenshots**
The player has no picture output, just black.

**Smartphone (please complete the following information):**
 - Device: Amlogic STB
 - Android Version : AOSP9
 - Kiwi Browser Version [ 94.0.4606.56]

**Additional context**
Here is the logcat output

10-16 21:45:28.130 I/ActivityManager( 3418): Start proc 4996:com.kiwibrowser.browser:sandboxed_process3/u0i3 for service com.kiwibrowser.browser/org.chromium.content.app.SandboxedProcessService3
10-16 21:45:28.135 W/dboxed_process( 4996): Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
10-16 21:45:28.138 E/dboxed_process( 4996): Not starting debugger since process cannot load the jdwp agent.
10-16 21:45:28.175 I/cr_tabmodel( 4719): Appending tabs being restored to metadata lists, 0, startingNormalCount: 2, startingIncognitoCount: 0
10-16 21:45:28.175 I/cr_tabmodel( 4719): Serializing tab lists; counts: 2, 0
10-16 21:45:28.188 W/dboxed_process3( 4996): type=1400 audit(0.0:49): avc: denied { getattr } for path="/data/data/com.kiwibrowser.browser" dev="mmcblk0p20" ino=1709 scontext=u:r:isolated_app:s0:c3,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c53,c256,c512,c768 tclass=dir permissive=0
10-16 21:45:28.223 I/cr_SplitCompatApp( 4996): Launched version=94.0.4606.56 minSdkVersion=21 isBundle=true processName=com.kiwibrowser.browser:sandboxed_process3 isIsolated=true
10-16 21:45:28.229 W/SystemServiceRegistry( 4996): No service published for: uimode
10-16 21:45:28.234 I/LoadedApk( 4996): No resource references to update in package com.kiwibrowser.browser.dev_ui
10-16 21:45:28.234 I/LoadedApk( 4996): No resource references to update in package com.kiwibrowser.browser.vr
10-16 21:45:28.235 I/LoadedApk( 4996): No resource references to update in package com.kiwibrowser.browser.test_dummy
10-16 21:45:28.241 I/cr_ChildProcessService( 4996): Creating new ChildProcessService pid=4996
10-16 21:45:28.247 I/cr_OPArchivePublisher( 4719): ADM threw while trying to remove a download. java.lang.IllegalArgumentException: input param 'ids' can't be null
10-16 21:45:28.258 I/cr_LibraryLoader( 4996): libraryName: /data/app/com.kiwibrowser.browser-wiG0Ha4XhVfuAi7RDxLG_A==/base.apk!/lib/armeabi-v7a/crazy.libchrome.so
10-16 21:45:28.261 W/cr_LibraryLoader( 4996): Forcing system linker, relocations will not be shared. This negatively impacts memory usage.
10-16 21:45:28.335 I/cr_LibraryLoader( 4996): Successfully loaded native library
10-16 21:45:28.336 W/dboxed_process( 4996): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (dark greylist, reflection)
10-16 21:45:28.337 W/dboxed_process( 4996): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (dark greylist, reflection)
10-16 21:45:28.337 W/dboxed_process( 4996): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (dark greylist, reflection)
10-16 21:45:28.338 I/cr_CachingUmaRecorder( 4996): Flushed 2 samples from 2 histograms.
10-16 21:45:28.406 I/chromium( 4996): [INFO:dark_mode_settings_builder.cc(38)] [Kiwi] ParseDarkModeSettings
10-16 21:45:28.406 I/chromium( 4996): [INFO:dark_mode_settings_builder.cc(54)] [Kiwi] ParseDarkModeSettings - A: contrastpercent -- 0
10-16 21:45:31.164 I/MessageMonitor( 3327): G[3]: [NU-AmNuPlayer] Last Message 15 is ['mckN':0], cost 22 Us
10-16 21:45:31.167 I/MessageMonitor( 3327): G[3]: [NU-GenericSource] Last Message 777 is [0x00000009:0], cost 662 Us
10-16 21:45:31.207 I/MessageMonitor( 3327): G[3]: [NU-NuPlayerRenderer] Last Message 8320 is ['queB':0], cost 30 Us
10-16 21:45:31.209 I/MessageMonitor( 3327): G[3]: [NU-NuPlayerDecoder-audN] Last Message 13833 is ['cdcN':2], cost 55 Us
10-16 21:45:31.209 I/MessageMonitor( 3327): [NU-NuPlayerDecoder-audN] DQ pts(120502857), In pts(120502857) [0/4], Out pts(120398367),Render pts(-1[0]), Drop pts(-1[0]) [0/4]
10-16 21:45:32.338 I/NU-NuPlayerRenderer( 3327): PTS: AV sync info:Audio on Header 
10-16 21:45:32.338 I/NU-NuPlayerRenderer( 3327): PTS:   SystemTimeStamp:121039732
10-16 21:45:32.338 I/NU-NuPlayerRenderer( 3327): PTS:   Last AudioTimeStamp:121469387
10-16 21:45:32.338 I/NU-NuPlayerRenderer( 3327): PTS:   Last VideoTimeStamp:0
10-16 21:45:32.338 I/NU-NuPlayerRenderer( 3327): PTS:   AV diff:121039732 ,Ajump:0,Vjump:0
10-16 21:45:32.338 I/NU-NuPlayerRenderer( 3327): PTS:   mAjumpedNum:0, mAudioJumped till now=1006069912
10-16 21:45:32.338 I/NU-NuPlayerRenderer( 3327): PTS:   mVjumpedNum:0, mVideoJumped till now=1006069912
10-16 21:45:32.339 I/NU-NuPlayerRenderer( 3327): PTS:   mTotalAudioJumpedTimeUs:0
10-16 21:45:32.339 I/NU-NuPlayerRenderer( 3327): PTS:   mLastVideoUs:-1
10-16 21:45:32.339 I/NU-NuPlayerRenderer( 3327): PTS:   mLastAudioUs:121469387
10-16 21:45:40.147 I/cr_tabmodel( 4719): Appending tabs being restored to metadata lists, 0, startingNormalCount: 2, startingIncognitoCount: 0
10-16 21:45:40.147 I/cr_tabmodel( 4719): Serializing tab lists; counts: 2, 0
10-16 21:45:40.161 I/cr_MediaCodecBridge( 4787): create MediaCodec video decoder, mime video/avc
10-16 21:45:40.161 D/        ( 4719): PlayerBase::PlayerBase()
10-16 21:45:40.162 D/        ( 4719): TrackPlayerBase::TrackPlayerBase()
10-16 21:45:40.162 I/libOpenSLES( 4719): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
10-16 21:45:40.163 W/AudioFlinger( 3199): createTrack_l(): mismatch between requested flags (00000008) and output flags (00000002)
10-16 21:45:40.163 D/AudioFlinger( 3199): Client defaulted notificationFrames to 1026 for frameCount 2052
10-16 21:45:40.179 I/OMXClient( 4787): IOmx service obtained
10-16 21:45:40.179 I/chatty  ( 3332): uid=1046(mediacodec) HwBinder:3332_C expire 49 lines
10-16 21:45:40.185 I/MediaCodec( 4787): MediaCodec will operate in async mode
10-16 21:45:40.187 D/SurfaceUtils( 4787): connecting to surface 0xc3a6c808, reason connectToSurface
10-16 21:45:40.187 I/MediaCodec( 4787): [OMX.amlogic.avc.decoder.awesome] setting surface generation to 4901894
10-16 21:45:40.187 D/SurfaceUtils( 4787): disconnecting from surface 0xc3a6c808, reason connectToSurface(reconnect)
10-16 21:45:40.187 D/SurfaceUtils( 4787): connecting to surface 0xc3a6c808, reason connectToSurface(reconnect)
10-16 21:45:40.187 I/AmAVUtils( 4787): AmAVUtils::getComponentRole isEncoder :0 mime:video/avc 
10-16 21:45:40.187 V/AVUtils ( 4787): AVUtils::getComponentRole
10-16 21:45:40.187 I/chatty  ( 3332): uid=1046(mediacodec) HwBinder:3332_B expire 14 lines
10-16 21:45:40.187 E/ACodec  ( 4787): [OMX.amlogic.avc.decoder.awesome] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
10-16 21:45:40.188 I/chatty  ( 3332): uid=1046(mediacodec) omx@1.0-service expire 22 lines
10-16 21:45:40.188 I/chatty  ( 3332): uid=1046(mediacodec) HwBinder:3332_F expire 2 lines
10-16 21:45:40.193 I/chatty  ( 3332): uid=1046(mediacodec) HwBinder:3332_C expire 31 lines
10-16 21:45:40.193 I/chatty  ( 3332): uid=1046(mediacodec) omx@1.0-service expire 16 lines
10-16 21:45:40.193 I/AmAVUtils( 4787): AmAVUtils::isAudioExtendFormat input = video/avc
10-16 21:45:40.194 I/chatty  ( 3332): uid=1046(mediacodec) HwBinder:3332_B expire 33 lines
10-16 21:45:40.209 I/chatty  ( 3332): uid=1046(mediacodec) omx@1.0-service expire 11 lines
10-16 21:45:40.212 W/AshmemAllocator( 3175): ashmem_create_region(1048576) returning hidl_memory(0xed816170, 1048576)
10-16 21:45:40.213 W/AshmemAllocator( 3175): ashmem_create_region(1048576) returning hidl_memory(0xed816170, 1048576)
10-16 21:45:40.214 W/AshmemAllocator( 3175): ashmem_create_region(1048576) returning hidl_memory(0xed816170, 1048576)
10-16 21:45:40.219 D/SurfaceUtils( 4787): disconnecting from surface 0xc3a6c808, reason setNativeWindowSizeFormatAndUsage
10-16 21:45:40.219 D/SurfaceUtils( 4787): connecting to surface 0xc3a6c808, reason setNativeWindowSizeFormatAndUsage
10-16 21:45:40.219 D/SurfaceUtils( 4787): set up nativeWindow 0xc3a6c808 for 1920x1088, color 0x11, rotation 0, usage 0x402b00
10-16 21:45:40.219 I/chatty  ( 3332): uid=1046(mediacodec) HwBinder:3332_B expire 76 lines
10-16 21:45:40.220 W/MediaCodec_loop( 4787): type=1400 audit(0.0:50): avc: denied { read } for name="u:object_r:media_prop:s0" dev="tmpfs" ino=299 scontext=u:r:untrusted_app:s0:c53,c256,c512,c768 tcontext=u:object_r:media_prop:s0 tclass=file permissive=0
10-16 21:45:40.221 W/ACodec  ( 4787): [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 10 failed: -1010
10-16 21:45:40.222 W/ACodec  ( 4787): [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 9 failed: -1010
10-16 21:45:40.223 W/ACodec  ( 4787): [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
10-16 21:45:40.224 W/ACodec  ( 4787): [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
10-16 21:45:40.224 E/ACodec  ( 4787): Failed to allocate buffers after transitioning to IDLE state (error 0xfffffc0e)
10-16 21:45:40.224 E/ACodec  ( 4787): signalError(omxError 0x80001001, internalError -1010)
10-16 21:45:40.224 E/MediaCodec( 4787): Codec reported err 0xfffffc0e, actionCode 0, while in state 5
10-16 21:45:40.225 E/libc    ( 4787): Access denied finding property "media.metrics.enabled"
10-16 21:45:40.225 D/SurfaceUtils( 4787): disconnecting from surface 0xc3a6c808, reason disconnectFromSurface
10-16 21:45:40.226 W/AHierarchicalStateMachine( 4787): Warning message AMessage(what = 'omxI') = {
10-16 21:45:40.226 W/AHierarchicalStateMachine( 4787):   int32_t type = 0
10-16 21:45:40.226 W/AHierarchicalStateMachine( 4787):   int32_t event = 0
10-16 21:45:40.226 W/AHierarchicalStateMachine( 4787):   int32_t data1 = 0
10-16 21:45:40.226 W/AHierarchicalStateMachine( 4787):   int32_t data2 = 1
10-16 21:45:40.226 W/AHierarchicalStateMachine( 4787): } unhandled in root state.
10-16 21:45:40.227 E/cr_MediaCodecBridge( 4787): Cannot start the media codec
10-16 21:45:40.227 E/cr_MediaCodecBridge( 4787): android.media.MediaCodec$CodecException: start failed
10-16 21:45:40.227 E/cr_MediaCodecBridge( 4787): 	at android.media.MediaCodec.native_start(Native Method)
10-16 21:45:40.227 E/cr_MediaCodecBridge( 4787): 	at android.media.MediaCodec.start(MediaCodec.java:2068)
10-16 21:45:40.227 E/cr_MediaCodecBridge( 4787): 	at org.chromium.media.MediaCodecBridge.e(chromium-ChromeModernPublic.aab-stable-460605610:7)
10-16 21:45:40.227 E/cr_MediaCodecBridge( 4787): 	at org.chromium.media.MediaCodecBridgeBuilder.createVideoDecoder(chromium-ChromeModernPublic.aab-stable-460605610:7)
10-16 21:45:40.227 W/cr_MediaCodecBridge( 4787): Releasing: OMX.amlogic.avc.decoder.awesome
10-16 21:45:40.228 I/chatty  ( 3332): uid=1046(mediacodec) HwBinder:3332_C expire 5 lines
10-16 21:45:40.231 W/cr_MediaCodecBridge( 4787): Codec released
10-16 21:45:40.246 D/        ( 4719): PlayerBase::stop() from IPlayer
10-16 21:45:40.247 D/AudioTrack( 4719): stop() called with 4100 frames delivered
10-16 21:45:40.280 D/AudioFlinger( 3199): mixer(0xf0383080) throttle end: throttle time(10)
10-16 21:45:41.060 I/cr_MediaCodecBridge( 4787): create MediaCodec video decoder, mime video/avc
10-16 21:45:41.067 I/OMXClient( 4787): IOmx service obtained
10-16 21:45:41.072 I/MediaCodec( 4787): MediaCodec will operate in async mode
10-16 21:45:41.073 D/SurfaceUtils( 4787): connecting to surface 0xc3a6c808, reason connectToSurface
10-16 21:45:41.074 I/MediaCodec( 4787): [OMX.amlogic.avc.decoder.awesome] setting surface generation to 4901895
10-16 21:45:41.074 D/SurfaceUtils( 4787): disconnecting from surface 0xc3a6c808, reason connectToSurface(reconnect)
10-16 21:45:41.074 D/SurfaceUtils( 4787): connecting to surface 0xc3a6c808, reason connectToSurface(reconnect)
10-16 21:45:41.074 I/AmAVUtils( 4787): AmAVUtils::getComponentRole isEncoder :0 mime:video/avc 
10-16 21:45:41.074 V/AVUtils ( 4787): AVUtils::getComponentRole
10-16 21:45:41.074 E/ACodec  ( 4787): [OMX.amlogic.avc.decoder.awesome] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
10-16 21:45:41.075 I/chatty  ( 3332): uid=1046(mediacodec) HwBinder:3332_B expire 86 lines
10-16 21:45:41.077 I/AmAVUtils( 4787): AmAVUtils::isAudioExtendFormat input = video/avc
10-16 21:45:41.080 V/OmxVideoDecoder( 3332): VendorExt: getConfig: index=7 (low-latency)
10-16 21:45:41.081 D/OmxVideoDecoder( 3332): getConfig 1829 0x6f100004
10-16 21:45:41.082 I/OmxComponent( 3332): OMX_CommandStateSet 740 Cmd 0 nParam1 0x2
10-16 21:45:41.082 I/OmxComponent( 3332): STATE_SET:   OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.082 I/OmxComponent( 3332): STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.082 I/OmxVideoDecoder( 3332): Component Name OMX.amlogic.avc.decoder.awesome, width 1280, height 720
10-16 21:45:41.083 W/AshmemAllocator( 3175): ashmem_create_region(1048576) returning hidl_memory(0xed816170, 1048576)
10-16 21:45:41.084 I/OmxComponent( 3332): STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.084 W/AshmemAllocator( 3175): ashmem_create_region(1048576) returning hidl_memory(0xed816170, 1048576)
10-16 21:45:41.084 I/OmxComponent( 3332): STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.085 W/AshmemAllocator( 3175): ashmem_create_region(1048576) returning hidl_memory(0xed816170, 1048576)
10-16 21:45:41.085 I/OmxComponent( 3332): STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.085 V/OmxVideoDecoder( 3332): updatePort mUseNativeBuffers 1
10-16 21:45:41.085 D/AmlogicVideoDecoderAwesome( 3332): get native buffer info NV:w:1920,h:1088..
10-16 21:45:41.085 V/OmxVideoDecoder( 3332): updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
10-16 21:45:41.085 I/OmxVideoDecoder( 3332): Component Name OMX.amlogic.avc.decoder.awesome, width 1920, height 1088
10-16 21:45:41.085 V/OmxVideoDecoder( 3332): updatePort mUseNativeBuffers 1
10-16 21:45:41.085 D/AmlogicVideoDecoderAwesome( 3332): get native buffer info NV:w:1920,h:1088..
10-16 21:45:41.085 V/OmxVideoDecoder( 3332): updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
10-16 21:45:41.085 I/OmxVideoDecoder( 3332): Component Name OMX.amlogic.avc.decoder.awesome, width 1920, height 1088
10-16 21:45:41.085 D/OmxComponent( 3332): getExtensionIndex 1123 name="OMX.google.android.index.AndroidNativeBufferConsumerUsage"
10-16 21:45:41.086 D/OmxVideoDecoder( 3332): setParameter 951 0x7f00000b
10-16 21:45:41.086 D/OmxVideoDecoder( 3332): OMX_GoogleAndroidIndexAndroidNativeBufferConsumerUsage 0x100
10-16 21:45:41.086 D/OmxComponent( 3332): getExtensionIndex 1123 name="OMX.google.android.index.getAndroidNativeBufferUsage"
10-16 21:45:41.087 D/SurfaceUtils( 4787): disconnecting from surface 0xc3a6c808, reason setNativeWindowSizeFormatAndUsage
10-16 21:45:41.087 D/SurfaceUtils( 4787): connecting to surface 0xc3a6c808, reason setNativeWindowSizeFormatAndUsage
10-16 21:45:41.087 D/SurfaceUtils( 4787): set up nativeWindow 0xc3a6c808 for 1920x1088, color 0x11, rotation 0, usage 0x402b00
10-16 21:45:41.087 D/OmxVideoDecoder( 3332): setParameter 951 0x2000001
10-16 21:45:41.087 W/OmxVideoDecoder( 3332): 4kosd set output error, newBufferCount 10 > 6
10-16 21:45:41.087 E/OMXNodeInstance( 3332): setParameter(0xe6803bac:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
10-16 21:45:41.087 W/ACodec  ( 4787): [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 10 failed: -1010
10-16 21:45:41.087 D/OmxVideoDecoder( 3332): setParameter 951 0x2000001
10-16 21:45:41.087 W/OmxVideoDecoder( 3332): 4kosd set output error, newBufferCount 9 > 6
10-16 21:45:41.087 E/OMXNodeInstance( 3332): setParameter(0xe6803bac:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
10-16 21:45:41.088 W/MediaCodec_loop( 4787): type=1400 audit(0.0:51): avc: denied { read } for name="u:object_r:media_prop:s0" dev="tmpfs" ino=299 scontext=u:r:untrusted_app:s0:c53,c256,c512,c768 tcontext=u:object_r:media_prop:s0 tclass=file permissive=0
10-16 21:45:41.088 W/ACodec  ( 4787): [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 9 failed: -1010
10-16 21:45:41.088 D/OmxVideoDecoder( 3332): setParameter 951 0x2000001
10-16 21:45:41.088 W/OmxVideoDecoder( 3332): 4kosd set output error, newBufferCount 8 > 6
10-16 21:45:41.088 E/OMXNodeInstance( 3332): setParameter(0xe6803bac:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
10-16 21:45:41.088 W/ACodec  ( 4787): [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
10-16 21:45:41.089 D/OmxVideoDecoder( 3332): setParameter 951 0x2000001
10-16 21:45:41.089 W/OmxVideoDecoder( 3332): 4kosd set output error, newBufferCount 7 > 6
10-16 21:45:41.089 E/OMXNodeInstance( 3332): setParameter(0xe6803bac:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
10-16 21:45:41.089 W/ACodec  ( 4787): [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
10-16 21:45:41.089 E/ACodec  ( 4787): Failed to allocate buffers after transitioning to IDLE state (error 0xfffffc0e)
10-16 21:45:41.089 E/ACodec  ( 4787): signalError(omxError 0x80001001, internalError -1010)
10-16 21:45:41.089 E/MediaCodec( 4787): Codec reported err 0xfffffc0e, actionCode 0, while in state 5
10-16 21:45:41.089 I/OmxComponent( 3332): OMX_CommandStateSet 740 Cmd 0 nParam1 0x1
10-16 21:45:41.089 E/libc    ( 4787): Access denied finding property "media.metrics.enabled"
10-16 21:45:41.089 I/OmxComponent( 3332): STATE_SET:   OMX_StateLoaded => OMX_StateLoaded : OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.090 D/SurfaceUtils( 4787): disconnecting from surface 0xc3a6c808, reason disconnectFromSurface
10-16 21:45:41.090 I/OmxComponent( 3332): STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.091 I/OmxComponent( 3332): STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.091 W/AHierarchicalStateMachine( 4787): Warning message AMessage(what = 'omxI') = {
10-16 21:45:41.091 W/AHierarchicalStateMachine( 4787):   int32_t type = 0
10-16 21:45:41.091 W/AHierarchicalStateMachine( 4787):   int32_t event = 0
10-16 21:45:41.091 W/AHierarchicalStateMachine( 4787):   int32_t data1 = 0
10-16 21:45:41.091 W/AHierarchicalStateMachine( 4787):   int32_t data2 = 1
10-16 21:45:41.091 W/AHierarchicalStateMachine( 4787): } unhandled in root state.
10-16 21:45:41.091 I/OmxComponent( 3332): STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.092 E/cr_MediaCodecBridge( 4787): Cannot start the media codec
10-16 21:45:41.092 E/cr_MediaCodecBridge( 4787): android.media.MediaCodec$CodecException: start failed
10-16 21:45:41.092 E/cr_MediaCodecBridge( 4787): 	at android.media.MediaCodec.native_start(Native Method)
10-16 21:45:41.092 E/cr_MediaCodecBridge( 4787): 	at android.media.MediaCodec.start(MediaCodec.java:2068)
10-16 21:45:41.092 E/cr_MediaCodecBridge( 4787): 	at org.chromium.media.MediaCodecBridge.e(chromium-ChromeModernPublic.aab-stable-460605610:7)
10-16 21:45:41.092 E/cr_MediaCodecBridge( 4787): 	at org.chromium.media.MediaCodecBridgeBuilder.createVideoDecoder(chromium-ChromeModernPublic.aab-stable-460605610:7)
10-16 21:45:41.092 W/cr_MediaCodecBridge( 4787): Releasing: OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.093 D/OmxComponentManagerImpl( 3332): DecreaseEntryNumByName pEntry->mNum=1, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
10-16 21:45:41.093 I/omx_core( 3332): OMX_freeHandle_num_= 0
10-16 21:45:41.093 D/AmlogicVideoDecoderAwesome( 3332): ~AmlogicVideoDecoderAwesome
10-16 21:45:41.093 D/AmlogicVideoDecoderAwesome( 3332): ~AmlogicVideoDecoder
10-16 21:45:41.093 D/AmlogicVideoDecoderAwesome( 3332): ~AmlogicVideoDecoder, mOmxInstancenum 0
10-16 21:45:41.095 W/cr_MediaCodecBridge( 4787): Codec released

**Comment by d3ward** [comment]
I know it's been a while, if you're still using Kiwi, it's been updated so much since this issue was created. I'm closing this as I'm not sure how to test this, if you do and the problem persists feel free to reopen the issue.
