### ISSUE TITLE
uBlock Origin does not work in Private Window

### ISSUE THREAD

**Issue by dfg147** [kiwibrowser/src.next#416]
**Describe the bug**
uBlock Origin does not work in a private window, even though I have allowed it to run in a private window.

**To Reproduce**
Open a private window with uBlock Origin running and open a site that displays ads.

**Expected behavior**
Ads will be removed even in private windows.

**Smartphone (please complete the following information):**
 - Device: SM-G7810
 - Android Version : A11 
 - Kiwi Browser Version  94.0.4606.56

**Additional context**
With a private window open (with ads displayed), open the uBlock Origin extension management screen in a normal window, toggle one of the switches (for example, the Allow file URL access button), and then return to the private window. uBlock Origin will function and the ads will disappear.
In order to use uBlock Origin in a private window, I have to open the extension's administration page every time I open a private window.
By the way, the other extensions work fine in Private Window.

**Comment by dfg147** [comment]
Note: The same symptoms occur in PDF Viewer(https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm). There may be other extensions with similar symptoms.

**Comment by Delphox** [comment]
Fixed in latest GH version! 😀
