### ISSUE TITLE
Not pure black night  mode

### ISSUE THREAD

**Issue by b1ackfa1c0n** [kiwibrowser/src.next#42]
All the browser menus and webpages in next version not in pure black while using night mode like the old version using the same contract in accessibility settings.

Night mode in both browsers compared to each other,

Old version:
![Polish_20210712_183116276](https://user-images.githubusercontent.com/66196864/125324014-20a88e80-e348-11eb-9cea-d45746ec8cc2.jpg)

Next version:
![Polish_20210712_183308164](https://user-images.githubusercontent.com/66196864/125324104-39b13f80-e348-11eb-8b92-ecab8122b738.jpg)

**Comment by d3ward** [comment]
Night mode has been fixed . 
For the UI pure black , we have to wait for the implementation of dark theme .
Im gonna close the issue , feel free to reopen if need more discussion .
