### ISSUE TITLE
Missing event.dataTransfer.types at ondrop event

### ISSUE THREAD

**Issue by danny0838** [kiwibrowser/src.next#427]
**Describe the bug**
Custom data types for `event.dataTransfer` seems missing at the `ondrop` event, causing web apps dependent on such feature not function.

**To Reproduce**
1. Save below code as an HTML file.
2. Open it in the Kiwi browser.
3. Drag a div element and drop anywhere in the page.
4. Visit the developer console. The message at the `ondrop` event is `['text/plain']`.

```HTML
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>test drag custom data</title>
<style>div { margin: 1em; background-color: red; }</style>
<script>
function onDragStart(event) {
  const elem = event.target;
  event.dataTransfer.setData('application/myapp.items+json', {id: elem.id, time: Date.now()});
  event.dataTransfer.setData('text/plain', elem.id);
  console.warn('ondragstart:', event.dataTransfer.types);
}

function onDragOver(event) {
  event.preventDefault();
}

function onDrop(event) {
  console.warn('ondrop:', event.dataTransfer.types);
}

document.addEventListener('dragstart', onDragStart);
document.addEventListener('dragover', onDragOver);
document.addEventListener('drop', onDrop);
</script>
</head>
<body>
<div id="d1" draggable="true">drag me and drop anywhere</div>
<div id="d2" draggable="true">drag me and drop anywhere</div>
</body>
</html>
```

**Expected behavior**
The message at the `ondrop` event should be `['application/myapp.items+json', 'text/plain']` (order may change). This doesn't happen on Chrome (95.~) and Firefox (93).

**Smartphone:**
 - Device: ZenFone 8
 - Android Version : 11
 - Kiwi Browser Version: 94.0.4606.56

**Comment by d3ward** [comment]
Have you done tests on other browsers, for example on Chrome desktop, or on Chrome Android via ADB?

**Comment by danny0838** [comment]
Chrome Desktop does not have the issue, as above mentioned.

Chrome Android seems to have the same issue (tested on 95.0.4638.74)

Here is a revised version using alert on drop, for easier testing on a mobile browser:

```HTML
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>test drag custom data</title>
<style>div { margin: 1em; background-color: red; }</style>
<script>
var dragStartData;

function onDragStart(event) {
  const elem = event.target;
  event.dataTransfer.setData('application/myapp.items+json', {id: elem.id, time: Date.now()});
  event.dataTransfer.setData('text/plain', elem.id);
  dragStartData = JSON.stringify(event.dataTransfer.types);
}

function onDragOver(event) {
  event.preventDefault();
}

function onDrop(event) {
  dropData = JSON.stringify(event.dataTransfer.types);
  alert(`\
ondragstart: ${dragStartData}
ondrop: ${dropData}`);
}

document.addEventListener('dragstart', onDragStart);
document.addEventListener('dragover', onDragOver);
document.addEventListener('drop', onDrop);
</script>
</head>
<body>
<div id="d1" draggable="true">drag me and drop anywhere</div>
<div id="d2" draggable="true">drag me and drop anywhere</div>
</body>
</html>
```

**Comment by d3ward** [comment]
Thanks for the demo and great job on discovering that bug !

Ok this have nothing to do with Kiwi , i mean it's not a specific Kiwi bug but a chromium. 
And seems that all mobile browsers based on chromium have that bug 
So , better if you open an issue on the https://bugs.chromium.org/p/chromium/issues/list
and once will be fixed, Kiwi will upstream the fix .

**Comment by danny0838** [comment]
Thanks. Reported to the Bug tracker of Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1266859
