### ISSUE TITLE
It will be closed even if the link destination disables all blocks

### ISSUE THREAD

**Issue by nymbee16** [kiwibrowser/src.next#433]
It will be closed even if the link destination disables all blocks

I have reported this bug many times.
It will not be fixed at all.
#251
Do you think the developers know the cause of this bug?

Is anyone familiar with programs that can identify the cause?
Is there anyone other than the developer who can fix it?
If anyone can work with the developer, fix it.

   -Device: [Pixel 5]
   -Android version: [12]
   -Kiwi browser version [95.0.4638.74]

please help me.

**Comment by kiwibrowser** [comment]
I am working on this. Arnaud.
