### ISSUE TITLE
Unable to update to src.next from installed Google Play release (94)

### ISSUE THREAD

**Issue by kkuhle** [kiwibrowser/src.next#435]
**Describe the bug**
When I try to update to https://github.com/kiwibrowser/src.next/releases/tag/1437849131 (95) arm64
 (Tried all on oneplus 6t running android 11) it doesn't work..  I have to uninstall and reinstall (losing tabs and settings).  

Is this expected?

**Comment by samlux04** [comment]
Yes it's expected if you read the release notes. The GitHub release has different signature with play store.

**Comment by gnadelwartz** [comment]
btw. there us a new PS release based on chromium 95

**Comment by kkuhle** [comment]
Thanks, friends.  I updated via the Play Store after restoring backup data from Titanium and it works as expected.
