### ISSUE TITLE
Please do something with the Popup Blocker

### ISSUE THREAD

**Issue by samlux04** [kiwibrowser/src.next#436]
It's not just me who have the same issue. I read it on reddit and play store reviews, many people also experience the same issue. Due to the strict popup blocker or something we can't login to certain website which open a new window to login. Forums, online stores, social plugins etc. Hold on the login link and "open in new windows" also don't work, as mentioned in other issue here.
It's a good browser but we can't use it for daily driver. Please do something about it.
Thanks.

**Comment by DUOLabs333** [comment]
I don't think this is maintained any longer, but can't you disable the pop-up blocker?

**Comment by kiwibrowser** [comment]
No, this is heuristic deeper in the popup blocker (to basically stop the interaction). The main idea is to find a generic rule good enough to allow popup blocking by default (without nagging the user all the time).

There is certainly a better approach than just having google, paypal, klarna, twitter, facebook, disqus, etc allowed

**Comment by DUOLabs333** [comment]
Wait, you're active!

**Comment by kiwibrowser** [comment]
Yes, quite a lot ( https://github.com/kiwibrowser/src.next/actions ) but the repo is a bit out-of-sync while working on the 95 transition.

**Comment by DUOLabs333** [comment]
Oh, that's why i thought this was stale. Yeah, probably should be updated.

**Comment by kiwibrowser** [comment]
Yep, but this popup is still an issue, I'll work a bit on perf+stabilisation this week.

Back to the topic, I guess we need an idea, there is no right and easy answer to the actual issue.
The intention behind this functionality is to get rid of pop-unders (especially when there are video players).
One idea that could work, could be... to check the opacity of the object ? That wouldn't prevent the "play buttons" ?
Another idea that seems relatively easy, could be to allow trigger new windows if the underlying element is an <input type="button"> (that's at least one part of the cases).

**Comment by samlux04** [comment]
> I don't think this is maintained any longer, but can't you disable the pop-up blocker?

Unfortunately the block popup in the setting had no effect at all. It's hard coded as the auhour mentioned above as a feature and no option for user.

**Comment by samlux04** [comment]
Maybe and option to disable the popup blocker would be nice. I think unlock origin is enough to block most overlay ads and click redirect.
I'd love to use kiwi as a daily driver since it's way smoother than Firefox. I've gotten used to Firefox now even with its jittering scrolling.

**Comment by d3ward** [comment]
This is very old and Kiwi has come a long way since then, the built-in adblocker, which includes a popup blocker, is pretty solid and improved. 
So far I have not noticed any problems, plus the new tri-state system allows you to quickly disable it for specific sites if problems arise.
