### ISSUE TITLE
These domains are not correctly displayed

### ISSUE THREAD

**Issue by alleluia20** [kiwibrowser/src.next#437]
Hello,

The domains of the Faculties of this University are not correctly displayed. For example: https://ciencias.unizar.es/, https://econz.unizar.es/, https://fecem.unizar.es/, etc. ​Kiwi only displays the footer, while other browsers (like Opera) display correctly.

Not only does it happen with the homepages of the Faculties, but also with any subpage, for example: https://econz.unizar.es/servicios/reprografia

Regards.

**Comment by gnadelwartz** [comment]
disable "block ads" ...

**Comment by alleluia20** [comment]
Thank you, it worked. But there is a problem with the option to show ads,
so I opened #440.

Regards.

**Comment by gnadelwartz** [comment]
nice, pls consider closing this issue
