### ISSUE TITLE
Impossible to show ads by default

### ISSUE THREAD

**Issue by alleluia20** [kiwibrowser/src.next#440]
Hello,

Given that hiding ads often removes legitimate content (many false positives), and given that I am using uBlock Origin, I tried to configure ads to be shown by default, enabling it in the site configuration in settings.

The problem is that, basically, this option is buggy, and it does nothing. In my specific case, the first time it worked, I then chose to hide ads in that specific site (using the menu element) and, from that moment, ads were hidden by default in all sites, unless you add exceptions for ads to be shown, site by site, using the menu.

Regards.

**Comment by d3ward** [comment]
I know it's been a while but with latest Kiwi v116 this is not an issue anymore
