### ISSUE TITLE
No support for backup and restore 

### ISSUE THREAD

**Issue by 1Mark** [kiwibrowser/src.next#449]
**Describe the bug**
After using a Google account to restore a backup of a device. If you have shortcuts created via "Add to homescreen" they won't work after the restore.

**To Reproduce**
Open kiwi browser and visit any webpage.
Press the three dots and select "Add to homescreen"
Ensure your device is backed up to Google e.g use Google one app or settings.
Then on a factory reset device (or new) restore the backup via your Google account.
All icons should restore but shortcuts created via kiwi browser won't open - a prompt is shown saying "Couldn't restore shortcut because app doesn't support backup and restore". These shortcuts are also greyed out.

**Expected behavior**
Shortcut is restored and can be used 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2XL backed up then restored onto Google Pixel 6
 - Android Version : 12
 - Kiwi Browser Version  96.0.4664.46

**Additional context**
If you cannot remember the URL of these shortcuts you can no longer access them which is quite annoying.

**Comment by 1Mark** [comment]
To be honest, I think, this is more of a side effect, this bug as I phrased it above isn't that important. But what's important is to support backup and restore so when you change your device you don't lose your history+ bookmarks etc (I know bookmarks can be exported but who's going to remember to do that...).

**Comment by d3ward** [comment]
Closing and linking this to #122
