### ISSUE TITLE
Toolbar coloring

### ISSUE THREAD

**Issue by C-O-D** [kiwibrowser/src.next#454]
How can I disable the automatic toolbar coloring that occurred since the last couple of versions?
I don't like to have a pink, green or white toolbar, especially not when using the DarkReader extension...

**Comment by karl-pae** [comment]
Turning on dark theme. Turns your toolbar into black-grey. The toolbar color isn't affected while using dark theme.

**Comment by C-O-D** [comment]
Thanks for the mti tip, @karl-pae
I'm using dark theme all the time in Kiwi and also on my phone, but I'm still getting a colored toolbar - but this didn't happen a few versions ago.
Well, I'll try the mti extension...

**Comment by kiwibrowser** [comment]
Looks like a bug yes, working on a fix today

**Comment by kiwibrowser** [comment]
Thank you very much for spotting the issue!
This was clearly not intended, and is now resolved in the upcoming build.

**Comment by C-O-D** [comment]
Wow, thanks a lot for looking after!
