### ISSUE TITLE
Toolbar setting always on screen does not work

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src.next#458]
**Describe the bug**
When I turn on "toolbar always on screen", it doesn't seem to work. Please watch the video.

**Screenshots**
Please watch the video.If can't watch online.You can download it.

https://user-images.githubusercontent.com/55195642/146634170-3fcb376e-ecc2-4ab3-91c8-0c0dd1f560b3.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 7]:honor
 - Android Version : [e.g. A11 ]A10
 - Kiwi Browser Version [ e.g. 90.0.4577.17 ]Generation 1595223238,98.0.4758.14

**Additional context**

**Comment by karl-pae** [comment]
https://github.com/kiwibrowser/src.next/releases/tag/1598596904

The above release has solved the issue for me. 

Close the issue, if problem has been solved.

**Comment by kiwibrowser** [comment]
Thank you @karl-pae 

Yes I fixed the issue in the latest build
