### ISSUE TITLE
Forced Close after opening an offline page file (mhtml)

### ISSUE THREAD

**Issue by ExAnchoR** [kiwibrowser/src.next#461]
**Describe the bug**
kiwi browser crashes whenever I open an offline page file(mhtml) through a file explorer. I thought it was the file itself makes the browser crash but when I entered "file:///" in the omnibox it crashed the browser.

**To Reproduce**
Open an offline page file(mhtml) through file explorer/manager. I used FX version 7.1.0.0

**Expected behavior**
Open the offline page normally like how you open a offline page in the downloads(in browser).

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Sharp Aquos SHV38
 - Android Version : 8.0.0
 - Kiwi Browser Version 98.0.4758.14 (1607585358)

**Additional context**

**Comment by kiwibrowser** [comment]
I managed to reproduce the issue. I will do a fix, it affects all file:/// apparently.

**Comment by ExAnchoR** [comment]
I'm really in great trouble right now because I accidentally opened the file with kiwi instead of the temporary alt browser and it forced closed before I removed the tab. Now I can't open kiwi Browser, it keeps crashing whenever i open the browser and the worst I can't clear it's data because I have bookmarks in it.

**Comment by kiwibrowser** [comment]
Ok don't panic, I'm preparing a fix right now

**Comment by kiwibrowser** [comment]
Captured the stacktrace, I'll prepare a new build, it'll take about 30 minutes.
```
Stack Trace:
  RELADDR   FUNCTION                                                                          FILE:LINE
  v------>  base::SequencedTaskRunnerHandle::Get()::$_0::operator()() const                   ../../base/threading/sequenced_task_runner_handle.cc:26:3
  v------>  base::SequencedTaskRunnerHandle::Get()                                            ../../base/threading/sequenced_task_runner_handle.cc:26:3
  038e37ea  mojo::internal::GetTaskRunnerToUseFromUserProvidedTaskRunner(scoped_refptr<base::SequencedTaskRunner>)  ../../mojo/public/cpp/bindings/lib/task_runner_helper.cc:18:10
  031eb521  mojo::internal::BindingStateBase::BindInternal(mojo::internal::PendingReceiverState*, scoped_refptr<base::SequencedTaskRunner>, char const*, std::__1::unique_ptr<mojo::MessageReceiver, std::__1::default_delete<mojo::MessageReceiver> >, bool, bool, mojo::MessageReceiverWithResponderStatus*, unsigned int)  ../../mojo/public/cpp/bindings/lib/binding_state.cc:117:7
  02e5f613  mojo::internal::BindingState<network::mojom::URLLoader, mojo::RawPtrImplRefTraits<network::mojom::URLLoader> >::Bind(mojo::internal::PendingReceiverState*, scoped_refptr<base::SequencedTaskRunner>)  ../../mojo/public/cpp/bindings/lib/binding_state.h:120:23
  01a6675f  mojo::Receiver<network::mojom::URLLoader, mojo::RawPtrImplRefTraits<network::mojom::URLLoader> >::Bind(mojo::PendingReceiver<network::mojom::URLLoader>)  ../../mojo/public/cpp/bindings/receiver.h:161:5
  v------>  content::(anonymous namespace)::FileURLDirectoryLoader::Start(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>)  ../../content/browser/loader/file_url_loader_factory.cc:194:15
  01b03427  content::(anonymous namespace)::FileURLDirectoryLoader::CreateAndStart(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>)  ../../content/browser/loader/file_url_loader_factory.cc:164:22
  v------>  void base::internal::FunctorTraits<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), void>::Invoke<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>(void (*&&)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath&&, network::ResourceRequest&&, network::mojom::FetchResponseType&&, mojo::PendingReceiver<network::mojom::URLLoader>&&, mojo::PendingRemote<network::mojom::URLLoaderClient>&&, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >&&, std::nullptr_t&&)  ../../base/bind_internal.h:430:12
  v------>  void base::internal::InvokeHelper<false, void>::MakeItSo<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>(void (*&&)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath&&, network::ResourceRequest&&, network::mojom::FetchResponseType&&, mojo::PendingReceiver<network::mojom::URLLoader>&&, mojo::PendingRemote<network::mojom::URLLoaderClient>&&, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >&&, std::nullptr_t&&)  ../../base/bind_internal.h:699:12
  v------>  void base::internal::Invoker<base::internal::BindState<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>, void ()>::RunImpl<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), std::__1::tuple<base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>, 0u, 1u, 2u, 3u, 4u, 5u, 6u>(void (*&&)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), std::__1::tuple<base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>&&, std::__1::integer_sequence<unsigned int, 0u, 1u, 2u, 3u, 4u, 5u, 6u>)  ../../base/bind_internal.h:772:12
  01b04c5b  base::internal::Invoker<base::internal::BindState<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>, void ()>::RunOnce(base::internal::BindStateBase*)  ../../base/bind_internal.h:741:12
  v------>  base::OnceCallback<void ()>::Run() &&                                             ../../base/callback.h:142:12
  02e763bb  base::TaskAnnotator::RunTaskImpl(base::PendingTask&)                              ../../base/task/common/task_annotator.cc:135:32
  v------>  void base::TaskAnnotator::RunTask<base::internal::TaskTracker::RunTaskImpl(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&)::$_0>(perfetto::StaticString, base::PendingTask&, base::internal::TaskTracker::RunTaskImpl(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&)::$_0&&)  ../../base/task/common/task_annotator.h:74:5
  v------>  base::internal::TaskTracker::RunTaskImpl(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&)  ../../base/task/thread_pool/task_tracker.cc:706:19
  02e75f9f  base::internal::TaskTracker::RunSkipOnShutdown(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&)  ../../base/task/thread_pool/task_tracker.cc:691:3
  v------>  base::internal::TaskTracker::RunTaskWithShutdownBehavior(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&)  ../../base/task/thread_pool/task_tracker.cc:721:7
  02eef5d7  base::internal::TaskTracker::RunTask(base::internal::Task, base::internal::TaskSource*, base::TaskTraits const&)  ../../base/task/thread_pool/task_tracker.cc:548:5
  02eef3e3  base::internal::TaskTrackerPosix::RunTask(base::internal::Task, base::internal::TaskSource*, base::TaskTraits const&)  ../../base/task/thread_pool/task_tracker_posix.cc:22:16
  025a29d7  base::internal::TaskTracker::RunAndPopNextTask(base::internal::RegisteredTaskSource)  ../../base/task/thread_pool/task_tracker.cc:466:5
  034f7457  base::internal::WorkerThread::RunWorker()                                         ../../base/task/thread_pool/worker_thread.cc:379:34
  034f72c1  base::internal::WorkerThread::RunPooledWorker()                                   ../../base/task/thread_pool/worker_thread.cc:266:3
  025b1b4b  base::(anonymous namespace)::ThreadFunc(void*)                                    ../../base/threading/platform_thread_posix.cc:98:13
  0008171b  __pthread_start(void*)+40) (BuildId: 874b389553085fd9899c55432f97d751             /apex/com.android.runtime/lib/bionic/libc.so
  0003a3ed  __start_thread+30) (BuildId: 874b389553085fd9899c55432f97d751                     /apex/com.android.runtime/lib/bionic/libc.so
```

**Comment by ExAnchoR** [comment]
> Ok don't panic, I'm preparing a fix right now

Okay!, Thank you so much. I'll wait for the update.

**Comment by kiwibrowser** [comment]
The fix is ready and tested, it's now building all the different APKs, I'll let you know once it's ready (I guess 20 minutes).

**Comment by ExAnchoR** [comment]
> Captured the stacktrace, I'll prepare a new build, it'll take about 30 minutes.
> 
> ```
> Stack Trace:
>   RELADDR   FUNCTION                                                                          FILE:LINE
>   v------>  base::SequencedTaskRunnerHandle::Get()::$_0::operator()() const                   ../../base/threading/sequenced_task_runner_handle.cc:26:3
>   v------>  base::SequencedTaskRunnerHandle::Get()                                            ../../base/threading/sequenced_task_runner_handle.cc:26:3
>   038e37ea  mojo::internal::GetTaskRunnerToUseFromUserProvidedTaskRunner(scoped_refptr<base::SequencedTaskRunner>)  ../../mojo/public/cpp/bindings/lib/task_runner_helper.cc:18:10
>   031eb521  mojo::internal::BindingStateBase::BindInternal(mojo::internal::PendingReceiverState*, scoped_refptr<base::SequencedTaskRunner>, char const*, std::__1::unique_ptr<mojo::MessageReceiver, std::__1::default_delete<mojo::MessageReceiver> >, bool, bool, mojo::MessageReceiverWithResponderStatus*, unsigned int)  ../../mojo/public/cpp/bindings/lib/binding_state.cc:117:7
>   02e5f613  mojo::internal::BindingState<network::mojom::URLLoader, mojo::RawPtrImplRefTraits<network::mojom::URLLoader> >::Bind(mojo::internal::PendingReceiverState*, scoped_refptr<base::SequencedTaskRunner>)  ../../mojo/public/cpp/bindings/lib/binding_state.h:120:23
>   01a6675f  mojo::Receiver<network::mojom::URLLoader, mojo::RawPtrImplRefTraits<network::mojom::URLLoader> >::Bind(mojo::PendingReceiver<network::mojom::URLLoader>)  ../../mojo/public/cpp/bindings/receiver.h:161:5
>   v------>  content::(anonymous namespace)::FileURLDirectoryLoader::Start(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>)  ../../content/browser/loader/file_url_loader_factory.cc:194:15
>   01b03427  content::(anonymous namespace)::FileURLDirectoryLoader::CreateAndStart(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>)  ../../content/browser/loader/file_url_loader_factory.cc:164:22
>   v------>  void base::internal::FunctorTraits<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), void>::Invoke<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>(void (*&&)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath&&, network::ResourceRequest&&, network::mojom::FetchResponseType&&, mojo::PendingReceiver<network::mojom::URLLoader>&&, mojo::PendingRemote<network::mojom::URLLoaderClient>&&, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >&&, std::nullptr_t&&)  ../../base/bind_internal.h:430:12
>   v------>  void base::internal::InvokeHelper<false, void>::MakeItSo<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>(void (*&&)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath&&, network::ResourceRequest&&, network::mojom::FetchResponseType&&, mojo::PendingReceiver<network::mojom::URLLoader>&&, mojo::PendingRemote<network::mojom::URLLoaderClient>&&, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >&&, std::nullptr_t&&)  ../../base/bind_internal.h:699:12
>   v------>  void base::internal::Invoker<base::internal::BindState<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>, void ()>::RunImpl<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), std::__1::tuple<base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>, 0u, 1u, 2u, 3u, 4u, 5u, 6u>(void (*&&)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), std::__1::tuple<base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>&&, std::__1::integer_sequence<unsigned int, 0u, 1u, 2u, 3u, 4u, 5u, 6u>)  ../../base/bind_internal.h:772:12
>   01b04c5b  base::internal::Invoker<base::internal::BindState<void (*)(base::FilePath const&, network::ResourceRequest const&, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, scoped_refptr<net::HttpResponseHeaders>), base::FilePath, network::ResourceRequest, network::mojom::FetchResponseType, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>, std::__1::unique_ptr<content::FileURLLoaderObserver, std::__1::default_delete<content::FileURLLoaderObserver> >, std::nullptr_t>, void ()>::RunOnce(base::internal::BindStateBase*)  ../../base/bind_internal.h:741:12
>   v------>  base::OnceCallback<void ()>::Run() &&                                             ../../base/callback.h:142:12
>   02e763bb  base::TaskAnnotator::RunTaskImpl(base::PendingTask&)                              ../../base/task/common/task_annotator.cc:135:32
>   v------>  void base::TaskAnnotator::RunTask<base::internal::TaskTracker::RunTaskImpl(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&)::$_0>(perfetto::StaticString, base::PendingTask&, base::internal::TaskTracker::RunTaskImpl(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&)::$_0&&)  ../../base/task/common/task_annotator.h:74:5
>   v------>  base::internal::TaskTracker::RunTaskImpl(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&)  ../../base/task/thread_pool/task_tracker.cc:706:19
>   02e75f9f  base::internal::TaskTracker::RunSkipOnShutdown(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&)  ../../base/task/thread_pool/task_tracker.cc:691:3
>   v------>  base::internal::TaskTracker::RunTaskWithShutdownBehavior(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&)  ../../base/task/thread_pool/task_tracker.cc:721:7
>   02eef5d7  base::internal::TaskTracker::RunTask(base::internal::Task, base::internal::TaskSource*, base::TaskTraits const&)  ../../base/task/thread_pool/task_tracker.cc:548:5
>   02eef3e3  base::internal::TaskTrackerPosix::RunTask(base::internal::Task, base::internal::TaskSource*, base::TaskTraits const&)  ../../base/task/thread_pool/task_tracker_posix.cc:22:16
>   025a29d7  base::internal::TaskTracker::RunAndPopNextTask(base::internal::RegisteredTaskSource)  ../../base/task/thread_pool/task_tracker.cc:466:5
>   034f7457  base::internal::WorkerThread::RunWorker()                                         ../../base/task/thread_pool/worker_thread.cc:379:34
>   034f72c1  base::internal::WorkerThread::RunPooledWorker()                                   ../../base/task/thread_pool/worker_thread.cc:266:3
>   025b1b4b  base::(anonymous namespace)::ThreadFunc(void*)                                    ../../base/threading/platform_thread_posix.cc:98:13
>   0008171b  __pthread_start(void*)+40) (BuildId: 874b389553085fd9899c55432f97d751             /apex/com.android.runtime/lib/bionic/libc.so
>   0003a3ed  __start_thread+30) (BuildId: 874b389553085fd9899c55432f97d751                     /apex/com.android.runtime/lib/bionic/libc.so
> ```

Okay! I'll wait for it. Thank you so much again! This really saves me.

**Comment by ExAnchoR** [comment]
> The fix is ready and tested, it's now building all the different APKs, I'll let you know once it's ready (I guess 20 minutes).

Okay, Thank you very much.
sorry for the late replies btw.

**Comment by kiwibrowser** [comment]
Ok it should be much better now if you want to try :)

https://github.com/kiwibrowser/src.next/releases/tag/1612134076

**Comment by ExAnchoR** [comment]
> Ok it should be much better now if you want to try :)
> 
> https://github.com/kiwibrowser/src.next/releases/tag/1612134076

Hello, I've installed it and I'm able to open kiwi again! it's working now! Thank you so much for fixing it!!

**Comment by kiwibrowser** [comment]
Thank you for spotting the issue and confirming it's now working again :)
