### ISSUE TITLE
tabs switch

### ISSUE THREAD

**Issue by Frozen-hc** [kiwibrowser/src.next#463]
On tablets, when there are too many tabs, some of them won't show up, so why not make a vertical tab like Edge or a tab button that follows the addEress bar like on mobile?![Screenshot_20211229_013106_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/55055205/147592208-399a7ea3-6784-4938-ae7a-fb9b2202bbe9.jpg)

**Comment by CanYouJustWorkPlease** [comment]
I've seen the same issue with Chrome on desktop, so it must be an issue with Chromium.

**Comment by d3ward** [comment]
Issue has been fixed with latest Kiwi v116
