### ISSUE TITLE
Happy New Year 🎆 🎉 2022

### ISSUE THREAD

**Issue by karl-pae** [kiwibrowser/src.next#465]
Thank you Kiwi Browser and team for your continued support. Keeping us safe on the internet. 👍

Users, You can comment "the gratitude" in this issue (I hope so, lol) 😁

**Comment by kyoyacchi** [comment]
Haksız yere ban attığınız discord banımı açın önce.

**Comment by kiwibrowser** [comment]
Hey, happy new year to you too @karl-pae  :)
