### ISSUE TITLE
Kiwi Browser crashes after `chrome://help` is opened

### ISSUE THREAD

**Issue by cbwee** [kiwibrowser/src.next#467]
**Describe the bug**
After opening the `chrome://help` page, the browser crashes.

**To Reproduce**
Open Kiwi Browser, in a new tab 
(it is better to test this in private mode, because in the normal mode the browser would keep crashing) 
open the page `chrome://help`, and the browser will crash.

**Expected behavior**
The browser should not crash.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 9T and Windows Subsystem for Android
 - Android Version : Android 11 and Windows 11 (Android 11 in WSA)
 - Kiwi Browser Version 98.0.4758.29 (arm64-v8a and x86_64)

**Comment by Delphox** [comment]
Fixed on latest build!

**Comment by kiwibrowser** [comment]
Thank you @Delphox for the help capturing the backtrace as well!
