### ISSUE TITLE
less smoother than old kivi

### ISSUE THREAD

**Issue by Hellodogfang** [kiwibrowser/src.next#49]
Kiwi next version is less smoother than the old one at the moment. 
Hope the final version will solve this problem. 
Thanks for your hard work.

**Comment by gitdebpro** [comment]
> Kiwi next version is less smoother than the old one at the moment. 
> Hope the final version will solve this problem. 
> Thanks for your hard work.

yeah but it's fast as rocket which the old one is not definitely it will improve just give it sometime.

**Comment by kiwibrowser** [comment]
Thanks a lot for the confirmation @kryptobolt200528 as I was worried if this was fixed or not
