### ISSUE TITLE
No website content visible

### ISSUE THREAD

**Issue by eliba** [kiwibrowser/src.next#496]
**Describe the bug**
Webpages get shown in a plain white-on-white with nothing visible. It seems pages get loaded and it it also possible to highlight text, but neither the text or the highlight is visible. Also in the tab-switcher websites are not visible but plain white. Settings and other bulit-in menues work as expected.

This happened after the update to the latest version available in the Play Store.

**To Reproduce**
* Install Kiwi Browser
* Open any website

**Expected behavior**
Websites should display normal

**Screenshots**
![Screenshot_20220131-223306](https://user-images.githubusercontent.com/12097093/151877853-b0f1ce89-6989-4e66-8be9-fbb3c2510a90.png)
(This is my "New Tab" page, some `chrome://` page I can't recall the name of. It should show the favicons of different websites)
![Screenshot_20220131-223256](https://user-images.githubusercontent.com/12097093/151877856-f80d3cce-6f03-4140-ae8c-ae3683250ba1.png)
![Screenshot_20220131-223653](https://user-images.githubusercontent.com/12097093/151878115-f4a2d679-79bc-4659-8931-ba5dc4657483.png)
(The grey horizontal bar is only specific for GitHub sites)

**Smartphone (please complete the following information):**
 - Device: Fairphone 2
 - Android Version : Android 9 (Fairphone OpenOS without Google Play Services)
 - Kiwi Browser Version 90.0.4758.66

**Additional context**
Thank you very much for developing this awesome browser! I just realized how much I actually depend on it on my phone.

Someone on reddit seems to have the same problem: https://www.reddit.com/r/kiwibrowser/comments/sdns18/i_cant_use_kiwi_browser_at_all_now_help_me_ive/

**Comment by kiwibrowser** [comment]
This is a serious issue :/
I'll try a rebase and see if it disappears, because if it appeared recently I guess it is caused by a dependency :(

Very cool to see a Fairphone in real-life as well!

My intuition is that it is cause by the Zero copy flag, I'll disable it.

**Comment by eliba** [comment]
Hey, thank you very much for the fast response and fix!
It is working again with version `Kiwi Browser 98.0.4758.89` :)

**Comment by kiwibrowser** [comment]
Thank you for confirming that the issue was resolved.
Yes, unfortunately this was the Zero copy flag (this is a special configuration where the tiles = graphics are transferred directly from the GPU without any extra copy in memory. However, sometimes as you can see, actually copying the data would be better than doing nothing :D
