### ISSUE TITLE
In the next version, the new tab view cannot be collapsed when sliding. 

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src.next#5]
In the next version, the new tab view cannot be collapsed when sliding. Figure 1 shows the next version, and Figure 2 shows the previous version.
Obviously, the experience in Figure 1 is not as good as that in Figure 2.

![Screenshot_20210701_182819_com kiwibrowser browse](https://user-images.githubusercontent.com/55195642/124110398-c03d6580-da9a-11eb-8ffb-ba9f64040f07.jpg)
![Screenshot_20210701_182852_com kiwibrowser browse](https://user-images.githubusercontent.com/55195642/124110409-c3d0ec80-da9a-11eb-8286-b61cda193268.jpg)

**Comment by Delphox** [comment]
Check latest version! 😀

**Comment by drc5521** [comment]
> Check latest version! 😀

YEAH! I have switched to original.  Thank you very much.
