### ISSUE TITLE
Clicking on the hashtag doesn't work.

### ISSUE THREAD

**Issue by nymbee16** [kiwibrowser/src.next#50]
http://momoclonews.com/archives/55918964.html

Clicking on the hashtag doesn't work.
(blue text)

・Kiwi Browser "next" (src.next) ＝ NG
・It works with Kiwi Browser "classic" (src). ＝ OK

**Comment by nymbee16** [comment]
https://momoclo.antenam.info/

Most of the links from the hashtags within each item on this site are not working.

It does not respond when clicked and does not move to the link.

There is no problem with Browser "classic" (src).
When I click on a hashtag, it reacts and moves.

I think it's a bug in kiwibrowser "next"(src.next).

I hope this will be fixed soon.

**Comment by nymbee16** [comment]
Hello
Is this a bug?
Or did the method of opening links such as hashtags change due to the specification change?
I am in trouble because there is no answer.
It seems that some Japanese users have confirmed the same problem.
I would like to know the view of kiwibrowser.
Thank you.

**Comment by d3ward** [comment]
Hello , it seems to work fine for me with latest builds .

**Comment by nymbee16** [comment]
Thank you
However, in my environment, clicking the hashtag does not open the link. 

If you press and hold the hashtag, the menu list will be displayed,
Select the item you want to open from the menu list to open the link.
Has it been changed to such a specification?

Either because the change history is not public I do not know what the correct behavior from. 

This is my current environment.
I haven't installed the extension. 

Kiwi Browser 93.0.4577.9
Generation 1058408432
com.kiwibrowser.browser-1058408432-arm64-github.apk

Google Pixel 5 Bild：RQ3A.210705.001
OS：Android 11

Sorry for the incomprehensible English.

**Comment by nymbee16** [comment]
Please fix it so that you can click on the hashtag to open it as before, instead of long-pressing it.

**Comment by d3ward** [comment]
Hey , do you updated to latest ? 
I can click fine on links in the list news

**Comment by nymbee16** [comment]
I am reporting that one click from the hashtag, not the link in the list news, does not open the link.
Here is a report of the problem when clicking on the hashtag.

Click in the red frame of the image.
http://momoclonews.com/archives/55918964.html
One click will not open the link.
Kiwi Browser "classic" (src) = One click opened the link.
next = The link will not open with one click.
Same bug with "kiwi next" on my family's phone.
![Screenshot](https://user-images.githubusercontent.com/87474267/128093805-4b01758e-e047-4ade-87c8-1a82bb31d762.jpg)
Generation 1094737737
com.kiwibrowser.browser-1094737737-arm64-github.apk
Android 11
pixel 5

**Comment by MmyGgithubAaccount** [comment]
@nymbee16 by not working do you mean it doesn't open in the twitter android app or do you mean it doesn't search for the hashtag on twitter.com (inside kiwi browser)? 

The second case (twitter.com inside kiwi browser) works for me. The first case won't work because opening links in external apps is currently broken (#94)

**Comment by kotaro366** [comment]
I am not a contributor.
I don't have an external Twitter app.
I tried the second method.
I one-clicked on the hashtag in the red circle in the tacked-on image.
But it does not respond.
Clicking on it will not open Twitter.com in your Kiwi browser.
I've tried chrome and firefox.
In both cases, a single click on the hashtag will open Twitter.com in your browser.
MmyGgithubAaccount, did you open Twitter in your browser with one click?
What method would that be?
I posted this because I'm getting the same bug as nymbee16.

・Device: AQUOS sense3
・Android Version : Android 10
・Kiwi Browser Version : 93.0.4577.20

**Comment by MmyGgithubAaccount** [comment]
Latest github build of kiwi dev
Android 11
1 tap opens twitter tag search for me
Here's what I'm seeing:

https://user-images.githubusercontent.com/58236619/128218517-63e9c9e6-9ffc-45aa-9178-81d34d680755.mp4

@kotaro366 and @nymbee16 is new kiwi set as your default browser (if no, try setting it as default)? Or do you have any other app that is set to open twitter links by default (if yes, try seeing it to "ask everytime")? Also maybe try seeing system and kiwi language to English. Might be done weird language specific bug

**Comment by kotaro366** [comment]
I have Kiwi set as my default browser.
The system and Kiwi do not respond when I set their language to English.
I usually use Japanese.

**Comment by kotaro366** [comment]
@MmyGgithubAaccount
Do you one-click the hashtag after the entire page has fully loaded as well as the image?
In my environment, one click does not respond after the entire page has fully loaded.
If the page is in the process of being fully loaded, the link opens with one click.
Isn't it a bug that one click on a hashtag after it is fully loaded will not respond?
Chrome and Firefox will open the link with a single click of the hashtag, even after it is fully loaded.

**Comment by MmyGgithubAaccount** [comment]
@kotaro366 for me the hashtags work even when the page has fully loaded

**Comment by kotaro366** [comment]
I have an AQUOS sense3 and a PIXEL5.　
I reset both units to factory defaults and gave it a try.
I installed and tested only the Kiwi Browser.
The result was the same.
One click on the hashtag did not take me to the link.
I get the same symptoms with both.
What could be the cause?

**Comment by kotaro366** [comment]
@kiwibrowser
Can Kiwibrowser confirm this symptom?
I always click the hashtag to open the link.
It has become very inconvenient because it no longer opens when I click on it.
Please correct it.

**Comment by nymbee16** [comment]
@kiwibrowser

One click on the hashtag of the reporting site does not open the link.
Are you aware of this bug?
Some people seem to have no problem opening it.
I initialized my smartphone and installed only the Kiwi Browser to try it out.
But I can't open the link with a single click of hashtag.
I also initialized and tested a family member's smartphone, Google Pixel 5.
But one click on the hashtag doesn't open it.
The reason why some people can open it and others can't is that there must be a bug in some detail.
Can you reproduce this bug?
There is definitely a bug hidden in there somewhere.
(KiwiBrowserNext), I can't open the hashtag with one click anymore.
Isn't it compatible with smartphones made by Google?
