### ISSUE TITLE
Question Regarding Default Home Screen...

### ISSUE THREAD

**Issue by Ibuprophen** [kiwibrowser/src.next#503]
Is there a way for you to add a feature to have the Bookmarks as the default page when all the tabs are closed?

I can't even go to the bookmarks (or others) when all the tabs are closed. I have to open a new blank tab to access those options in the menu.

It's not a big deal and I only use the Android version of the browser at the moment.

Thanks a Bunch! :-)

~Ibuprophen

**Comment by lyk82468246** [comment]
Try chrome://bookmarks/ ?

**Comment by Ibuprophen** [comment]
Thanks for the response, but I may have to clarify a bit more... 

I meant that if all the tabs are closed, I'm unable to navigate the options in the main menu unless I have a tab open. 

I'd like to ask if there's a way that the ability to navigate all the options in the main menu without having to have a new tab (in general) open. 

I hope I had clarified this better via text... :-) 


~Ibuprophen

**Comment by karl-pae** [comment]
> I meant that if all the tabs are closed, I'm unable to navigate the options in the main menu unless I have a tab open. 

That's not possible, in any browser.

**Comment by Ibuprophen** [comment]
It's possible in Firefox & other Mozilla based browsers (only the few I use/used as I can't state this for every single one of them). 


~Ibuprophen

**Comment by karl-pae** [comment]
I don't know what you are talking about. Even desktop browsers needs to keep at least one tab open..

**Comment by karl-pae** [comment]
Hi, alternative solution is you can sideload this extension by @Delphox 

It will automatically create a new tab as soon as all tabs are closed.

https://github.com/Delphox/AlwaysHaveTab/releases/tag/1.4

**Comment by Ibuprophen** [comment]
I just grabbed it and am following it in Github. I'll give it a day or so and report back. 

Just curious as to any real difference between the non classic and classic ones? 

I'm fairly new to the Chrome browsers since Kiwi is the first one I've used and like. I've been a long time user of the Mozilla browsers. 

~Ibuprophen

**Comment by karl-pae** [comment]
Although it's already mentioned above. 

It's the Kiwi browser homepage settings. 

You can give it a try from kiwi settings > homepage.

![Screenshot_20220316-000028~2.jpg](https://user-images.githubusercontent.com/83178186/158447337-90cbedd2-7dfd-45f9-97e3-890c658e493e.jpg)

If you prefer modern homepage go for non classic.. 

or classic page, classic.

**Comment by Ibuprophen** [comment]
Awesome! 

Thank you very much for your time, patience and guidance. It works great! :-)) 


~Ibuprophen
