### ISSUE TITLE
Uri bar paddock/site info missing

### ISSUE THREAD

**Issue by fredgolightly** [kiwibrowser/src.next#507]
I've just noticed after the latest Play Store update that the padlock icon on the address bar is missing. I assume this is a Chrome change not Kiwi, but it makes it impossible to clear data/cookies for the site and see site info. Can this be returned?

Edit: again, as per another issue where the extensions didn't show in the menu if put first on large tablet screens this appears only on my Tab S7 tablet

**Comment by Pokerkoffer** [comment]
I can confirm that. The icon is gone, see attached screenshot. (Samsung Galaxy Tab S7+, latest Kiwi Playstore Version)

![image](https://user-images.githubusercontent.com/770369/159555833-f606646d-1d20-48e5-aab8-3cd8d7b0223d.png)

**Comment by Pokerkoffer** [comment]
@fredgolightly Can you add the "Bug" label, to increase the visibility of this issue?
