### ISSUE TITLE
Groups Tab Option

### ISSUE THREAD

**Issue by NAVEEDNOORKHAN** [kiwibrowser/src.next#51]
Kindly don't add groups tab option in Kiwi Browser by default because latest chrome using Groups Tab by default even we can't change or remove in settings, It's very annoying, Kindly make update but we recommend you to add everything optional like a perfect application.
User can change everything on demand. One more request please add a custom color picker bar in theme section for making full ui colorful like we can select any color for kiwi browser instead of white and black theme. Everyone will like these perfect features and i want to make Kiwi Browser Always as a perfect adfree browser 💕. Thanks

**Comment by d3ward** [comment]
You can change to other Tab Switcher layouts , including old vertical/horizontal from previous Kiwi

**Comment by kiwibrowser** [comment]
Hello,

Yes, Kiwi listened, offers the possibility to switch to an old-school tabswitcher :)

**Comment by kiwibrowser** [comment]
Regarding browser color, you can customize it using https://github.com/d3ward/mti
