### ISSUE TITLE
Adding Twitter url to new tab homepage doesn't load icon

### ISSUE THREAD

**Issue by fredgolightly** [kiwibrowser/src.next#511]
Adding a twitter url ie https://mobile.twitter.com/explore to a new position via the '+' on the new tabe homepage results in a loading/spiral animation and not the site icon
![Screenshot_20220217-100123~2](https://user-images.githubusercontent.com/29231130/154452594-40229258-5039-4ed8-8e50-95a60bc36d66.png)

**Expected behavior**
Load the site favicon like it does all other sites.

**Screenshots**

Samsung Tab S7 + Pixel 5
Android 12
 - 98.0.4758.106

**Comment by karl-pae** [comment]
Hi, download the latest build from here:
https://github.com/kiwibrowser/src.next/releases

and revert if the issue still occurs, else you can close this issue. Additionally, you can try clearing the cache. 

In my case, I get the icon.
