### ISSUE TITLE
Bottom Toolbar setting missing on tablet

### ISSUE THREAD

**Issue by fredgolightly** [kiwibrowser/src.next#513]
Perhaps by design, but on my tablet (but no on my phone) the option to move the toolbar to the bottom is missing in settings

Samsung Tab S7
Android 12

98.0.4758.106

**Comment by gnadelwartz** [comment]
Th8s setting 8s only for phones as 9n tablets the tabbed toolbar is use, not the mobile toolbar. If it's a feature request you should change the bug label to feature request

**Comment by fredgolightly** [comment]
> This setting is only for phones as on tablets the tabbed toolbar is used, not the mobile toolbar. If it's a feature request you should change the bug label to feature request

Thanks for the info! I cannot change it to a feature request though
