### ISSUE TITLE
New tab homepage: disabled in Settings, but still shows

### ISSUE THREAD

**Issue by mariusa** [kiwibrowser/src.next#514]
**Describe the bug**
I disabled homepage in Settings, but still shows on new tabs

**To Reproduce**
Settings > Homepage > Off
New tab
Shows 2 rows of links to Facebook, Amazon, Yahoo... and "Discover" news

**Expected behavior**
New tab should show a blank page

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Lite 11 5g
 - Android Version :  A11 
 - Kiwi Browser Version 98.0

**Additional context**
Would love to show bookmarks instead of those links & news. Or, 'Classic homepage' seems to work, it has most visited sites (?) and news can be turned off.

**Comment by karl-pae** [comment]
> Would love to show bookmarks instead of those links & news.

You can add `chrome://bookmarks` under "Enter custom web address"

**Comment by mariusa** [comment]
Perfect, thank you!
