### ISSUE TITLE
desktop mode bug

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src.next#52]
When I open desktop mode by default and click Developer tools again, it will automatically change back to mobile mode.Then I have to refresh again.

**Comment by kiwibrowser** [comment]
Fixed (upcoming build)

**Comment by drc5521** [comment]
> Fixed (upcoming build)

This problem has been fixed, but there is another bug, still open the desktop mode, exit the browser, close the background, reopen the browser, then search, pull down to refresh, it will return to the phone mode, and then refresh, back to the desktop mode. ...

**Comment by drc5521** [comment]
> Fixed (upcoming build)

This problem has been fixed, but there is another bug, still open the desktop mode, exit the browser, close the background, reopen the browser, then search, pull down to refresh, it will return to the phone mode, and then refresh, back to the desktop mode. ...

**Comment by d3ward** [comment]
#62
