### ISSUE TITLE
Extension install from Chrome Store error

### ISSUE THREAD

**Issue by e-t-l** [kiwibrowser/src.next#521]
**Describe the bug**
When trying to install an extension from chrome.google.com/webstore, a popup appears saying "An error has occured." Tapping the "show details" button displays: "Image decode failed"

**To Reproduce**
1. Navigate to the Chrome extension store on Kiwi
2. Go to the page of an extension, e.g. "[Free Email Tracker by Saleshandy](https://chrome.google.com/webstore/detail/free-email-tracker-by-sal/acfmebaomboldplijdpfepofggkocgnl)"
3. Tap "Add to Chrome"

**Expected behavior**
The extension installs without issue

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - Android Version : A12
 - Kiwi Browser Version 98.0.4758.106

**Comment by gnadelwartz** [comment]
For me the extension installs without problem and opens Gmail website, opening the extension options shows a login screen.
Can you provide more contex whats goings wrong on your device pls.

**Comment by e-t-l** [comment]
LOL the context is I use a domain-based adblocking firewall, and when I installed Kiwi I forgot to add an exception for it. I appreciate your willingness to help, sorry for wasting your time.
