### ISSUE TITLE
Does Kiwi Browser support self-hosted updates for third-party extensions instead of via the chrome web store?

### ISSUE THREAD

**Issue by akang1937** [kiwibrowser/src.next#527]
Does Kiwi Browser support self-hosted updates for third-party extensions instead of via the chrome web store?

**Comment by DUOLabs333** [comment]
So, you want Kiwi to support some type of self-hosted Web Store? How would that even work?

**Comment by kiwibrowser** [comment]
Yes Kiwi respects custom update_url in the manifest file
