### ISSUE TITLE
The Baidu Baijiahao picture shows a problem.

### ISSUE THREAD

**Issue by gugulu18** [kiwibrowser/src.next#535]
![Uploading Screenshot_20220308_180103_com.kiwibrowser.browser.jpg…]()
Dear developer, hello, there is a problem with the picture display of Baidu Baijiahao, the avatar is not displayed, I hope it can be fixed as soon as possible, thank you.

**Comment by gugulu18** [comment]
https://baijiahao.baidu.com/s?id=1724160582934986250&wfr=spider&for=pc&searchword=%E7%99%BE%E5%AE%B6%E5%8F%B7

**Comment by gugulu18** [comment]
![Uploading Screenshot_20220308_180103_com.kiwibrowser.browser.jpg…]()

**Comment by gnadelwartz** [comment]
Does the ze problem also exist if you disable blocking ads?

**Comment by gugulu18** [comment]
> Does the problem also exist if you disable blocking ads?

Thank you for your reply, I have now solved this problem by reinstalling the browser.

**Comment by gnadelwartz** [comment]
Thanks for information, close the issue pls.

**Comment by gnadelwartz** [comment]
@kiwibrowser pls dlose this issue ...
