### ISSUE TITLE
refresh home page - news

### ISSUE THREAD

**Issue by Titanposeidon** [kiwibrowser/src.next#536]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
 home page , news dont refresh when pull down the page, it'd be nice to add this feature

**Additional context**

**Comment by karl-pae** [comment]
Until this gets implemented (maybe), you can use refresh button from the menu. :)

**Comment by karl-pae** [comment]
Duplicate of #518.
**close.**

**Comment by karl-pae** [comment]
You can't swipe down (pull to refresh) or 

You can swipe down, but news feed won't refresh.

**Comment by karl-pae** [comment]
Hi, download the latest build from here:
https://github.com/kiwibrowser/src.next/releases

and revert if the issue still occurs, else you can close this issue.

I don't have that problem. Swipe down works and news feed too is refresh. 😕

**Comment by kiwibrowser** [comment]
Freshly fixed in 99-series :) Thank you very much @karl-pae for triage and feedback!

**Comment by karl-pae** [comment]
> Freshly fixed in 99-series :) Thank you very much @karl-pae for triage and feedback!

So #518 too should be closed. 😄
