### ISSUE TITLE
Please change the translate of that text.

### ISSUE THREAD

**Issue by kyoyacchi** [kiwibrowser/src.next#538]
I mean, it's "Web Mağazası Sayfasını Optimize Edin."  (Turkish)
Not like that. It's like translated from Google.
Also, the explanation is wrong as well... 
(*Web Mağazası sayfasının görünümünü iyileştirin.*) is ok for that. (I think).

Is there a *crowdin* link to that sentence/word?

*Also please unban me from discord server. I wasn't impersonating anyone. I was just talking as usual how i talk with people.*

![Screenshot_2022-03-13-02-31-18~2](https://user-images.githubusercontent.com/63583961/158038629-bbb2da5f-6e4e-42b1-ab7d-b941a0e337aa.png)

(*The SS is from Accessibility("Erişilebilirlik") page.*)

**Comment by Moon1moon** [comment]
https://crowdin.com/translate/kiwibrowser
