### ISSUE TITLE
Save website as pdf

### ISSUE THREAD

**Issue by kryptobolt200528** [kiwibrowser/src.next#54]
I think many people use this feature ...and its not available on most browsers ....this can too give a boost to the downloads.

**Comment by Lartsch** [comment]
Well in fact you can just use the "Share..." button from Kiwi's 3-Dot menu and then choose "Print" > PDF

**Comment by kryptobolt200528** [comment]
> Well in fact you can just use the "Share..." button from Kiwi's 3-Dot menu and then choose "Print" > PDF
> Using this frequently and it works well.

Hey it does work good on some phones but on others its terrible i personally tested it on 4 phones ...a samsung , a realme , a redmi and  an one plus ...
Realme and redmi's save as pdf(print) is not that good...

**Comment by d3ward** [comment]
Can you show us some screen ? It's the bug still there ?
Im gonna convert that issue to bug

**Comment by d3ward** [comment]
This is fixed . Tested on most common websites like Wikipedia , NYT , and others. 
User have to go Share->Print then pick "PDF" ( considering #457 will improve user experience  )
