### ISSUE TITLE
Chrome extensions cannot open incognito windows

### ISSUE THREAD

**Issue by clemoun** [kiwibrowser/src.next#541]
Hello,

The chrome extension I am developing requires to open an incognito window using the following code :
```const window = await chrome.windows.create({url: url, incognito: true, focused: false})```

Even with the extension set to "Allow Incognito Mode", this code does not work on KiwiBrowser the same way it does on Chrome (Version 99.0.4844.51 - 64-bit):
- A new tab is created but not as incognito
- The new tab is focused

This has been tested on:
 - Device: FairPhone 3
 - Android Version : 10
 - Kiwi Browser Version :  99.04844.66
 
Thanks for your help !

**Comment by FFace32** [comment]
This is still the case on [3356207093](https://github.com/kiwibrowser/src.next/releases/tag/3356207093).
