### ISSUE TITLE
Please re-add Android 5 Support.

### ISSUE THREAD

**Issue by kyoyacchi** [kiwibrowser/src.next#543]
**Is your feature request related to a problem? Please describe.**

I mean, the apk(s) in releases page doesn't work and play store version doesn't get any update at all.  (for android 5) I can see the app in play store.
**Describe the solution you'd like**

Re-add android 5 support back... 
**Describe alternatives you've considered**

**Additional context**

I can't install any apk in releases page or the app doesn't gets any update from play store.

The latest version that i use for now is "96.0.4664.58". (Yes there is enough space, and i tried to install.)

**Comment by kyoyacchi** [comment]
@kiwibrowser What do you say/think?

**Comment by gnadelwartz** [comment]
Android 5 support is no more possible as chromium raised the bar to support Android 6 and above only, so you havevto stick with 96.xxx Version 

Android 6 is out for 8 years, you should consider to update/replace your device...

**Comment by axopoulos** [comment]
> Android 5 support is no more possible as chromium raised the bar to support Android 6 and above only, so you havevto stick with 96.xxx Version
> 
> Android 6 is out for 8 years, you should consider to update/replace your device...

What. My phone (redmi note 3) is working perfectly fine and it's powerful enough, good cpu and ram, why do I have to replace it? just because companies removed older Android support only to make more money? What a joke.

**Comment by kyoyacchi** [comment]
> > Android 5 support is no more possible as chromium raised the bar to support Android 6 and above only, so you havevto stick with 96.xxx Version
> > Android 6 is out for 8 years, you should consider to update/replace your device...
> 
> What. My phone (redmi note 3) is working perfectly fine and it's powerful enough, good cpu and ram, why do I have to replace it? just because companies removed older Android support only to make more money? What a joke.

Is your phone android 5?

**Comment by gnadelwartz** [comment]
> What. My phone (redmi note 3) is working perfectly fine and it's powerful enough, good cpu and ram, why do I have to replace it? just because companies removed older Android support only to make more money? What a joke.

Blame Xiaomi not Kiwi:
Released 2016, March 03 Status	Discontinued,  Android 5.1.1 (Lollipop), upgradable to 6.0.1 (Marshmallow)

**Comment by kiwibrowser** [comment]
> > Android 5 support is no more possible as chromium raised the bar to support Android 6 and above only, so you havevto stick with 96.xxx Version
> > Android 6 is out for 8 years, you should consider to update/replace your device...
> 
> What. My phone (redmi note 3) is working perfectly fine and it's powerful enough, good cpu and ram, why do I have to replace it? just because companies removed older Android support only to make more money? What a joke.

I agree with you it's silly and sad to see that both manufacturers and Google push people to throw away their phones by not doing software updates.

The reference / target development device for Kiwi is a OnePlus 6 from 2018, which is average-ish in terms of performance and updates (+/- equivalent of a Xiaomi Redmi 10 @ 150 USD or so).

It may be possible to support older devices, I'm just not too sure of the complexity of it.

To me it sounds relatively "simple", but if Google themselves decided to drop support for older devices, I wonder if this is just a political choice, or if it's a technical choice that is more expensive than it seems.

**Comment by Ibuprophen** [comment]
> Android 5 support is no more possible as chromium raised the bar to support Android 6 and above only, so you havevto stick with 96.xxx Version
> 
> Android 6 is out for 8 years, you should consider to update/replace your device...

@gnadelwartz, can you please clarify what the last version of Kiwi to have v96.xxx?

Thanks a Bunch! 👍 

~Ibuprophen
