### ISSUE TITLE
[bug] URL of opened sites cannot be edited 

### ISSUE THREAD

**Issue by kryptobolt200528** [kiwibrowser/src.next#55]
[Video describing issue](https://youtu.be/BBgfyhb4o9U)

**Comment by nostalgickd** [comment]
I don't think this is a bug. It's a **stupid** change from Google's side.
You can still edit the URL by clicking on the pencil button right under the URL bar.

It's called "Search Ready Omnibox" and I've been trying to disable it as well. 
There used to be a flag to toggle it, but it's gone now.

Here's some explanation from [Google support](https://support.google.com/chrome/thread/6037926/how-to-disable-the-new-effect-of-clearing-the-address-bar-when-clicking-it?hl=en):
```
It's to make it extra clear that you can start typing directly after clicking the omnibox (address bar).
The current URL is listed beneath the Omnibox as first result and has a pencil icon next to it. 
So, you can still edit the current URL.
 
Google sometimes does  'field studies' to see how actual people use Chrome and they saw
that lots of them click the 'x' before typing a new address. 
So, just marking the address blue doesn't seem to be clear enough for those people.
When Google's testing such a thing, they integrate it in Chrome as a so called 'flag'. 
This allows people to disable it if it doesn't work. It's also not sure if this change will be kept.
```
