### ISSUE TITLE
Disable Pull to Refresh Option... 

### ISSUE THREAD

**Issue by Ibuprophen** [kiwibrowser/src.next#550]
To put simply... I was hoping for the developer to add an option to be able to disable the Pull to Refresh feature. 

If there's an Extension available (that I was unable to locate in the store) or an option already available (that I had been unable to locate), please help me out with some guidance. 

Thank you very much for your time, patience and understanding with this! :-)) 

~Ibuprophen

**Comment by MooShuOrc** [comment]
That would be a welcome feature. For reference, [Soul Browser](https://github.com/SoulBrowser/SoulBrowser) has a good implementation of this.

**Comment by EternityForest** [comment]
I very much would like to see this(And ANY future gestural UI) made configurable.

I have accidentally lost data many times with this. I would imagine people with certain disabilities probably have even more trouble.

At the very least, the pull distance should be configurable.

**Comment by pc00per** [comment]
Kiwi's issue section is piling up. So I'm not sure devs will prioritize open issues instead of their current working roadmap. 
I'd like to this feature too. I always hated accidental refreshes. I never got a chance to manually refresh a page. If I were, I would just head to menu & use physical button. A gesture for such critical event is a complete nightmare.

**Comment by htsmi** [comment]
I'd also like to express my support for an option to disable pull-to-refresh. It is something I have always turned off in Firefox. I just lost a multi-page medical form I was filling because I attempted to scroll to the top of a disclaimer screen that popped up.

**Comment by Ibuprophen** [comment]
This development appears (to me) abandoned... 👎

**Comment by htsmi** [comment]
Umm okay... I wouldn't assume the project is abandoned yet though, and in any case several other people have requested this and it's marked as enhancement. I don't think I see how it is productive to mark it as complete..?

**Comment by Ibuprophen** [comment]
Reopened as a (hopeful) planned enhancement. 👍 

~Ibuprophen

**Comment by htsmi** [comment]
Thank you!

**Comment by Ibuprophen** [comment]
I'm going to close this issue since my phone is no longer compatible... 

~Ibuprophen
