### ISSUE TITLE
Current JS `prompt()` behavior is  not very intuitive

### ISSUE THREAD

**Issue by ravilov** [kiwibrowser/src.next#566]
**Current behavior:**
- prompt opens, text field is not focused and doesn't show up virtual keyboard, I have to manually tap the field
- if I close prompt by clicking OK, prompt disappears and data is sent to JS but the virtual keyboard is left open
- if I close prompt by tapping DONE on keyboard, keyboard goes away but the prompt is still open and requires clicking OK

**Expected behavior:**
- prompt opens, text field gets focused immediately and virtual keyboard is shown
- regardless how I close it (with prompt's OK or keyboard's DONE), prompt should close and the keyboard disappear

----

Kiwi Browser 99.0.4844.94

**Comment by gnadelwartz** [comment]
Does Chrome work as you expect?

**Comment by ravilov** [comment]
Been forever since I tried Chrome. Just tried it now (99.0.4844.88) and it seems to do exactly the way Kiwi does. So there is that I guess. But nobody says Kiwi can't be better, right? 😉

**Comment by gnadelwartz** [comment]
Shure, but wouldn't it be better to file but report to chrome then also, so every chromium based browser will be improved?

Let's see what Arnaud think about.

**Comment by d3ward** [comment]
As this is standard Chromium behaviour and not a Kiwi thing, I close it. 
PS. Now when you click OK , both prompt and virtual get closed. Just a slight improvement
