### ISSUE TITLE
Why are there tracker in Kiwi Browser 

### ISSUE THREAD

**Issue by Raul1198** [kiwibrowser/src.next#571]
Here's a screenshot from Application Manager
![Screenshot_20220410-032135_App Manager](https://user-images.githubusercontent.com/29801315/162592672-fb0e6fb1-f5ee-4ae0-909b-9fb594990f0a.png)

I thought kiwi was a privacy respecting browser

**Comment by UltraStudioLTD** [comment]
> Here's a screenshot from Application Manager ![Screenshot_20220410-032135_App Manager](https://user-images.githubusercontent.com/29801315/162592672-fb0e6fb1-f5ee-4ae0-909b-9fb594990f0a.png)
> 
> I thought kiwi was a privacy respecting browser

As far as I can see 5/8 are ads trackers but idk about others.

Also care to share that Application Manager's link or APK?

**Comment by Raul1198** [comment]
> > Here's a screenshot from Application Manager ![Screenshot_20220410-032135_App Manager](https://user-images.githubusercontent.com/29801315/162592672-fb0e6fb1-f5ee-4ae0-909b-9fb594990f0a.png)
> > I thought kiwi was a privacy respecting browser
> 
> As far as I can see 5/8 are ads trackers but idk about others.
> 
> Also care to share that Application Manager's link or APK?

https://muntashirakon.github.io/AppManager/

https://t.me/AppManagerChannel/209

https://github.com/MuntashirAkon/AppManager

**Comment by kiwibrowser** [comment]
It's AdMob integration for the ads that appears in the newsfeed in the homepage.
A) AdMob is not activated on the GitHub build
B) AdMob is optional and can be deactivated by the user just by pressing the cog (setting) icon on the homepage
