### ISSUE TITLE
Privacy Sandbox always enabled

### ISSUE THREAD

**Issue by MooShuOrc** [kiwibrowser/src.next#574]
On the current GitHub build (101.0.4951.28), and at least the previous build, the "Privacy Sandbox" feature (Setings > Privacy) cannot be shut off. It just immediately re-enables itself.

Frankly, this "feature" should not even be in Kiwi at all. Despite all the talk about "privacy," it's actually just Google tracking.

Please please please fix this and give serious thought to removing it entirely.

ARM64 build on Android 10.

**Comment by kiwibrowser** [comment]
I'll check, it's indeed a bug.
For information, the Privacy Sandbox isn't active at all in Kiwi because the Privacy Sandbox requires an external component to be downloaded (chrome://components) so it should be removed from UI completely.

**Comment by MooShuOrc** [comment]
Sounds good. Thanks for the quick reply.

**Comment by kiwibrowser** [comment]
(By the way, I just checked and FLoC is always off, but I'll work on removing the component completely)

**Comment by MooShuOrc** [comment]
The menu option remains, but it stays shut off, which is good enough for me.
