### ISSUE TITLE
Flocuss extension Google account Sync

### ISSUE THREAD

**Issue by yo-honey** [kiwibrowser/src.next#575]
Google Drive Sync is Not working in flocuss extension.

Open Flocuss extension 
Click on New Account 
Select Google drive
Click on add account
Click on "Login with Google"
Nothing happens

So it should open a Google sign in page so I can login into Google account to sync bookmarks from Google account

 - Device: [OnePlus 7T Pro]
 - Android Version : [A11 ]
 - Kiwi Browser Version [101.0.4951.13 ]

**Comment by netrunner-exe** [comment]
I have same issue.

**Comment by 424344** [comment]
there is a workaround: in floccus on a desktop browser login with Google, then export the config. then copy the config file to android and import the config.

**Comment by d3ward** [comment]
With latest Kiwi v116 this has been fixed . Login with Google account on Floccus extension in Kiwi works.
