### ISSUE TITLE
Graphical glitches in Tab bar on Samsung Galaxy Tab S8+

### ISSUE THREAD

**Issue by lje** [kiwibrowser/src.next#576]
**Describe the bug**
When I scoll down on the page until the tab bar disappears and then scroll back up, the tab bar contains graphical glitches.
The issue does not occur in Chrome for Android.

**To Reproduce**
Open web page. Scroll down a bit until the tab bar disappears, scroll back up

**Expected behavior**
No graphical glitches (like in Chrome)

**Screenshots**
All screen shots are cropped to the upper part of the screen because only the tab bar is affected by the glitch.

Tab bar in initally (no glitch)
![Screenshot_20220410-112056_Kiwi Browser](https://user-images.githubusercontent.com/357743/162809409-ff70d967-eb29-4d31-a73b-bf50e8ff7e8f.png)

After scrolling down and back up
![Screenshot_20220410-112109_Kiwi Browser](https://user-images.githubusercontent.com/357743/162809440-b8000779-8ba4-4c36-bfd8-a5a3b0138e9c.png)

After some more scrolling
![Screenshot_20220410-112125_Kiwi Browser](https://user-images.githubusercontent.com/357743/162809474-22085e79-c645-418e-88b3-40801e3f0bbd.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S8+
 - Android Version : 12.0
 - Kiwi Browser Version 101.0.4951.13

**Additional context**
I miss the option to fix the tab bar and not have it scroll out. That option is presend in Kiwi on my smartphone but not on my tablet. A fixed tab bar would probably workaround the issue as well.

**Comment by amck1nnon** [comment]
I'm having similar UI rendering issues on the S22 Ultra (SD8G1)

Mostly contained to the New Tab page specifically, but very similar in appearance.

![Screenshot_20220419-111700_Kiwi Browser](https://user-images.githubusercontent.com/49832919/163901095-be9e0c5b-33d4-4364-853b-2d8ca4d5eed1.jpg)

**Comment by lje** [comment]
Galaxy Tab S8+ is equipped with a SD8G1 as well, maybe that issue is specific to that SOC.

**Comment by jiangzhenjerry** [comment]
Same here. I have both S22 Ultra and Tab S8 Ultra, and this issue exists on both (and has existed for quite a long time, ever since I received both devices in March).

I don't think it's related to whether the tab bar can be fixed or not. On my Tab S8 Ultra, I can reproduce it by simply creating a new tab.

**Comment by kwand** [comment]
I have the same problem with both an S22 Ultra and Tab S8 Ultra. On the S22, it's only really visible upon hiding the toolbar, while on the S8, it's very easy to reproduce given the toolbar is present almost all the time. Creating a new tab causes this issue immediately.

**Comment by pressRtowin** [comment]
Happens on my Tab S8 Ultra as well as my Z Fold4 (which, unlike the S22 Ultra and Tab S8 Ultra, uses a Snapdragon 8+ Gen 1).

**Comment by Daedren** [comment]
Appears to be fixed for me on the latest version (107.0.5304.66)

**Comment by amck1nnon** [comment]
> Appears to be fixed for me on the latest version (107.0.5304.66)

Agreed. Seems to work properly now on the same S22 Ultra mentioned earlier.

**Comment by lje** [comment]
Issue seems to be fixed, thanks.

**Comment by kiwibrowser** [comment]
Thank you for the confirmation @Daedren @amck1nnon and @lje
