### ISSUE TITLE
Accessibility icon  disappears  in the dark mode.

### ISSUE THREAD

**Issue by Darkshadow-create** [kiwibrowser/src.next#588]
When kiwi browser switched to the dark mode,accessibility icon doesn't appear normally it the settings.![Screenshot_20220415_144338.jpg](https://user-images.githubusercontent.com/62942201/163660718-7c83ecb2-c2a8-42fe-b578-286dd33b453a.jpg)

**Comment by Darkshadow-create** [comment]
![fff899d2c43c2db328ed82eafe849a0](https://user-images.githubusercontent.com/62942201/163532393-cb4c6b3b-3d42-4d9a-a267-29d53034ebe6.jpg)

**Comment by kyoyacchi** [comment]
it's fixed as far as i can see

**Comment by kiwibrowser** [comment]
Yes it is resolved. Thank you for verifying it too @kyoyacchi ! :)

**Comment by kyoyacchi** [comment]
> Yes it is resolved. Thank you for verifying it too @kyoyacchi ! :)

Btw, could you unban me from discord server? I did nothing wrong. I just spoke my native language. What's wrong with this?
