### ISSUE TITLE
[BUG] The bottom toolbar when pushing web elements do not move their clickable area

### ISSUE THREAD

**Issue by Y-T-G** [kiwibrowser/src.next#59]
The elements still act as if they were not moved from their position. For example, tapping 'Continue' below, actually registers as a tap on the 'Open' button, since that was its position before being pushed up by the toolbar.

![2021_07_19_02_55_19_trim](https://user-images.githubusercontent.com/32206511/126079310-3e6addb9-2b54-4f82-99e7-52b0caa1d41c.gif)

**Comment by Y-T-G** [comment]
Inspecting from DevTools, I find that it happens with  elements that have the `position` property set to `fixed`.

**Comment by Lartsch** [comment]
Might be related to #89

**Comment by Y-T-G** [comment]
This has been fixed in the latest version. Although https://github.com/kiwibrowser/src.next/issues/170 still exists and is closely related to this.
