### ISSUE TITLE
Kiwi Extensions Issue

### ISSUE THREAD

**Issue by touhidurrr** [kiwibrowser/src.next#6]
Kiwi browser extention pages are glitchy. Even uBlock Origins preferences page doesn't show properly. The editor of uBO doesn't work.
Firefox seems to have fixed the extension related issues. Maybe see what they have done.

**Comment by d3ward** [comment]
Firefox is different from Kiwi
The glitchy extensions page seems to be fixed , same for the uBlock preferences page .
Feel free to reopen the issue if necessary

**Comment by barolo** [comment]
It's broken again, in latest version just shows blank page

**Comment by touhidurrr** [comment]
@d3ward this issue might need to be reopned?

**Comment by d3ward** [comment]
It's the issue still there ? For me ubo seems to works fine

**Comment by touhidurrr** [comment]
> It's the issue still there ? For me ubo seems to works fine

Dunno. I cant test it. Recently I tried to install the latest dev version in my Android 5.0 run phone and it didn't install for Android 6.0 requirement. But the Play Store version works fine. Is this requiremnet necessary?
