### ISSUE TITLE
[BUG]Toolbar behaves weirdly when not connected to a network

### ISSUE THREAD

**Issue by kryptobolt200528** [kiwibrowser/src.next#60]
![Screenshot_2021-07-19-17-42-29-14](https://user-images.githubusercontent.com/72438196/126158251-17f9cf12-f492-4170-a52a-a05a25457ec9.jpg)

![Screenshot_2021-07-19-17-42-44-71](https://user-images.githubusercontent.com/72438196/126158327-1a983692-850c-4191-9819-15f1055a2452.jpg)

![Screenshot_2021-07-19-17-42-49-50](https://user-images.githubusercontent.com/72438196/126158344-c19a967a-65ad-4012-a97b-e00e53583c12.jpg)

**Comment by Y-T-G** [comment]
I got this too in the recent build

**Comment by kiwibrowser** [comment]
This is a high priority issue

**Comment by d3ward** [comment]
This issue has been fixed ( tested on v98 builds )
