### ISSUE TITLE
when my video is playing

### ISSUE THREAD

**Issue by sunjanesy** [kiwibrowser/src.next#603]
![Video_20220429_080130_584](https://user-images.githubusercontent.com/104602119/165866314-ca924bd3-90ca-4660-862c-b5d9309b7318.gif)

site: hanime.tv
description: When I jump to the video timeline, the picture will freeze at that frame, only the sound is normal.
Device: Redmi K50
OS: MIUI13

**Comment by kyoyacchi** [comment]
I see you're man of culture as well.

**Comment by JoeJoeyMa** [comment]
https://github.com/kiwibrowser/src.next/issues/613 #613
