### ISSUE TITLE
[Bug] Dark mode activated but white flash persist

### ISSUE THREAD

**Issue by joelocandol** [kiwibrowser/src.next#617]
Hi, when the dark mode is on, there is still a white flash happening when the keyboard appears on screen (and also when a page is loaded). I noticed that the problem is solved when I disable and then enable again the dark mode 

Kiwi version: 101.0.4951.48
Phone: Redmi note 10 (although, I had also noticed that this problem happens in other phones)

**Comment by jodel64** [comment]
Can confirm this (Android 9/OnePlus 5)

**Comment by d3ward** [comment]
If you are still using Kiwi, check the latest v116 and feel free to reopen the issue if it persists.
