### ISSUE TITLE
desktop and mobile mode bug

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src.next#62]
Still open the desktop mode, exit the browser, close the background, reopen the browser, then search, pull down to refresh, it will return to the phone mode, and then refresh, back to the desktop mode. ...When I manually checked, everything returned to normal.
See the video for details.

https://user-images.githubusercontent.com/55195642/126247185-091b5c0e-6917-4c21-876c-3a2d198717b1.mp4

**Comment by d3ward** [comment]
If you want to always start desktop mode , even after restart Kiwi , you need to enable the option at the bottom of Settings->Accessibility
