### ISSUE TITLE
Please upgrade Chromium to 102

### ISSUE THREAD

**Issue by DiAnTTA** [kiwibrowser/src.next#626]
Chrome, Brave, Vivaldi browsers have upgraded Chromium to 102

**Comment by gnadelwartz** [comment]
Dev is working hard on the next update , v103 is more  complex than expected , there are some under hood improvements in chromium code that generate conflicts , which need to be fixed before releasing

**Comment by Anoop2609** [comment]
Chromium is currently at 104 still google play store version is not getting updated. Is there any upcoming plans to upgrade?

**Comment by kiwibrowser** [comment]
I have functional rebase to 105.0.5195.24 -- I'll push it around Wednesday/Thursday to Play Store (the tab switcher is not functional yet) and update the repo here (as it is long time)

**Comment by Anoop2609** [comment]
Thanks for updating in play store.
