### ISSUE TITLE
Google docs: Unable to load file

### ISSUE THREAD

**Issue by QuantumWalker** [kiwibrowser/src.next#63]
Hello, 
After open any google docs "in desktop view function" during 1 minute an error appears "Trying to connect" and "something went wrong" on the up of document and new window "unable to load file. Try to load it again" and do it all over again. 
If we want to use copy/paste function from menu, we must download extraction Google Docs Offline, after installation an issue appear again.

Can anyone fix it? 

For me it important, because in desctop mode we have all function of google docs ..add on, or macros in spreadsheets.
Thanks.

![Screenshot_20210720-170624_Kiwi Browser](https://user-images.githubusercontent.com/87707539/126338203-114f6810-c323-4673-9a3d-8056f2aabf42.jpg)

![Screenshot_20210720-171234_Kiwi Browser](https://user-images.githubusercontent.com/87707539/126339209-60cb4a39-97a6-490b-932d-e16802d99bc5.jpg)

![Screenshot_20210720-161932_Kiwi Browser](https://user-images.githubusercontent.com/87707539/126336415-16524ffe-1baa-4e9b-b67a-3d2efa1cb9af.jpg)

**Comment by Lartsch** [comment]
Did this work on previous Kiwi versions? @QuantumWalker

**Comment by d3ward** [comment]
@QuantumWalker is this still a bug ?

**Comment by tortino2** [comment]
> is this still a bug ?

yes, bug still present (tested on kiwi v112.0.5615.137)

**Comment by d3ward** [comment]
Just tried with v116 . Despite i find it very uncomfortable to use Google sheet with desktop/web, I managed to work on it , use copy/paste feature with the extension and everything seems to work without issues.
@tortino2 @QuantumWalker if you have a chance , try and reopen the ticket if issue persist .
