### ISSUE TITLE
A small window for options of extensions?

### ISSUE THREAD

**Issue by rainfall-breeze** [kiwibrowser/src.next#630]
When the option of extensions is opened, could it pop from the bottom instead of a new tab?
Just like the lemur browser and rains browser.
![QtScrcpy_20220609_181742_452](https://user-images.githubusercontent.com/67453066/172825841-194eb6dd-5061-421e-bb25-b6dc79b0cdac.png)
![微信图片_20220609181824](https://user-images.githubusercontent.com/67453066/172825861-9591890d-de32-4015-a0a4-05cde512414f.jpg)

**Comment by d3ward** [comment]
Duplicate of https://github.com/kiwibrowser/src.next/issues/479 .

**Comment by Ibuprophen** [comment]
@kyoyacchi, If your referring to the Kiwi Browser, the following link provides guidance to your question. 

https://github.com/kiwibrowser/src.next#releases

~Ibuprophen
