### ISSUE TITLE
empty new tab after 1 hour

### ISSUE THREAD

**Issue by Titanposeidon** [kiwibrowser/src.next#638]
it'd be nice to get an empty new tab when opening kiwi browser after a while later ( like 1 hour or something else )
it always opening the last opened tab, sometimes its annoying, it'd be an option to open last tab or new tab

opera has this future

**Comment by gnadelwartz** [comment]
Did you enable settings - privacy - close all tabs between sessions?

**Comment by d3ward** [comment]
@Titanposeidon Can you check latest version ? This looks like was a bug , and I don't see it in v116 . Closing this , but feel free to re-open if you still have issues
