### ISSUE TITLE
[BUG] System Autofill Doesn't Work

### ISSUE THREAD

**Issue by nullpenguinexception** [kiwibrowser/src.next#64]
Hello, in other chromium based browsers (Chrome, Brave...) the inline autofill works correctly. I try it in Kiwi, it doesn't handle. By the way, I use KeePassDX as an autofill provider.

**Comment by nullpenguinexception** [comment]
@d3ward I'm trying to find the source of the bug. Can it be about **AutofillServerCommunication**? Other browsers which autofill work, have this command line tag in **chrome://version**. The exact opposite: _Kiwi, Bromite, Ungoogled Chromium Android_ browsers which don't support autofill, don't contain **AutofillServerCommunication** tag in command line section. It would be better to research on this command line tag.

**Comment by kiwibrowser** [comment]
> AutofillServerCommunication

Not totally sure, but I think AutofillServerCommunication just means it's a server that stores what the user enters in input fields (don't think it's a good thing).
https://source.chromium.org/chromium/chromium/src/+/main:components/autofill/core/common/autofill_features.cc;l=345;drc=0775b29ae4f4dc6d3ad250f525d76c97320e6e75;bpv=1;bpt=1

**Comment by kiwibrowser** [comment]
Indeed, according to Google, the Autofill service needs to check that the owner of a website needs to be the person who asks for the autofill;
exception: "Note: The autofill service could also add well-known browser apps into an allowlist and skip the verifications above, as long as the service can verify the authenticity of the browser app by checking its signing certificate."

**Comment by nullpenguinexception** [comment]
> Hello,
> 
> I start to suspect more and more that it's Google who decides who has access to Autofill API or not, and not due to app compatibility.
> 
> To verify this, can you add Kiwi Browser in the autofill whitelist at OS level ?
> 
> `adb shell settings put global autofill_compat_mode_allowed_packages "$(adb shell settings get global autofill_compat_mode_allowed_packages):com.kiwibrowser.browser[url_bar]" `

`adb shell settings put global autofill_compat_mode_allowed_packages com.kiwibrowser.browser[url_bar]`
I tried this then force stop kiwi, it's still same.

**Comment by nullpenguinexception** [comment]
> > AutofillServerCommunication
> 
> Not totally sure, but I think AutofillServerCommunication just means it's a server that stores what the user enters in input fields (don't think it's a good thing).
> https://source.chromium.org/chromium/chromium/src/+/main:components/autofill/core/common/autofill_features.cc;l=345;drc=0775b29ae4f4dc6d3ad250f525d76c97320e6e75;bpv=1;bpt=1

Hmm, maybe it's because Brave & Chrome have their own autofill servers. Kiwi, Bromite, UC don't have any autofill servers.

> Indeed, according to Google, the Autofill service needs to check that the owner of a website needs to be the person who asks for the autofill;
> exception: "Note: The autofill service could also add well-known browser apps into an allowlist and skip the verifications above, as long as the service can verify the authenticity of the browser app by checking its signing certificate."

Do they say that it's about signing certificates?

**Comment by kiwibrowser** [comment]
This is where  @d3ward  found the info: https://developer.android.com/reference/kotlin/android/service/autofill/AutofillService

**Comment by nullpenguinexception** [comment]
Bromite's developer [says:](https://github.com/bromite/bromite/blob/master/FAQ.md)

> Does Bromite support the Android autofill framework?
>>No; the only autofill available in Chromium browsers requires integration with the Play Store binary blobs.

I guess there is an API about autofill support, which requires Google Play Services.

**Comment by 1Mark** [comment]
I also have this issue, I think this began after the new UI for chromium (the one with the fancy share screen") was backported to Kiwi

**Comment by Lartsch** [comment]
Fixed with latest version. Please close @nullpenguinexception

**Comment by Kallb123** [comment]
I've just tried yesterday's play store version (93.0.4577.22). It does not have the same behaviour as Chrome and Firefox. They seem to use the native system auto fill. Kiwi does not prompt to fill details. Kiwi requires password applications to enable accessibility mode, which is different to supporting the native auto fill framework. Happy to be corrected if there's an even newer version.

**Comment by d3ward** [comment]
> Fixed with latest version. Please close @nullpenguinexception 

Im not sure it's fixed . I use Bitwarden and that is Chrome 
![Screenshot_20210805-023741.jpg](https://user-images.githubusercontent.com/39910418/128273248-35ba8f14-8ec4-461c-bdda-91a64bcea335.jpg)

While if we take a look at Kiwi , there is nothing 
![Screenshot_20210805-023802.jpg](https://user-images.githubusercontent.com/39910418/128273276-fcd969ed-18d0-4d0e-92c6-90d6dfe34a97.jpg)

**Comment by nullpenguinexception** [comment]
> Fixed with latest version. Please close @nullpenguinexception

Nope, I've tried [latest release](https://github.com/kiwibrowser/src.next/releases/tag/1094737737) it's still same.

**Comment by Lartsch** [comment]
With bitwarden I have no issues having It's "legacy" mode enabled to support non-native autofill. Always had it like this.

But I can see that there might be many such services not having such an option. Basically what @Kallb123

**Comment by MmyGgithubAaccount** [comment]
For autofill, I've noticed that even using legacy mode in bitwarden which uses accessibility service, bitwarden doesn't get the url from where the autofill was requested on the .dev version of kiwi while for non-dev kiwi (both playstore and github builds) bitwarden gets the page url
![1628169237278](https://user-images.githubusercontent.com/58236619/128356014-890b87fa-0436-45ca-b444-959b9a53ee57.png)
![1628168670926](https://user-images.githubusercontent.com/58236619/128356019-d889e6d2-1a99-4af8-94f9-6f8215d021d4.png)
Which makes me ask what other differences are there between these two versions

**Comment by nullpenguinexception** [comment]
> With bitwarden I have no issues having It's "legacy" mode enabled to support non-native autofill. Always had it like this.
> 
> But I can see that there might be many services not having such an option. Basically what @Kallb123 said

Accessibility is not about autofill. It's just a full-time front side service that checks your screen for any login, also it drains the battery much faster. Inline system autofill is completely different from that. This API has come in Android 8 (API level 26), and it's much better obviously.

**Comment by alkanna** [comment]
Any news on this one ?
I'm having the same issue on latest play store version.

**Comment by doobydooby72** [comment]
Ive used keepass2android for ages and this became a problem some time ago (dont know how long but a while... Months) always used the accessibility extension for the keepass app and it never messes up (except of recent with tutanota now making keepass thinks its mega and not tutanota, very recent)
I dont know how this was broken d its sad it hasnt been fixed yet. Its the only element on mobile kiwi thats a deal breaker (the other being kiwis lack of tab choice on a tablet) now i find myself using iceraven half the time even though it has a fraction of the support of kiwi cos autofill works with that at least. These 2 browsers are my only choices cos i have a myriad of extensions/addons i couldnt live without. Cant wait for a fix. Lets make kiwi great again 😝😭❤️
Thanks for the great app otherwise, love the Diversity of options.

**Comment by kkuhle** [comment]
In [132](https://github.com/kiwibrowser/src.next/issues/132) in this [comment](https://github.com/kiwibrowser/src.next/issues/132) it was suggested to run some compatibility commands manually.

- Store the current `autofill_compat_mode_allowed_packages` in a variable:
```
n=$(settings get global autofill_compat_mode_allowed_packages)
```

*If I run this command without storing in a variable to see the output, here is what I get*:
```
settings get global autofill_compat_mode_allowed_packages                                                                           <
com.android.chrome[url_bar]:com.brave.browser[url_bar]:com.brave.browser_beta[url_bar]:com.brave.browser_nightly[url_bar]:com.chrome.beta[url_bar]:com.chrome.dev[url_bar]:com.chrome.canary[url_bar]:com.microsoft.emmx[url_bar]:com.opera.browser[url_field]:com.opera.browser.beta[url_bar]:com.opera.mini.native[url_bar]:com.opera.mini.native.beta[url_bar]:com.sec.android.app.sbrowser[location_bar_edit_text]:com.sec.android.app.sbrowser.beta[location_bar_edit_text]:org.mozilla.fennec_aurora[url_bar]:org.mozilla.firefox[url_bar]:org.mozilla.firefox_beta[url_bar]
```
*^ these appear to be all of the other browsers that I have installed where autofill works.*

*autofill for kiwi doesn't work as set up above*

- add kiwi browser to this list
```
settings put global autofill_compat_mode_allowed_packages $n:com.kiwibrowser.browser[url_bar]
```
*and now I have kiwi listed*
```
settings get global autofill_compat_mode_allowed_packages                                                                           <
com.android.chrome[url_bar]:com.brave.browser[url_bar]:com.brave.browser_beta[url_bar]:com.brave.browser_nightly[url_bar]:com.chrome.beta[url_bar]:com.chrome.dev[url_bar]:com.chrome.canary[url_bar]:com.microsoft.emmx[url_bar]:com.opera.browser[url_field]:com.opera.browser.beta[url_bar]:com.opera.mini.native[url_bar]:com.opera.mini.native.beta[url_bar]:com.sec.android.app.sbrowser[location_bar_edit_text]:com.sec.android.app.sbrowser.beta[location_bar_edit_text]:org.mozilla.fennec_aurora[url_bar]:org.mozilla.firefox[url_bar]:org.mozilla.firefox_beta[url_bar]:com.kiwibrowser.browser[url_bar]
```
**and now autofill for kiwi works**

Is there any way to add kiwi to this list without taking manual action to do it?

How are these other browsers getting added when they're installed?

**Comment by kiwibrowser** [comment]
So this is very interesting that you managed to get it and to confirm that it works (I suspected it too in https://github.com/kiwibrowser/src.next/issues/64#issuecomment-887592298 but couldn't validate it)

I'm pretty sure this list is hardcoded by Google, but it's not that sure, I will try to have a talk with Google on how to get certified / included in this list (if it's really them deciding, and not the OEMs) but I'm pretty sure it's in the Android project.

The biggest question is more about who can help with this at Google, so let's see, but I really appreciate you spent time to try: @kawaiiDango and @kkuhle
I'll do my best to find in their network

**Comment by batuhankrmn** [comment]
This is really important feature for me too, following the process. It'd be perfect If we get bitwarden auto fill service on Kiwi. Bitwarden extension is not that good, doesn't auto fill.

**Comment by kiwibrowser** [comment]
I wrote to Google, and waiting for their reply.

**Comment by sergioad** [comment]
Could this later be implemented for Microsoft Authenticator soon it will gain importance dude to the password-less PC unlock in Windows 11

**Comment by nullpenguinexception** [comment]
I guess the issue has been fixed. After installing latest release, autofill works fine on my Android 9 device.

If it works properly for everyone, I'll close the issue.

**Comment by batuhankrmn** [comment]
> I guess the issue has been fixed. After installing latest release, autofill works fine on my Android 9 device.
> 
> If it works properly for everyone, I'll close the issue.

I can confirm that It works for me too on latest release.

**Comment by itsmeboy0** [comment]
Latest release? The latest release from the play store does not work yet.

**Comment by nullpenguinexception** [comment]
> Latest release? The latest release from the play store does not work yet.
 
Try [this](https://github.com/kiwibrowser/src.next/releases/tag/1437849131) one, latest GitHub release.

**Comment by d3ward** [comment]
> Latest release? The latest release from the play store does not work yet.

The release of the update on play store is gradual. It takes up to 4 days to get to everyone

**Comment by itsmeboy0** [comment]
Great, looks like the update has reached the play store and it works now.

**Comment by nullpenguinexception** [comment]
As it has solved, I'm closing the issue. Thanks to everyone who helped to solve it.

**Comment by Indranil012** [comment]
Password field on xdaforum, github site is still not filling with bitwarden app.

**Comment by 1Mark** [comment]
> Password field on xdaforum, github site is still not filling with bitwarden app.

Same for me it fills the username but not the password, using latest version from the playstore

**Comment by m0vie** [comment]
This still does not work for me at all. Enabled verbose auto-fill debugging in developer options. This is the result when clicking into the logon field on github.com:


Chrome (97.0.4692.87):
```
01-15 15:20:26.023  1477  7470 V AutofillInlineSuggestionsRequestSession: onInputMethodStartInput() received on 0
01-15 15:20:26.025  1477  7510 V AutofillInlineSuggestionsRequestSession: onInputMethodShowInputRequested() received: true
01-15 15:20:26.028  1477  7470 V AutofillInlineSuggestionsRequestSession: onInputMethodStartInputView() received
01-15 15:20:26.028  1477  1477 V AutofillInlineSuggestionsRequestSession: maybeUpdateResponseToImeLocked called
01-15 15:20:26.037  1477  7510 V AutofillManagerServiceImpl: startSession(): token=Token{5b4dbbf ActivityRecord{daff28c u0 com.android.chrome/com.google.android.apps.chrome.Main t4479}}, flags=0, forAugmentedAutofillOnly=false
01-15 15:20:26.037  1477  7510 V AutofillSession: updateLocked(1169554705): id=0:3727@1169554705, action=START_SESSION, flags=0
01-15 15:20:26.037  1477  7510 V AutofillSession: updateLocked(1169554705): mCurrentViewId=null, mExpiredResponse=false, viewState=null
01-15 15:20:26.037  1477  7510 V AutofillSession: Creating viewState for 0:3727@1169554705
01-15 15:20:26.037  1477  7510 V AutofillSession: Requesting structure for request #1 ,requestId=26, flags=0
01-15 15:20:26.038  1477  1477 D AutofillInlineSuggestionsRequestSession: onCreateInlineSuggestionsRequestLocked called: 0:3727@1169554705
01-15 15:20:26.093  1477  7470 V AutofillSession: New structure for requestId 26: android.app.assist.AssistStructure@d9ee75e
01-15 15:20:26.101  1477  7470 D AutofillSession: url_bars in compat mode: [url_bar]
01-15 15:20:26.101  1477  7470 D AutofillHelper: sanitizeUrlBar(): id=url_bar, domain=github.com
01-15 15:20:26.101  1477  7470 D AutofillSession: Setting urlBar as id=1073741873@1169554705 and domain github.com
01-15 15:20:26.107  3364  3364 I AndroidIME: AbstractIme.onActivate():86 LatinIme.onActivate() : EditorInfo = inputType=Email imeActionName=GO dump=[inputType=0xd1 imeOptions=0x12000002 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 initialCapsMode=0x0 hintText=null label=null packageName=com.android.chrome autofillId=0 fieldId=-1 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], IncognitoMode = false, DeviceLocked = false
01-15 15:20:26.135  1477  8222 D AutofillInlineSuggestionsRequestSession: onInlineSuggestionsSessionInvalidated() called.
01-15 15:20:26.142  1477  7469 D AutofillInlineSuggestionsRequestSession: onInlineSuggestionsRequest() received: InlineSuggestionsRequest { maxSuggestionCount = 9, inlinePresentationSpecs = [InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }], hostPackageName = com.google.android.inputmethod.latin, supportedLocales = [de_DE,en_US], extras = Bundle[EMPTY_PARCEL], hostInputToken = android.os.BinderProxy@ea5888d, hostDisplayId = 0, inlineTooltipPresentationSpec = null }
01-15 15:20:26.143  1477  7469 V AutofillInlineSuggestionsRequestSession: onInputMethodStartInputView() received
01-15 15:20:26.143  1477  1477 V AutofillInlineSuggestionsRequestSession: maybeUpdateResponseToImeLocked called
01-15 15:20:26.143  1477  1477 V AutofillInlineSuggestionsRequestSession: maybeUpdateResponseToImeLocked called
01-15 15:20:26.154  1477  1477 V RemoteFillService: calling onFillRequest() for id=26
01-15 15:20:26.242  1477  1710 V AutofillUI: hideSaveUiUiThread(): mSaveUi=null, callback=Session: [id=1169554705, component=ComponentInfo{com.android.chrome/com.google.android.apps.chrome.Main}, state=STATE_ACTIVE], mCallback=null
01-15 15:20:26.243  1477  1477 V AutofillSession: processResponseLocked(): mCurrentViewId=0:3727@1169554705,flags=2, reqId=26, resp=FillResponse : [mRequestId=26, datasets=[Dataset[noId, fieldIds=[0:3727@1169554705, 1073741873@1169554705], fieldValues=[[type=1, value=11_chars], [type=1, value=11_chars]], fieldPresentations=2, fieldInlinePresentations=2, fieldInlineTooltipInlinePresentations=2, fieldFilters=2, hasPresentation, hasInlinePresentation, hasAuthentication]], disableDuration=0, mSupportInlinePresentations=true],newClientState=null
01-15 15:20:26.243  1477  1477 V AutofillSession: updateTrackedIdsLocked(): null => {1073741873@1169554705, 0:3727@1169554705} triggerId: null saveOnFinish:true flags: 0 hasSaveInfo: false
01-15 15:20:26.244  1477  1477 D InlineSuggestionFactory: createInlineSuggestions(source=android:autofill) called
01-15 15:20:26.244  1477  1477 D AutofillInlineSuggestionsRequestSession: onInlineSuggestionsResponseLocked called for:0:3727@1169554705
01-15 15:20:26.244  1477  1477 V AutofillInlineSuggestionsRequestSession: maybeUpdateResponseToImeLocked called
01-15 15:20:26.245  1477  1477 D AutofillInlineSuggestionsRequestSession: maybeNotifyFillUiEventLoked(): hasSuggestionToShow=true, mPreviousHasNonPinSuggestionShow=false
01-15 15:20:26.245  1477  1477 D AutofillInlineSuggestionsRequestSession: Send inline response: 1
01-15 15:20:26.257  3364  3364 I ProactiveSuggestionsHolderManager: ProactiveSuggestionsHolderManager$3.display():213 Requesting to show proactive suggestions: AUTO_FILL PREEMPTIVE_WITH_SUPPRESSION
```

Kiwi (98.0.4758.51):
```
01-15 15:19:38.672  1477  8336 V AutofillInlineSuggestionsRequestSession: onInputMethodStartInput() received on 1
01-15 15:19:38.676  1477  7379 V AutofillInlineSuggestionsRequestSession: onInputMethodShowInputRequested() received: true
01-15 15:19:38.676  1477  7379 V AutofillInlineSuggestionsRequestSession: onInputMethodStartInputView() received
01-15 15:19:38.686  1477  7379 V AutofillManagerServiceImpl: startSession(): token=Token{7f1166a ActivityRecord{4e0bf8 u0 com.kiwibrowser.browser/com.google.android.apps.chrome.Main t4474}}, flags=0, forAugmentedAutofillOnly=false
01-15 15:19:38.688  1477  7379 V AutofillSession: updateLocked(1331097331): id=1:2724@1331097331, action=START_SESSION, flags=0
01-15 15:19:38.688  1477  7379 V AutofillSession: updateLocked(1331097331): mCurrentViewId=null, mExpiredResponse=false, viewState=null
01-15 15:19:38.689  1477  7379 V AutofillSession: Creating viewState for 1:2724@1331097331
01-15 15:19:38.689  1477  7379 V AutofillSession: Requesting structure for request #1 ,requestId=24, flags=0
01-15 15:19:38.695  1477  1477 D AutofillInlineSuggestionsRequestSession: onCreateInlineSuggestionsRequestLocked called: 1:2724@1331097331
01-15 15:19:38.699  1477  7379 V AutofillSession: New structure for requestId 24: android.app.assist.AssistStructure@2008979
01-15 15:19:38.699  1477  7379 D AutofillSession: url_bars in compat mode: [url_bar]
01-15 15:19:38.700  1477  7379 D AutofillHelper: sanitizeUrlBar(): id=url_bar, domain=github.com
01-15 15:19:38.700  1477  7379 D AutofillSession: Setting urlBar as id=1073741874@1331097331 and domain github.com
01-15 15:19:38.700  1477  7379 V AutofillSession: fillContextWithAllowedValuesLocked(): no node for 1:2724@1331097331
01-15 15:19:38.705  3364  3364 I AndroidIME: AbstractIme.onActivate():86 LatinIme.onActivate() : EditorInfo = inputType=Email imeActionName=GO dump=[inputType=0xd1 imeOptions=0x12000002 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 initialCapsMode=0x0 hintText=null label=null packageName=com.kiwibrowser.browser autofillId=1 fieldId=-1 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], IncognitoMode = false, DeviceLocked = false
01-15 15:19:38.735  1477  9879 D AutofillInlineSuggestionsRequestSession: onInlineSuggestionsSessionInvalidated() called.
01-15 15:19:38.739  1477  9879 D AutofillInlineSuggestionsRequestSession: onInlineSuggestionsRequest() received: InlineSuggestionsRequest { maxSuggestionCount = 9, inlinePresentationSpecs = [InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }, InlinePresentationSpec { minSize = 126x154, maxSize = 840x154, style = Bundle[mParcelledData.dataSize=2796] }], hostPackageName = com.google.android.inputmethod.latin, supportedLocales = [de_DE,en_US], extras = Bundle[EMPTY_PARCEL], hostInputToken = android.os.BinderProxy@ea5888d, hostDisplayId = 0, inlineTooltipPresentationSpec = null }
01-15 15:19:38.741  1477  1477 V AutofillInlineSuggestionsRequestSession: maybeUpdateResponseToImeLocked called
01-15 15:19:38.741  1477  7379 V AutofillInlineSuggestionsRequestSession: onInputMethodStartInputView() received
01-15 15:19:38.750  1477  1477 V AutofillInlineSuggestionsRequestSession: maybeUpdateResponseToImeLocked called
01-15 15:19:38.757  1477  1477 V RemoteFillService: calling onFillRequest() for id=24
01-15 15:19:43.745  1477  1477 E RemoteFillService: Error calling on fill request
01-15 15:19:43.745  1477  1477 E RemoteFillService: java.util.concurrent.TimeoutException
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at com.android.internal.infra.AndroidFuture.triggerTimeout(AndroidFuture.java:290)
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at com.android.internal.infra.AndroidFuture$$ExternalSyntheticLambda0.run(Unknown Source:2)
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at android.os.Handler.handleCallback(Handler.java:938)
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at android.os.Looper.loopOnce(Looper.java:201)
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at android.os.Looper.loop(Looper.java:288)
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at com.android.server.SystemServer.run(SystemServer.java:902)
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at com.android.server.SystemServer.main(SystemServer.java:609)
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at java.lang.reflect.Method.invoke(Native Method)
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-15 15:19:43.745  1477  1477 E RemoteFillService:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
01-15 15:19:43.747  1477  1477 D AutofillSession: finishing session due to service timeout
01-15 15:19:43.747  1477  1477 V AutofillSession: removeFromServiceLocked(1331097331): null
01-15 15:19:43.748  1477  1477 D AutofillInlineSuggestionsRequestSession: onInlineSuggestionsResponseLocked called for:1:2724@1331097331
01-15 15:19:43.748  1477  1710 D AutofillUI: destroySaveUiUiThread(): already destroyed
01-15 15:19:43.749  1477  1477 V AutofillInlineSuggestionsRequestSession: maybeUpdateResponseToImeLocked called
01-15 15:19:43.749  1477  1477 D AutofillInlineSuggestionsRequestSession: maybeNotifyFillUiEventLoked(): hasSuggestionToShow=false, mPreviousHasNonPinSuggestionShow=false
01-15 15:19:43.749  1477  1477 D AutofillInlineSuggestionsRequestSession: Send inline response: 0
01-15 15:19:43.749  1477  1477 V AutofillSession: destroyLocked(): logging 1 requests
```

**Comment by itsmeboy0** [comment]
@m0vie  I have also noticed that the autofill does not work on GitHub but works on other sites. Please create a separate issue for it.

**Comment by 1Mark** [comment]
> @m0vie  I have also noticed that the autofill does not work on GitHub but works on other sites. Please create a separate issue for it.

I wouldn't track it using a separate issue since it's not a full fix. One issue should track it A-Z.

**Comment by itsmeboy0** [comment]
It works for me on other websites so 🤷, this is a specific bug.

**Comment by 1Mark** [comment]
> It works for me on other websites so 🤷 (unless it doesn't for you, do test it), this is a specific bug.

Also doesn't work on xda forums

**Comment by m0vie** [comment]
> @m0vie I have also noticed that the autofill does not work on GitHub but works on other sites. Please create a separate issue for it.

I've tried it on dozens of sites and it does not work on any of them - Chrome and Firefox on the other hand do work for all of them.

This is a general problem.

**Comment by C-O-D** [comment]
It worked quite nice here with KP2A before the last series of updates but now it's gone again completely.
The fact that it works with other browsers and has already worked with Kiwi shows that it must be a Kiwi problem and not an Android problem which can only be solved via ADB or am I missing something here?

**Comment by chirag127** [comment]
Not solved
