### ISSUE TITLE
Can't Remove kiwi://extensions

### ISSUE THREAD

**Issue by ArghyadeepMondal** [kiwibrowser/src.next#642]
**Describe the bug**
You can Add to Chrome Extensions  in Kiwi Browser 103.0.5060.59 but can't remove from Kiwi Browser.

**To Reproduce**
Remove any Extensions from kiwi://extensions .

**Expected behavior**
Work fine in Kiwi Browser 101.0.4951.57

**Screenshots**
![Screenshot_20220701_040553](https://user-images.githubusercontent.com/68646838/176792391-6c3c7ffa-7ddc-45b3-b908-c49c92286fb7.jpg)

**Smartphone :**
 - Device: [ Vivo Y91i (1820) ]
 - Android Version : [ Android 8.1.0 (Oreo) ]
 - Kiwi Browser Version [ C103.0.5060.59-Kiwi Stable/Dev/ARM/ARM64 - G2581156208; G2582063817; G2582441223 ]

**Additional context**
It looks normal in Kiwi Browser 101.0.4951.57 & Geometry OU Kiwi 101- .

**Comment by kiwibrowser** [comment]
Fixed, deployment in progress

**Comment by ArghyadeepMondal** [comment]
> Kiwi Browser_G2593424697_C103.0.5060.101 this version is bugy. After update my Kiwi Browser from G2582441223_C103.0.5060.59 to G2593424697_C101.0.5060.101. When go Chrome Web Store (https://chrome.google.com/webstore/) & add any extensions to Kiwi Browser it's restart my Kiwi Browser look like crash my Kiwi Browser. Please Fix! Best Regards for response my comment & quick releases new version of Kiwi. Inteligent & Professional Team Work!🎉 Have a nice day...

![Screenshot_20220701_071445](https://user-images.githubusercontent.com/68646838/176806191-4f3511a8-2932-4d1c-9a90-b89cb6615cbe.jpg)
me send this report to Geometry OU Developer using kiwi://crashes/ local-urls.
