### ISSUE TITLE
Bottom toolbar overlays tab-bar

### ISSUE THREAD

**Issue by Charles7z** [kiwibrowser/src.next#658]
When  bottom toolbar is set along with tab switcher set to grid the bottom toolbar lays over the tab bar.

Set toolbar to bottom
Set tab switcher to grid
Restart
Open multiple tabs in same group
Result: tab bar will not appear above the bottom toolbar as it does on other chrome variants = no visible tab bar.

**Expected behavior**
It is expected that both the tab bar and toolbar are visible when using tab groups as they are when the toolbar is set to top, see images.

**Smartphone:**
 - Device: Moto G Power 2021
 - Android Version : 11
 - Kiwi Browser Version: Kiwi Browser_103.0.5060.104, Generation 2703759296

Attempted fixes:
Adjusted appropriate flags, no changes
Set toolbar to always show, no change
Restarts, clearing cache, no change

This screenshot shows normal behavior for top toolbar with tab groups active.

![top toolbar with tabbar](https://user-images.githubusercontent.com/103839039/181078352-dee47c62-f5f3-46fd-aa92-a5d16b6212a5.png)

Screenshot showing tab group.

![showing tab groups are active](https://user-images.githubusercontent.com/103839039/181078436-a5ef039e-3bf2-473e-9538-cd5d19d2766a.png)

Screenshot showing bottom toolbar hiding the same tab bar group from first screenshot.

![bottom toolbar](https://user-images.githubusercontent.com/103839039/181078485-73b7d5b0-ac50-4fe2-8a51-09163bd5b396.png)

**Comment by d3ward** [comment]
Kiwi v116 no longer has this problem. Now when the bottom toolbar is enabled and the tab switcher with groups is enabled, the tab-strip works as expected
