### ISSUE TITLE
Auto fill password do not work 

### ISSUE THREAD

**Issue by Titanposeidon** [kiwibrowser/src.next#659]
on early versions i was using safein cloud password manager with kiwi browser in success for auto fillimg but on last version it doesnt work
i tried to clear all data base, reuploaded again but still doesnt work
it is really important for using

pls advice for fix

**Comment by Ibuprophen** [comment]
@Titanposeidon, did you go to the Settings, select Passwords and then turn on the top 2 options? 

~Ibuprophen

**Comment by Titanposeidon** [comment]
@Ibuprophen sure i tried

**Comment by Titanposeidon** [comment]
sure i tried but doesnt work

**Comment by Ibuprophen** [comment]
Sorry that it wasn't a solution for you as I have no problem with this feature myself.

That's all I can personally think of and hopefully someone can chime in to help you resolve this. 

@kiwibrowser? 

~Ibuprophen

**Comment by Titanposeidon** [comment]
i just re uploaded old version which is 2275000710, auto fill passwords working with safein cloud password manager, pls fix on last release

**Comment by C-O-D** [comment]
I also think it's a super shame that it no longer works with KP2A. It must be a kiwi problem, because as mentioned in other comments it has worked some versions before and with Firefox it works as well...

**Comment by Titanposeidon** [comment]
yes its really annoying, all my passwords on my app but always trying to go out of browser, checking on password app, then copy then go back to kiwi browser...
on new version its not working still, i am sure developer will fix the issue soon

**Comment by C-O-D** [comment]
> yes its really annoying, all my passwords on my app but always trying to go out of browser, checking on password app, then copy then go back to kiwi browser... on new version its not working still, i am sure developer will fix the issue soon

I rather think that the developers believe the problem is not Kiwi based but hopefully I'm wrong about this...

**Comment by kiwibrowser** [comment]
Understood, it's clear I'll compare 2275000710 and current version and prepare a fix for Autofill

**Comment by C-O-D** [comment]
> Understood, it's clear I'll compare 2275000710 and current version and prepare a fix for Autofill

WOW! Thanks a lot 👍

**Comment by Titanposeidon** [comment]
> Understood, it's clear I'll compare 2275000710 and current version and prepare a fix for Autofill

thanks sounds great

**Comment by Titanposeidon** [comment]
> Understood, it's clear I'll compare 2275000710 and current version and prepare a fix for Autofill

Just to inform with the last update, 2884965778, still doent work, fyi @kiwibrowser

**Comment by kiwibrowser** [comment]
I am trying a new fix, I think it will be ready in one hour :)

**Comment by Titanposeidon** [comment]
> I am trying a new fix, I think it will be ready in one hour :)

on last realese, its working! thanks for your effort and the fix

**Comment by C-O-D** [comment]
> I am trying a new fix, I think it will be ready in one hour :)

Thanx for the fix, you made my life better! 🙂
