### ISSUE TITLE
Add support for getDisplayMedia(.) in WebRTC for screen sharing within kiwi browser 

### ISSUE THREAD

**Issue by Sujan319** [kiwibrowser/src.next#665]
**Is your feature request related to a problem? Please describe.**
++ When I want to share screen from my browser, it says 'permission denied' or  ' your browser can't share your screen'.

**Describe the solution you'd like**
++ Add support for getDisplayMedia(.) in WebRTC.
++ Implement using Screen Capture API.
++ Here is the reference for [getDisplayMedia(.)](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) and [Screen_Capture_API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture)

**Additional context**
![IMG_20220809_091206](https://user-images.githubusercontent.com/67813061/183560349-daf56bdb-471a-490b-b57e-0044456e1f11.jpg)

**Comment by JacenBridger** [comment]
Interesting 🤔 (https://chromium-review.googlesource.com/c/chromium/src/+/2495823/3)

**Comment by Sujan319** [comment]
After some searches, here & there, Good news is, I find a working developer build 88.0.4306.0 after turning the Screen Capture API flag on. 
![20220810_000244_120323](https://user-images.githubusercontent.com/67813061/183736509-9010c00a-f3a9-4263-9c31-8be7dddad54e.jpg)
+
![IMG_20220810_000943](https://user-images.githubusercontent.com/67813061/183736626-791c97f3-36ef-4c7b-896a-b5357add436f.jpg)
+
![IMG_20220810_001005](https://user-images.githubusercontent.com/67813061/183736780-41719877-7255-42c5-8c3b-ae6f933c022d.jpg)
+
![IMG_20220809_235554](https://user-images.githubusercontent.com/67813061/183736974-ae83842e-7bd0-44df-85ed-6ebbeab8c64f.jpg)

but the bad news is it works only for Android (<10) devices and flag is expired.

**Comment by Sujan319** [comment]
Upstream related
