### ISSUE TITLE
Playstore releases missing in assets

### ISSUE THREAD

**Issue by lje** [kiwibrowser/src.next#673]
From the documention: Once in a while, we send a "-github.apk" build to be reviewed and signed by Google. Google reviews the application, checks that the application is not malicious, adds the "Google Play Certified" badge, signs the file and this becomes "-playstore.apk".

I checked all releases for this project and the only "-playstore.apk" assets are from 2021-07-31 (com.kiwibrowser.browser-457702115-playstore.apk) and 2021-07-22 (com.kiwibrowser.browser-1057018260-arm64-playstore.apk).
There are no playstore releases published after July 2021. Since the last release in play store is from August 2022 (more than one year later), where are all the new "-playstore.apk" files?

**Comment by d3ward** [comment]
As the document says ...."once in a while", it's something rare that requires urgent updates for users who have a PlayStore version with a critical bug.
