### ISSUE TITLE
[FIXED] Key pop-up issues... 

### ISSUE THREAD

**Issue by Ibuprophen** [kiwibrowser/src.next#674]
After installing the following (recent) pre-release.. 

https://github.com/kiwibrowser/src.next/releases/tag/2878862993

... The password key pops up whenever I'm in a text field most (if not all) the time. 

The following image reflects an example of what I'm referring to... 

[Kiwi Browser - Password Field Popup](https://user-images.githubusercontent.com/18060271/185484324-7b7d3082-8862-423c-8ee8-97bd100e2fe1.jpg)

... and has never done this (to me) before. 

Also, when I'm in a field that does require a username and/or password, the auto fill pop up works (for me) without any issues. 

Thank you very much for your time and understanding with this issue and I'm hoping for a solution on the next release (or some guidance as to prevent this from happening). 

Please let me know if you require any further information. 

~Ibuprophen

**Comment by kiwibrowser** [comment]
I worked on a fix for this today, in the very last build, could you please check if the issue is resolved for you ? (when I tested it was)

**Comment by MooShuOrc** [comment]
The "key" is gone for some text boxes, but not all. For example, the search box on http://duckduckgo.com

**Comment by Ibuprophen** [comment]
@kiwibrowser, It (unfortunately) didn't fix the issue at all for me as it's present in every site I go to like Google, Ancestry, Github, etc... 

I also noticed that the "Next NTP" crx extension I was using via the following link... 

https://github.com/d3ward/nextntp

... stopped working as well. 

If you feel it necessary, I can Uninstall the browser and reinstall it using your most recent pre-release. 

I'm not sure if the issue(s) may be carrying over from the one release to the other. 

It may be a bit of a pain to set up again, but the issues may (hopefully) be resolved. 

I'll await your advice/guidance with this decision my friend as I'd hate to go dive off that pier (so to speak) unnecessarily. 

~Ibuprophen

**Comment by C-O-D** [comment]
The key pops up in nearly every input field here, version 2891278039-arm64

**Comment by Ibuprophen** [comment]
Oy Vey... Now my bookmarks just disappeared on top of the other issues @kiwibrowser... :-(( 

~Ibuprophen

**Comment by Ibuprophen** [comment]
Forgotten to mention about the bookmarks @kiwibrowser... 

I even tried to import them from a backup. 

They will show until I exit the browser and open it again. Then they're all gone again. 

This level of issues are making it frustrating even for a developer like myself. 

~Ibuprophen

**Comment by kiwibrowser** [comment]
I managed to reproduce the bookmarks issue, somehow the interface fails to save the changes, I'm investigating the issue

**Comment by Ibuprophen** [comment]
Thank you very much for a quick response and a heads up @kiwibrowser. 👍 

~Ibuprophen

**Comment by Ibuprophen** [comment]
> @kiwibrowser, It (unfortunately) didn't fix the issue at all for me as it's present in every site I go to like Google, Ancestry, Github, etc...
> 
> I also noticed that the "Next NTP" crx extension I was using via the following link...
> 
> https://github.com/d3ward/nextntp
> 
> ... stopped working as well.
> 
> If you feel it necessary, I can Uninstall the browser and reinstall it using your most recent pre-release.
> 
> I'm not sure if the issue(s) may be carrying over from the one release to the other.
> 
> It may be a bit of a pain to set up again, but the issues may (hopefully) be resolved.
> 
> I'll await your advice/guidance with this decision my friend as I'd hate to go dive off that pier (so to speak) unnecessarily.
> 
> ~Ibuprophen

Just an FYI regarding this matter... 

I had just found out how to get this specific issue I had going again using an alternative route (via another extension) that, I'm hoping, will keep on working. 

~Ibuprophen

**Comment by Ibuprophen** [comment]
@kiwibrowser, can you please provide me with a quick heads-up regarding a release that addresses both the Bookmarks & Key pop-up issue? 

Thanks a Bunch My Friend! 👍 

~Ibuprophen

**Comment by Ibuprophen** [comment]
@kiwibrowser, please give some great news regarding a release that (at least) addresses the Bookmarks issue. 

Thanks a Bunch My Friend! 👍

~Ibuprophen

**Comment by htsmi** [comment]
Would it be possible to separate the two issues being discussed here? I have been experiencing the "key" symbol popup on many non-login text boxes as of several releases ago and it takes up a lot of space for no reason. I am now on version 105.0.5195.33. I don't recall ever seeing it in Kiwi before around mid August. I use an external password manager with Android autofill and I have "save passwords" turned off in settings, so I don't think there's a reason for it to show up at all for me.

**Comment by Ibuprophen** [comment]
It appears that the recent release of the browser seems to have resolved the Key Pop-up issue. 

Thanks a Bunch @kiwibrowser! 👍 

~Ibuprophen

**Comment by C-O-D** [comment]
Big thanks from me too 👍🥂
