### ISSUE TITLE
Download popup dialog appears only at the second attempt of the file to be downloaded

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src.next#68]
When I open "Ask when to save files" and "Ask where to save files", but there is no prompt. Download it directly.

**Comment by Lartsch** [comment]
This bug is present for me as well.

**Comment by Lartsch** [comment]
Apparently the dialogue appears when downloading a file for a second time (overwrite dialogue), but not for first downloads

**Comment by d3ward** [comment]
This bug is also present in recent v98 builds

**Comment by C-O-D** [comment]
Here too but only on Samsung tablet, smartphone works correctly. Does this make any sense?

**Comment by biggestsonicfan** [comment]
Was this bug ever fixed? Seems to still be an issue.

**Comment by d3ward** [comment]
With latest Kiwi v116 . The option "Ask where to save files" seems to work as expected.
