### ISSUE TITLE
Tabs reload every time on exiting the browser

### ISSUE THREAD

**Issue by MmyGgithubAaccount** [kiwibrowser/src.next#69]
Like the title says, tabs reload every time I leave the browser. I don't even have to leave for a long time. Just going to recents and immediately opening the app again makes the tabs reload
This makes it impossible to log into websites because I use a password manager and have 2fa active almost everywhere and leaving the app to copy login credentials/2fa code makes the tab reload making me restart the login process again
The only workaround I've discovered for this is using the browser in split screen which prevents it from reloading
I'm on an aosp based custom rom running Android 11

**Comment by MmyGgithubAaccount** [comment]
Update: seems to be fixed with latest release

**Comment by temporarium** [comment]
It's still not working on my Android 7.1.2 tablet with Kiwi v93.0.4577.11.
Tabs reload every time they're selected or a link is opened in another tab.

Should I open another issue? Do you need more info?

**Comment by MmyGgithubAaccount** [comment]
Re-opening since others still seem to have this issue

@temporarium do you see this issue in other chromium based browsers as well?

**Comment by kiwibrowser** [comment]
FYI I have the same issue with Chrome stable, so I guess we have to figure out what's going on there

**Comment by MmyGgithubAaccount** [comment]
Could this be because of bfcache occupying a lot of ram and unloading tabs on low memory devices? @temporarium and @kiwibrowser maybe you could try disabling bfcache in flags and see if the situation improves

If this happens on chrome stable as well it might be better to report it in the chromium bug tracker so it gets fixed upstream

**Comment by kiwibrowser** [comment]
ok I'll experiment and tell you

**Comment by temporarium** [comment]
I discovered that this (reloading a tab on switchi to it or opening a link in a new tab) happens when I have **"Desktop mode by default" enabled**. With it disabled, it behave scorrectly.

**Comment by kiwibrowser** [comment]
@temporarium I experimented actually, and rolled-out a fix, I hope it's fine in the latest build (coming on Play Store as .20)

**Comment by temporarium** [comment]
Confirmed to work correctly now. Thanks for an excellent browser!!
