### ISSUE TITLE
Allow synchronization with Google.

### ISSUE THREAD

**Issue by rokejulianlockhart** [kiwibrowser/src.next#694]
**Is your feature request related to a problem? Please describe.**

I am unable to synchronize my browsing-information via Kiwi despite being able to via Chrome for Android.

**Describe the solution you'd like**

What the title describes.

**Describe alternatives you've considered**

The sole alternatives—synchronization with Mozilla, or custom synchronization—are probably similarly difficult to implement due to the incompatibility and potential terms-of-service violations necessary to synchronize such information with Mozilla, and the cost and time necesssry to maintain custom infrastructure.

**Additional context**

  This is part of every edition, version, and iteration of Chrome, although not Chromium (anymore?).
  I know that this is partially possible for other browsers to implement, because [Microsoft Edge recently did](https://www.androidpolice.com/microsoft-edge-import-browser-chrome-each-launch/). That should additionally demonstrate that this is possible to achieve without repercussion (the ToS obviously allows it) because Google would not allow them to otherwise!

<details>

*  https://www.google.com/search?q=kiwi+browser+sync+with+google

    *  https://support.google.com/chrome/thread/172310810?hl=en

*  https://www.google.com/search?q=kiwi+browser+sync+with+google+site:www.reddit.com

    *  https://www.reddit.com/r/kiwibrowser/comments/w192vj/sync_bookmarks/
    *  https://www.reddit.com/r/kiwibrowser/comments/x0600q/sync_kiwi_app_on_my_android_into_chromes_bookmarks/
    *  https://www.reddit.com/r/androidapps/comments/c0zh96/is_it_possible_to_sign_into_the_kiwi_browser/
    *  https://www.reddit.com/r/kiwibrowser/comments/l1b1ha/how_can_i_get_my_bookmarks_to_sync_across_devices/
    *  https://www.reddit.com/r/kiwibrowser/comments/tvvogo/how_do_you_sync_your_bookmarks_with_chrome/
    *  https://www.reddit.com/r/kiwibrowser/comments/140v5uh/sync_kiwi_history_to_google_account_or_chrome_and/
    *  https://www.reddit.com/r/kiwibrowser/comments/xqzx0w/online_sync_between_kiwi_browser_to_chrome/
    *  https://www.reddit.com/r/kiwibrowser/comments/14733m2/how_to_sync_from_chrome_to_kiwi_browser_android/
    *  https://www.reddit.com/r/kiwibrowser/comments/xoqfo3/is_there_a_possibility_to_sync_history_between/
    *  https://www.reddit.com/r/kiwibrowser/comments/y14luf/how_can_i_transfer_my_data_from_chrome_to_kiwi/

demonstrate that this feature has been frequently requested.

**Comment by gnadelwartz** [comment]
This is prohibited by Google, no chromium based browser is allowed to sync, only original Google chrome

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@gnadelwartz, in which case, how does Microsoft's Edge perform this? I believe that my citation demonstrates that it possesses such capability.

**Comment by gnadelwartz** [comment]
Import chrome bookmarks and tabs on every start does not mean sync with Google account, but others may now better.

**Comment by d3ward** [comment]
I close this, as it is not possible to use Google for sync.

**Comment by rokejulianlockhart** [comment]
@d3ward, then close as not planned rather than completed.
