### ISSUE TITLE
Bottom bar blocks part of the page 

### ISSUE THREAD

**Issue by hhjeremy** [kiwibrowser/src.next#7]
The bottom bar makes the bottom part of a page unclickable and it also blocks some part of the page. 
![Screenshot_20210703-071414_Kiwi Browser (Next)](https://user-images.githubusercontent.com/18645822/124342855-ca14b500-dbcf-11eb-916a-b79a403a457e.jpg)

**Comment by mycal123** [comment]
Yeah same here, so temporary i m using fullscreen script

**Comment by d3ward** [comment]
This it's fixed with latest versions
