### ISSUE TITLE
View source option

### ISSUE THREAD

**Issue by gokulraam** [kiwibrowser/src.next#70]
Is view source option available?. Could not find it in the menu.

**Comment by Lartsch** [comment]
You can use the Developer Tools (from Kiwi's 3-Dot-Menu) to see source, but it is not yet optimized for easy usage as of now.

Please close this issue if your question is answered therefore. @gokulraam

**Comment by KaKi87** [comment]
"View source" can also be accessed by opening the address bar and prefixing the current URL with `view-source:`.
Considering that DevTools is indeed implemented, I don't think that a *View source* menu would be worth it.
I'll close the issue, but feel free to express yourself if you have additional arguments and we might reopen it.
