### ISSUE TITLE
Monet theme disappeared from home screen 

### ISSUE THREAD

**Issue by soymadip** [kiwibrowser/src.next#700]
**Describe the bug**
In the latest build, Monet theme disappeared from homescreen and tool bar 

**To Reproduce**
Open browser, see the tool bar(must have A12 for material you theme)

**Expected behavior**
Tab bar also should be themed
**Screenshots**
![Screenshot_2022-08-29-16-33-05-91_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/84225810/187191116-39ee2439-0a97-4dcc-b311-6d6754c7c1c4.jpg)

**Smartphone (please complete the following information):**
 - Device: [realme narzo 30]
 - Android Version : [A12 ]
 - Kiwi Browser Version: 105.0.5195.33

**Comment by soymadip** [comment]
Settings panel is as themed as before 
![Screenshot_2022-08-29-16-58-56-51_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/84225810/187191455-5c63aea2-bb7d-40f8-9239-09ea8119f94d.jpg)

**Comment by kiwibrowser** [comment]
Hello,

I resolved the issue, the fix will be deployed with the upcoming build (in a couple of hours)

<img width="1688" alt="Screenshot 2022-08-29 at 14 38 20" src="https://user-images.githubusercontent.com/40272275/187192841-08102422-a056-4c75-9c66-29b0c432995d.png">

**Comment by soymadip** [comment]
> Hello,
> 
> I resolved the issue, the fix will be deployed with the upcoming build (in a couple of hours)
> 
> <img alt="Screenshot 2022-08-29 at 14 38 20" width="1688" src="https://user-images.githubusercontent.com/40272275/187192841-08102422-a056-4c75-9c66-29b0c432995d.png">

Thanks a lot sir
