### ISSUE TITLE
Allow to set desktop/mobile mode per site

### ISSUE THREAD

**Issue by NuraliMedeu** [kiwibrowser/src.next#713]
**Is your feature request related to a problem? Please describe.**
Currently, when a user sets desktop sites to open by default, all sites (even those which do not work with touchscreens) open in desktop mode. While it's possible to open the mobile version of a problematic site by unchecking "Desktop site" in the tab menu, this setting is saved only for that tab, not for the site. This means that every time the site is opened in another tab, it loads its desktop version and the user has to uncheck "Desktop site" to use it, which is annoying.

**Describe the solution you'd like**

Make an option to save desktop/mobile mode for individual sites in settings and save the "Desktop site" toggle per site as opposed to per tab.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by NuraliMedeu** [comment]
I found a solution in the form of an extension called [User-Agent Switcher for Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg) . However, I will not close this issue as I think the feature I proposed must be supported natively.

**Comment by karl-pae** [comment]
Not possible.

**Comment by NuraliMedeu** [comment]
If it's not possible, explain why in at least one sentence.

**Comment by kyoyacchi** [comment]
> Not possible.

Why?

**Comment by NuraliMedeu** [comment]
@karl-pae care to explain?

**Comment by karl-pae** [comment]
I can only say is, it's very small feature to be implemented in browser for some 5% -7% users.. 

You can either search for such extensions or may be build your own. It's pretty easy, if you know js. 😉

**Comment by NuraliMedeu** [comment]
Ok, thanks.

**Comment by d3ward** [comment]
With v116 , now the desktop mode check box is working on per site criteria .
