### ISSUE TITLE
Extension icons in overflow menu are monochrome

### ISSUE THREAD

**Issue by MmyGgithubAaccount** [kiwibrowser/src.next#72]
This makes it impossible to view extra information those icons might display e.g. number of blocked elements per page for ublock, number of running userscritpts for tampermonkey, etc
It also makes it difficult to distinguish between the extensions with a quick glance

**Comment by Lartsch** [comment]
Yep, not critical imo but it sure limits some usability. Maybe this one can be sorted out all in one with the patch I mentioned in #74

**Comment by karl-pae** [comment]
With recent builds the bug/issue has been solved. Issue can be closed now.
