### ISSUE TITLE
Tabs' names not updating

### ISSUE THREAD

**Issue by Blank-c** [kiwibrowser/src.next#720]
**Describe the bug**
Tabs' names won't change after first search after every startup

**To Reproduce**
1) Open Kiwi Browser.
2) Search something.
3) Search something else.
4) Press the recent tabs button.
5) Look at the tabs' names.

**Expected behavior**
Tabs' names should have changed.

**Screenshots**
![Oh-Greate-Heavens!](https://user-images.githubusercontent.com/94945186/192136592-aa2f77ea-10a7-4258-9211-7e66dbfb1447.png)

**Smartphone:**
 - Device: Oppo A83 (CPH1729)
 - Android Version : 7.1.1
 - Kiwi Browser Version: 105.0.5195.33

**Comment by karl-pae** [comment]
Duplicate #706.

**Comment by Blank-c** [comment]
Duplicate of #706

**Comment by karl-pae** [comment]
#706 has been resolved.
