### ISSUE TITLE
Media Query is inaccurate

### ISSUE THREAD

**Issue by bershanskiy** [kiwibrowser/src.next#725]
**Describe the bug**
Media Query `prefers-color-scheme` does not represent system color scheme.

**To Reproduce**
1. Set device system theme to dark
2. Set Kiwi theme to match system theme and Night theme to Default (and observe that Kiwi UI is dark)
3. Open https://jsconsole.com/ or browser Developer Tools (whichever is more convenient)
4. Run `matchMedia('(prefers-color-scheme: dark)').matches` and observe that returned value is `false`
5. Run `matchMedia('(prefers-color-scheme: dark)').onchange = console.log`, change system theme to light, go back to page, then change system theme to dark again and go back to page, observe that color change events were not delivered

**Expected behavior**
In step 4 system theme should be dark so the returned value should be `true`. In step 5 system theme changed twice, so there should be two change events (to `false` and then to `true`).

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE, 
 - Android Version : Android 12, Android 11
 - Kiwi Browser Version 105.0.5195.33

**Additional context**
This bug prevents users of [Dark Reader](https://https://darkreader.org/) from using our "system automation" feature which enabled Dark Reader when system is set to dark. I might have time to prepare a PR to fix this issue, if you would be interested in reviewing it.

**Comment by kiwibrowser** [comment]
O.o
You found something I was looking for days, I actually implemented a completely different flow by adding an extra parameter to the renderer "IsDarkUi"

Let me try to make a build with the code and share with you the APK
It should take about an hour

**Comment by bershanskiy** [comment]
> Let me try to make a build with the code and share with you the APK

That would be great!

Also, how do I see the official branched rebased on top of Chromium 107? I see only `src.next` with branch `kiwi` which is last updated on August 29 with Chromium 105.

**Comment by bershanskiy** [comment]
@kiwibrowser It seemed weird that this patch worked, since it just introduces a function which would need to be called by something else. I just tested Chromium 107 without this patch and it appears to support `prefers-color-scheme`. I'm not sure which commit introduced this feature, but it landed within the last few days (tentatively Oct 9 or Oct 10). After all, this patch is not needed after all.

**Comment by bershanskiy** [comment]
I believe this is not a Chromium bug, but a Kiwi-specific bug, I'm still looking into it.

**Comment by kiwibrowser** [comment]
What I can try to do, is if you suspect a fix was pushed in the last days, is to retry a rebase (anyway I need to re-roll a deploy of the release because the crash rate is too high) on an even more recent 107.x version.
After that, I could also check if all the changes that are Kiwi specific for Media Queries (there is a few actually) are properly pushed so you can see what logic is applied

I'll work on the rebase tomorrow

**Comment by bershanskiy** [comment]
> What I can try to do, is if you suspect a fix was pushed in the last days, is to retry a rebase (anyway I need to re-roll a deploy of the release because the crash rate is too high) on an even more recent 107.x version.

I tested Google Chrome 106.0.5249.79 and it supports Media Queries right now, so rebasing on 107 probably won't do anything.

> After that, I could also check if all the changes that are Kiwi specific for Media Queries (there is a few actually) are properly pushed so you can see what logic is applied

It would be nice to see only the diff, is there a more convenient way to do it besides checking out `src.next` and an equivalent Chromium revision in separate folders and diffing them?

**Comment by bershanskiy** [comment]
This bug was fixed upstream and Kiwi works fine now.
