### ISSUE TITLE
Microsoft Autofill on kiwi

### ISSUE THREAD

**Issue by IcedWatermelonJuice** [kiwibrowser/src.next#747]
The "Microsoft AutoFill" extension does not work properly on kiwi browser.
Is there a plan for kiwi to support this extension in the future?

**Comment by d3ward** [comment]
Can you provide more info of what is not working ?

**Comment by IcedWatermelonJuice** [comment]
Sorry, I haven't used this browser for a long time, so I can't provide more info

**Comment by d3ward** [comment]
Closing this then . If you will be back to Kiwi and still face the issue feel free to re-open the ticket with details .
