### ISSUE TITLE
About hiding toolbars when pulling down

### ISSUE THREAD

**Issue by iKineticate** [kiwibrowser/src.next#749]
Because the mobile phone opens the barrier free mode that needs to simulate gesture clicking, the toolbar cannot be hidden when scrolling。I hope this problem can be optimized. Thank you。

**Comment by d3ward** [comment]
Hide toolbar when scrolling works as expected.  You have to check the support of special gestures that cannot be handled by Kiwi
Feel free to re-open and provide more details if issue persist
