### ISSUE TITLE
Bottom toolbar option is missing in tablet devices.

### ISSUE THREAD

**Issue by Nikhil9335** [kiwibrowser/src.next#750]
The bottom toolbar option in Toolbar setting is missing in tablet devices and because of this, the **_Hand Button (works only with the bottom toolbar)_** option is also missing which is very useful to bypass ads.

 1- ![Screenshot_20221028-135652_Kiwi Browser_1](https://user-images.githubusercontent.com/90768182/198542150-9acff2c2-7a4c-468e-856b-edbee49a293e.png)
2-
![Screenshot_20221028-140124_1](https://user-images.githubusercontent.com/90768182/198542391-8ea33b54-bb5d-488f-a5a4-1aa69fe63ae0.png)

 - Device: Xiaomi Pad 5 
 - Android Version : Tested on A11, A12
 - Kiwi Browser Version 107.0.5304.72

If this can't be fixed, then atleast bring the Hand Button on top toolbar, it's very useful. **Thanks Devs!** 🔥

**Comment by d3ward** [comment]
#198
