### ISSUE TITLE
Kiwi Browser Feature Recommendation

### ISSUE THREAD

**Issue by qingwan123** [kiwibrowser/src.next#761]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

First of all, I was just inspired to feel that this function is very user-friendly, and in line with the mobile browser mode of operation.

I am a user from China and I like kiwi very much.

I want Android to come up with a tablet mode that can be switched on and off according to the user's needs.

![Screenshot_2022-11-24-09-05-38-94_1526bbe67bba6d33b86f0f3237fecb5d](https://user-images.githubusercontent.com/101662989/203671952-d4273aa8-8dcb-4b33-8efc-9fe1a7704af2.jpg)

UIAs above, this is just a personal suggestion, if it is difficult to implement, or if other users object. You can also not update.

**Comment by kyoyacchi** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> **Describe the solution you'd like**
> 
> **Describe alternatives you've considered**
> 
> **Additional context**
> 
> First of all, I was just inspired to feel that this function is very user-friendly, and in line with the mobile browser mode of operation.
> 
> I am a user from China and I like kiwi very much.
> 
> I want Android to come up with a tablet mode that can be switched on and off according to the user's needs.
> 
> ![Screenshot_2022-11-24-09-05-38-94_1526bbe67bba6d33b86f0f3237fecb5d](https://user-images.githubusercontent.com/101662989/203671952-d4273aa8-8dcb-4b33-8efc-9fe1a7704af2.jpg)
> 
> UIAs above, this is just a personal suggestion, if it is difficult to implement, or if other users object. You can also not update.

May I ask what's the name of the browser you are using in ss?

**Comment by qingwan123** [comment]
> @qingwan123 请问你用的ss浏览器叫什么名字？

I am from China, and this browser is domestic. It's called Yujian browser. I don't know if you can download it.

**Comment by kyoyacchi** [comment]
> > @qingwan123 请问你用的ss浏览器叫什么名字？
> 
> I am from China, and this browser is domestic. It's called Yujian browser. I don't know if you can download it.

https://play.google.com/store/apps/details?id=com.yjllq.internet This one?

**Comment by d3ward** [comment]
#146
