### ISSUE TITLE
应用跳转

### ISSUE THREAD

**Issue by Dreammak1r** [kiwibrowser/src.next#771]
点击网页会跳转到浏览器外的第三方应用，这个太烦人了，反正华为手机是这样，希望改进一下，给用户一个选择的空间。

**Comment by Avenzhao** [comment]
for this problem you should contact the admin of the website

**Comment by Dreammak1r** [comment]
> 对于这个问题，您应该联系网站的管理员

您说的是会跳转外部应用的那些网站的管理员吗？那显然是不现实的，因为不只是单个网页会跳转，而是很多网页都会跳转外部应用，例如m.iqiyi.com,m.bilibili.com......所以我觉得开发团队可以在kiwi浏览器里加入一个功能“阻止网页跳转外部应用”，像狐猴浏览器那样，就不会直接跳转外部应用了。
