### ISSUE TITLE
Black toolbar

### ISSUE THREAD

**Issue by person10301** [kiwibrowser/src.next#775]
Everything is dark gray, but the panel is black
![Screenshot_2022-12-10-20-55-18-01_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/105549221/206868842-d6745906-84ad-4a76-8a02-e8a9b431290c.jpg)

**Comment by d3ward** [comment]
The latest v116 brought back the amoled theme. Now everything is consistent.
