### ISSUE TITLE
A POTENTIAL BUT FATAL BUG

### ISSUE THREAD

**Issue by Emperormummy** [kiwibrowser/src.next#777]
**Describe the bug**
input "kiwi://settings/system"on serach bar can enter a kiwi browser settings page,I carelessly close the "Hardware Acceleration"option and relaunched kiwi,then kiwi crash immediately and can't enter again from that time...
![IMG_20221212_125804](https://user-images.githubusercontent.com/68811535/206964539-b91ea014-bacd-4295-9b13-2017b9776eb1.jpg)

I tried to reboot my phone and clear cache,it doesn't work......
The last way to solve this is force open the Hardware Acceleration and ban this potential page...

**Smartphone (please complete the following information):**
 - Device: [Redmi K50,Mi 10 Pro,Realme X50 Pro Gaming]
 - Android Version : [A12]
 - Kiwi Browser Version [107.0.5304.74 ]
 
Input settings/system on Chrome Mobile APP can't enter the potential page.

**Comment by kylprq** [comment]
can confirm thiy

**Comment by kiwibrowser** [comment]
Fix is ready it will be in +/- 1 hour

**Comment by kylprq** [comment]
May completely blocking kiwi://settings page like android chrome? (chrome://settings returns "This site can’t be reached") cause hardware acceleration is not the only one. ty for awesome project ☺️

**Comment by Emperormummy** [comment]
It fixed on 111.0.5563.73

**Comment by Emperormummy** [comment]
> 

i approve block this page

**Comment by kylprq** [comment]
> > 
> 
> i approve block this page

still same on kiwi://settings page
