### ISSUE TITLE
The tab does not have obvious active signs on the PAD

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src.next#78]
When the Kiwi browser is running on the PAD, the tab does not have obvious active signs, causing me not know which tab open. as the picture shows.
![Screenshot_20210723_102543_com kiwibrowser browse](https://user-images.githubusercontent.com/55195642/126731274-6e0f53a4-bf1a-4b36-8f13-d6d42fab6ab2.png)

**Comment by d3ward** [comment]
This issue has been fixed , not sure when but recent updates doesn't have that bug. 
@drc5521 if you still face the issue consider reopening the issue with more specific details like device , android version, etc

**Comment by drc5521** [comment]
Unfortunately, the problem still exist.
Device:HuaWei MatePad10.8
Android version: Android 10
