### ISSUE TITLE
[BUG] double mirror loading animation(bottom toolbar) when opening webpage *in app*

### ISSUE THREAD

**Issue by kryptobolt200528** [kiwibrowser/src.next#79]
![Screenshot_2021-07-23-11-56-01-98](https://user-images.githubusercontent.com/72438196/126744751-63505ad0-c582-4f13-ac0a-9a069a47383c.jpg)

**Comment by kiwibrowser** [comment]
Hello,

Does the issue still exist ? (I wasn't able to reproduce it)

Thank you,

**Comment by d3ward** [comment]
This issue should be closed considering the bug was on v90 , lack of user details and now Kiwi it's on v98
