### ISSUE TITLE
Implement Autoplay blocking in site settings

### ISSUE THREAD

**Issue by JacenBridger** [kiwibrowser/src.next#790]
**Is your feature request related to a problem? Please describe.**

--> Autoplay video incurs high data usage, thus creating trouble for user with limited data pack.

**Describe the solution you'd like**

--> There should be an option in site settings namely "Autoplay blocking" to block video which play automatically.

**Describe alternatives you've considered**

--> [AutoplayStopper](https://chrome.google.com/webstore/detail/autoplaystopper/ejddcgojdblidajhngkogefpkknnebdh?hl=en) is one such extension, that can be used as alternative. But if browser does it natively, thats much more effective & preferable.

**Comment by d3ward** [comment]
#150
