### ISSUE TITLE
PWA is black

### ISSUE THREAD

**Issue by kuxv** [kiwibrowser/src.next#797]
**Describe the bug**
For some reason the PWA in kiwi is mostly black.

**To Reproduce**
Open PWA like https://gloomhaven-secretary.de/

**Expected behavior**
It shouls look the same as if opened as web page.

**Screenshots**
broken PWA in kiwi:
![Screenshot_20230110-165231_Kiwi Browser](https://user-images.githubusercontent.com/3008023/211740219-cac070bb-e22b-4fb4-af64-88e53e292fba.png)

correct web page in kiwi:
![Screenshot_20230110-165416_Kiwi Browser](https://user-images.githubusercontent.com/3008023/211740526-72b6b9b3-b382-43d1-936f-875f968e754e.png)

correct PWA in firefox:
![Screenshot_20230110-165336_Firefox](https://user-images.githubusercontent.com/3008023/211740442-7f8357b9-0c41-44c1-9477-24bc3fad7d66.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - Android Version : 12
 - Kiwi Browser Version: 107.0.5304.74

**Additional context**
It works correctly as PWA in firefox and as a regular page in Kiwi. Only PWA in Kiwi is broken.

**Comment by kuxv** [comment]
Issue #769 might be related

**Comment by d3ward** [comment]
@kuxv Can you check if this is fixed ? I tried it and looks good to me .

**Comment by kuxv** [comment]
hi, yes, it is! Thanks!

**Comment by kuxv** [comment]
it works now
