### ISSUE TITLE
Can't add unpacked extension via manifest.json

### ISSUE THREAD

**Issue by powellnorma** [kiwibrowser/src.next#798]
**Describe the bug**

I am unable to install an unpacked extension via manifest.json

**To Reproduce**

1. I am using https://github.com/kiwibrowser/src.next/releases/tag/3356207093
2. Extract any existing addon and try to add the manifest.json - It is shown in the file browser, but once selected the file browser closes - but nothing happens

**Comment by Practicalbutterfly5** [comment]
Convert it to zip then try

**Comment by powellnorma** [comment]
It works then, but optimally there would be a way to make use of hot reloading. I am not sure if there currently are solutions that have creating an .zip as intermediary step

**Comment by Practicalbutterfly5** [comment]
It's the limitation of permissions that kiwi has. Kiwi browser does not ask for all file permissions (and ofc the browser should never have full storage access). So when you select only the manifest file in the android built-in file picker, the browser only gets access to that manifest file and not the rest of the extension files.

**Comment by d3ward** [comment]
@powellnorma Hot reloading is not something that is practical, as there is a lack of permissions and Android functionality to manage it. I really recommend developing from a desktop environment.
