### ISSUE TITLE
How to deal with this problem?

### ISSUE THREAD

**Issue by maflower23** [kiwibrowser/src.next#799]
Describe*
![Screenshot_20230112_173719](https://user-images.githubusercontent.com/122708460/212514912-782a5f25-b41f-43d5-bf9d-2dcf975c582c.jpg)
 (Not only the adblock has this problem, when I install Tampermonkey kiwi also warning that.

       To Reproduce*
Enter kiwi://extensions, click "+(from .zip/.crx/...)", select the extension flie to install, click the extension's switch and kiwi will warning that.
I can click "OK"  and then start the extension, but in fact it not work.

Smartphone :
 - Device: vivo T1x(2123A); Alibaba Tmall Media box_M18
 - Android Version : 11; 6
 - Kiwi Browser Version 107.0.5304.75

**Comment by d3ward** [comment]
This has been fixed with latest v116. After you press "ok" now extension works . Tested with Tampermonkey .crx
