### ISSUE TITLE
 default Download location is Android/data/com.... 

### ISSUE THREAD

**Issue by mycal123** [kiwibrowser/src.next#8]
Download location
Downloads /storage/emulated/0/Android/data/com.kiwibrowser.browser.dev/files/Download
![Screenshot_20210703102057](https://user-images.githubusercontent.com/59077033/124343478-55e70b00-dbe9-11eb-87bf-5dfd656c7c47.jpg)

**Comment by Xi-PP** [comment]
Android 11 storage settings... Chrome does this same dude
