### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Rikk** [kiwibrowser/src.next#801]
Hello. Is there a timeline for a new release with updated Chromium? Latest is from Oct 30, 2022, right?

Thanks for the best version of Chrome for Android!

**Comment by kyoyacchi** [comment]
@kiwibrowser

**Comment by jututt** [comment]
Chromium is now on 112, Kiwi still on 107. Is Kiwi project still alive?

**Comment by Ibuprophen** [comment]
This just breaks my heart... :tired_face:

~Ibuprophen

**Comment by kiwibrowser** [comment]
<img width="389" alt="Screenshot 2023-02-19 at 18 20 08" src="https://user-images.githubusercontent.com/40272275/219960700-0ed2355c-33e9-422d-a13b-4de413843423.png">

For info, for now the latest version of Kiwi is 110. (which is the latest stable version of Chrome, 110 was released a week ago by Google) so just wait a bit and you'll see it in the store / GitHub.
Also, 112 is not even in beta, it will be released in April 2023 by Google only, so normal.

Just wait a bit til it's deployed everywhere

**Comment by jututt** [comment]
nice to hear that. Btw, I checked on Google Play and it's still on 107

**Comment by Ibuprophen** [comment]
@kiwibrowser, thank you very much for your time and response in this much needed clarification. :smiling_face_with_three_hearts: 

~Ibuprophen

**Comment by vortaj** [comment]
> [...] the latest stable version of Chrome, 110 was released a week ago by Google [...]

It was released on February 1, which is almost 3 week ago.
> [...] Wait a bit [...]

Sure, by that time 111 will be released.

**Comment by Emperormummy** [comment]
How to download the 110 version?

**Comment by Juhaoyang** [comment]
> <img alt="Screenshot 2023-02-19 at 18 20 08" width="389" src="https://user-images.githubusercontent.com/40272275/219960700-0ed2355c-33e9-422d-a13b-4de413843423.png">
> 
> For info, for now the latest version of Kiwi is 110. (which is the latest stable version of Chrome, 110 was released a week ago by Google) so just wait a bit and you'll see it in the store / GitHub. Also, 112 is not even in beta, it will be released in April 2023 by Google only, so normal.
> 
> Wait a bit til it's deployed everywhere and everything will be there like usual as I'm actively working on it :)

那什么时候能发布新版本呢？我们非常期待！
So when did you send the lastest version to the Github or the Google Play ,there are so many people   waiting for your's update!

**Comment by joserealdev** [comment]
Hey @kiwibrowser where can I find that version? I have the last one from Google play and It's v107. Also I took a look to the [releases page](https://github.com/kiwibrowser/src.next/releases) and the last one is from October 30th 2022. Thanks 🙂

**Comment by Reopado** [comment]
> <img alt="Screenshot 2023-02-19 at 18 20 08" width="389" src="https://user-images.githubusercontent.com/40272275/219960700-0ed2355c-33e9-422d-a13b-4de413843423.png">
> 
> For info, for now the latest version of Kiwi is 110. (which is the latest stable version of Chrome, 110 was released a week ago by Google) so just wait a bit and you'll see it in the store / GitHub. Also, 112 is not even in beta, it will be released in April 2023 by Google only, so normal.
> 
> Wait a bit til it's deployed everywhere and everything will be there like usual as I'm actively working on it :)

What is the current ETA for this release please?
It has been almost a month since your post and 112b will be releasing in a few weeks as you said and we're still using 107.

**Comment by dportvine** [comment]
@kiwibrowser 
What prevents you from publishing the new version here on the githab?
If you update your browser every six months, it will die. Think about it.
I also recommend checking out the version of Telegram on their website. This version is updated bypassing the Play Market.

**Comment by jututt** [comment]
https://github.com/kiwibrowser/src.next/issues/813#issuecomment-1465291985

**Comment by Davy49** [comment]
I find all of these comments extremely interesting due to the fact that I've downloaded & installed the latest 'pre-release' that's showing here in github on my android phone that's currently running version 12 of android and in the 'about' area in the kiwi browser settings it's showing the following: Kiwi Browser 107.0.5304.75 , also on that same page it's also showing some information concerning my current android operating system (12) as well as the model of phone LM-G900 Build/SKQ 1.211103.001 . I'm really perplexed now as to how some users are reportedly using version 110 of the kiwi browser ?

**Comment by Reopado** [comment]
I just downloaded 111, thanks for releasing it @kiwibrowser

**Comment by Rikk** [comment]
@kiwibrowser Thank you for updating. Very nice!

**Comment by Juhaoyang** [comment]
> How to download the 110 version?

link：https://juhaoyang.xyz/web/chrome.php
