### ISSUE TITLE
Kiwi Browser does not appear in the Android share destinations

### ISSUE THREAD

**Issue by timkgh** [kiwibrowser/src.next#812]
**Describe the bug**
Kiwi Browser does not appear in the Android share menu. There is no direct way to share a link from another app (e.g. Google Discover feed) to open in Kiwi, without using another app such as [Open Link With...](https://play.google.com/store/apps/details?id=com.tasomaniac.openwith)

**To Reproduce**
Click the share icon on any article in the Google Discover feed, Kiwi Browser does not show up as a destination to share with.

**Expected behavior**
Have Kiwi Browser show up as a share destination. Other browsers such as Firefox show up.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - Android Version : A13
 - Kiwi Browser Version: 107.0.5304.74

**Comment by vonDubenshire** [comment]
Working on latest version for me. 

I've noticed Chrome now has this again after missing for years

**Comment by timkgh** [comment]
Indeed, it seems to have shown up in the latest version.
