### ISSUE TITLE
How To Select Proper APK ? 

### ISSUE THREAD

**Issue by Davy49** [kiwibrowser/src.next#813]
I just installed the latest github version of the kiwi browser on my android LG Velvet 5G phone. How does a user actually know if they are choosing the correct apk version to install? Unless I somehow missed seeing it I didn't see the actual ABI Version showing up anywhere. For instance my phone is of the arm64-v8a architecture.

**Comment by kiwibrowser** [comment]
In chrome://version you can see whether you have the 32-bit version installed or the 64-bit version.
arm versions (32-bit) work on all devices, and arm64 versions (64-bit) only on arm64 devices.

There will be an update getting deployed here tomorrow also.

**Comment by Davy49** [comment]
Hi,
Thanks so much for your timely response, it surely means a lot to have communication like this. I've used the kiwi browser in the past before it was open source, I noticed that the version of chrome is pretty far behind the actual official chrome version, I'm guessing that's pretty normal with this browser. I also remember that before it became open source there was only one developer working on it and I think it just got to the point of being too much for a single person to do.

**Comment by kiwibrowser** [comment]
Yes, it's true. The workload is not a directly problem actually, but I only do occasionally work on the project, as it's something I do for fun. Coding is somewhat relaxing for me and Kiwi is some sort of accidental side-project that I tried to monetize but +/- gave up (the right move would probably be to specialize it into crypto but it's not really my type of things).
Sometimes it's very easy for me to do the version upgrades and is almost all automated, and sometimes it's a lot of manual work (the tabswitcher for example is typically problematic, as the "old" tab switcher of Chromium that Kiwi intentionally uses, starts more and more to look like alien to the codebase :))
Normally 111 should come as a test tomorrow (and seems to be working quite well).

**Comment by Davy49** [comment]
While viewing your most recent reply now I'm convinced that I incorrectly chose the incorrect apk file to install on my phone. Upon checking the version of kiwi browser I'm currently using it shows version 107.0.5304.75, I'm glad now that I posted my question.

Thanks 👍

**Comment by Davy49** [comment]
I find all of these comments extremely interesting due to the fact that I've downloaded & installed the latest 'pre-release' that's showing here in github on my android phone that's currently running version 12 of android and in the 'about' area in the kiwi browser settings it's showing the following: Kiwi Browser 107.0.5304.75 , also on that same page it's also showing some information concerning my current android operating system (12) as well as the model of phone LM-G900 Build/SKQ 1.211103.001 . I'm really perplexed now as to how some users are reportedly using version 110 of the kiwi browser ?

**Comment by Reopado** [comment]
> I'm really perplexed now as to how some users are reportedly using version 110 of the kiwi browser ?

@kiwibrowser recently released several updates and we now have access to version 111, just choose the newest version from here and you're all set: 
[Kiwi Browser Releases](https://github.com/kiwibrowser/src.next/releases)

**Comment by d3ward** [comment]
Kiwi v116 is out ! 👀
