### ISSUE TITLE
Gboard Autocomplete

### ISSUE THREAD

**Issue by otharion** [kiwibrowser/src.next#818]
**Describe the bug**
Gboard autocomplete doesn't work.

**To Reproduce**
Install Gboard and enable autocomplete on Google's account.

**Expected behavior**
When I enter a webpage and this one ask me to login my Gboard doesn't show me the username and password.

**Screenshots**
![Screenshot_2023-03-14-10-17-42-923_com kiwibrowser browser](https://user-images.githubusercontent.com/15057660/224954096-37204766-61e2-414b-b075-41bce3370544.jpg)

**Smartphone:**
 - Device: [POCO X3 NFC]
 - Android Version : [A12]
 - Kiwi Browser Version [ 111.0.5563.71]

**Additional context**
None.

**Comment by kiwibrowser** [comment]
Hello,

The issue with Gboard should be now fixed

**Comment by otharion** [comment]
Issue fixed. Thanks a lot.
