### ISSUE TITLE
Feature Requests [Complete list]

### ISSUE THREAD

**Issue by kryptobolt200528** [kiwibrowser/src.next#82]
List of features requested by users

Save website as pdf

Clear all data on exit/Clear data(cookies.. excluding history)/Clear history on exit

Ability to change speed dial icon(the image)

Js/cookie on off toggle

Stack tabs(like brave)

Dedicated reader mode toggle in menu

Floating menu in PWAs

**Comment by d3ward** [comment]
- #54
 - #26 
 - Will never happen as there are alternative like nextntp
 - #56 
 - Create a dedicated issue like "Stack tabs" ( with a screenshot can be helpful )
 - Create a dedicated issue like "Reader mode improvements with shortcut in menu"
 - Create a dedicated issue like " Floating menu in PWAs"
