### ISSUE TITLE
Remove this useless confirmation message: "Download file? Anyone using this device can see the downloaded file".

### ISSUE THREAD

**Issue by HT-7** [kiwibrowser/src.next#824]
In Chrome Mobile 109, Google introduced a download confirmation barrier for incognito mode, which requires the user to confirm each download. The notification reads "Download file? Anyone using this device can see the downloaded file".

It is obvious that this new "genius idea" from Googleland is intended to help newbie phone users who believe that incognito mode leaves absolutely no traces at all, whereas the purpose of incognito mode is not recording browsing data like history, and not retaining cookies when exited. Downloaded files are outside the scope of incognito mode. Besides, most mobile phones are just used by one person.

This notification is for newbies. However, Kiwi browser is for power users.

To power users, this confirmation dialogue is not helpful. In fact, it is nothing but an annoyance.

There have been several complaints about it: 

* https://www.reddit.com/r/motorola/comments/10uo5w5/message_download_fileanyone_using_this_device_can/.compact
* https://www.reddit.com/r/chrome/comments/10rqq2c/does_anyone_know_how_to_get_rid_of_this_message/.compact

Currently, there is an option in `chrome://flags` to turn it off, however, what tends to eventually happen to flags is taught to us by history (#697).

Please remove this annoyance. Thanks much.

**Comment by kiwibrowser** [comment]
<img width="551" alt="Screenshot 2023-03-14 at 16 12 52" src="https://user-images.githubusercontent.com/40272275/225028487-385801d5-c8d3-4383-820c-413b7c7624b8.png">

The feature is already off by default in Kiwi

**Comment by HT-7** [comment]
Thanks alot for your quick response! I really appreciate it, and I also appreciate your good work.

I just wanted to ensure that when Google decides to toss this option down the moat, Kiwi Browser remains unaffected.
