### ISSUE TITLE
Duplicate 'Clear Browsing Data'

### ISSUE THREAD

**Issue by Malgotra** [kiwibrowser/src.next#826]
**Describe the bug**
There is duplicate 'clear browsing data' entry in settings.
First one in Settings menu.
Second one in Settings<Privacy.
**To Reproduce**
1. Open settings you will see 'clear browsing data' in privacy and security section.
2. Open settings. Navigate to privacy and security section. Open privacy menu. You will see 'clear browsing data' in first place.
**Expected behavior**
There will be only one entry of 'Clear Browsing Data' in settings. Either in privacy and security section or in privacy and submenu (security<privacy).
**Screenshots**
![Screenshot_20230319-160139](https://user-images.githubusercontent.com/122884037/226170101-6431b7ac-6e87-4af3-9207-084637f4ee54.png)
![Screenshot_20230319-160147](https://user-images.githubusercontent.com/122884037/226170105-b179651b-3c65-4d17-8fb9-3bc7a55df28f.png)

**Smartphone (please complete the following information):**
 - Device: [Micromax IN1b]
 - Android Version : [A11 ]
 - Kiwi Browser Version [ 111.0.5563.78]

**Additional context**
No

**Comment by d3ward** [comment]
Not really a duplicate . One is a quick shortcut on settings so user can easily find it . The other one is under the category it need to be . There is also one in the menu . It's about convenience and let user choose
