### ISSUE TITLE
Delayed update

### ISSUE THREAD

**Issue by jututt** [kiwibrowser/src.next#829]
I have two Xiaomi devices running Kiwi: on the newest, running Android 12, Google Play updated Kiwi to 111 about 1 week ago; on the other, running Android 10, rooted, I had some Kiwi updates via GP in the last days, but version ia still 107.
Why?

**Comment by lje** [comment]
It seems Kiwi has some problem with updating via Google Play again. Google Play show me 107 fom fall last year, Apkmirror has 111 for download.

**Comment by jututt** [comment]
What device / androif version do you have?

**Comment by lje** [comment]
I have both a Galaxy S21 FE as well as an old Nokia 5, the issue persists on both devices. It may be the same issue again that Playstore in some regions is not updated, like we had with the German Playstore in the past (see issue https://github.com/kiwibrowser/src.next/issues/650)

**Comment by jututt** [comment]
thanks, updated via apkmirror

**Comment by jututt** [comment]
update in GP came today
