### ISSUE TITLE
"Save as PDF" doesn't work anymore

### ISSUE THREAD

**Issue by stmichalke** [kiwibrowser/src.next#840]
**Describe the bug**
With v111 it isn't possibke to export a website as PDF.

**To Reproduce**
Share -> Print -> Save as PDF gets stuck while prepairing the preview

**Expected behavior**
A preview should be prepaired and the PDF should be offered for downloading.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e
 - Android Version : SL
 - Kiwi Browser Version: 111.0.5563.104 (Offizieller Build) (64-Bit)

**Comment by MooShuOrc** [comment]
Confirmed. It hasn't worked on any of the builds this year.

(Note: The extension PDF Mage works pretty well as a workaround.)

Device: Pixel 6 Pro
Android Version : A13 (CalyxOS 4.7.5)
Kiwi Browser Version: All ARM64 builds released this year (so far)

**Comment by Onkeljoes** [comment]
Just here to confirm. Having the same issue.

**Comment by stmichalke** [comment]
It works again with Kiwi Browser 116.0.5845.21, I thank you a lot.
