### ISSUE TITLE
chrome.exe is faster than browser.exe or any ....exe

### ISSUE THREAD

**Issue by greyrat116** [kiwibrowser/src.next#847]
Article by Yandex browser developers https://habr.com/ru/companies/yandex/articles/721374/

browser.exe renaming in chrome.exe

**Comment by kiwibrowser** [comment]
Issue/article is not related to Kiwi but very cool to read it.
There is actually the same problem on Android with OnePlus phone and 90Hz support. They activate the 90Hz only based on the name of the app :/
And they manually make this list
