### ISSUE TITLE
panel color not displaying correctly

### ISSUE THREAD

**Issue by ghdpsr** [kiwibrowser/src.next#849]
should be light, but it is dark. displayed correctly on other sites.

poco m4 pro 5g
android 13 pixel expirience gsi
kiwi 111.0
![Screenshot_20230420-150548_Kiwi Browser](https://user-images.githubusercontent.com/131364301/233361649-cb1662f5-18a8-4805-894e-cae21677aa22.png)

**Comment by d3ward** [comment]
This is not a bug . It's the theme color of the website and works the same on other browsers, in this case startpage.com have a theme-color set to #171B25
In future there may be implemented an option in theme to force the theme
