### ISSUE TITLE
YubiKey does not work

### ISSUE THREAD

**Issue by sturmen** [kiwibrowser/src.next#85]
Hi, I tried to sign into the YouTube website using my Google account, which is protected by two-factor authentication tied to my YubiKey. When prompted, I inserted my YubiKey into my phone's Type-C port but Kiwi did not recognize it. Is this feature supported?

**Comment by d3ward** [comment]
Hello , is that still a bug ? Did you tried recent Kiwi builds ? 
Let us know if the yubikey works @sturmen

**Comment by d3ward** [comment]
This could be a feature request. As this issue is very old and op didn't share any update about the problem, issue will be closed .

**Comment by 66Leo66** [comment]
Hi, yubikey is still not working on the latest version (Oct. 31 release). Have tried Github 2FA and Yubikey Official Demo, neither of them worked. Error messages are as follows. Hope the issue can be reopened and resolved, thanks!
![Screenshot_2022-12-04-16-46-29-793_com kiwibrowser browser](https://user-images.githubusercontent.com/33322229/205481878-75494674-cab1-49a0-a671-3a2ef91f01d4.jpg)
![Screenshot_2022-12-04-16-46-37-635_com kiwibrowser browser](https://user-images.githubusercontent.com/33322229/205481881-1005f214-5348-4532-9d4b-6151a7f89851.jpg)

**Comment by mdentremont** [comment]
I'm seeing similar behaviour on okta.com

**Comment by mdentremont** [comment]
I just tested and this works in Brave browser as well
