### ISSUE TITLE
 Inquiry about Chrome Extension integration

### ISSUE THREAD

**Issue by Shrey-Raj** [kiwibrowser/src.next#856]
Hi there,

I was wondering if your GitHub repo has integrated a Chrome extension within your app? I couldn't find any information about it on your repository, so I thought I'd reach out and ask.

If it's not something that you have already incorporated, I was wondering if you could provide some guidance on how I could go about adding a Chrome extension to an app while building . 

Thank you for your time and consideration.

Best regards,
SHREY RAJ

**Comment by d3ward** [comment]
Kiwi do not bundle specific extension . Also I don't think guidance will be provided as there is a lot of resource to start from
