### ISSUE TITLE
Blank page in Kiwi when clicking on a link to go a post in Facebook mobile.

### ISSUE THREAD

**Issue by jmh2002** [kiwibrowser/src.next#87]
**Describe the bug**
Blank page in Kiwi when clicking on a link to go a post in Facebook mobile. Kiwi Browser v93.0.4577.9

**Smartphone (please complete the following information):**

Device: Samsung Galaxy S5 Duos SM-G900FD
Android Version: LineageOS 17.1 (Android 10)
Kiwi Browser Version: v93.0.4577.20 (from the Play Store)

![viber_image_2021-07-23_18-31-59-111](https://user-images.githubusercontent.com/11772804/126745345-08504180-c33e-42e5-b7b3-15d0f73f25f8.jpg)

**Comment by Lartsch** [comment]
Do you have the data saver mode enabled? @jmh2002

**Comment by jmh2002** [comment]
Thanks for the reply :)

Settings > Lite Mode > is OFF.

Is that what you mean?

**Comment by Lartsch** [comment]
@jmh2002 Yes it's what I meant. If you had it activated I would have suggested to try turn it off, but it was just a wild guess.

**Comment by Lartsch** [comment]
@jmh2002 I have similar issues with other websites, but elements appear as soon as I try to scroll (for ex. on twitter).
Could you try if this applies to your case as well?

**Comment by jmh2002** [comment]
I can confirm that scrolling makes no difference unfortunately. Also it only seems to be posts on facebook, some other pages (eg: my home page, my friends page, etc) seem to work correctly.

Overall it seems to be similar to this issue: https://github.com/kiwibrowser/src/issues/380#issuecomment-885547256

**Comment by jmh2002** [comment]
Unfortunately this problem still exists in v93.0.4577.20 (from the Play Store).

m.facebook.com does not work properly.

I tried logging out of Facebook and also clearing all facebook data in Kiwi Browser > Settings > Site Settings > All Sites > Facebook > Clear & Reset

logging back into Facebook works but the site doesnt work properly. In addition to the above screenshot here are a couple more showing the Home Page (not working) and the Menu (working):

![Screenshot_20210804-104259_Kiwi_Browser](https://user-images.githubusercontent.com/11772804/128096151-77cd2c85-5dc1-4d57-89bc-320c8fa099da.jpg)

![Screenshot_20210804-104321_Kiwi_Browser](https://user-images.githubusercontent.com/11772804/128096195-d5315cf8-d08e-4fd2-b2c9-85fe654ca265.jpg)

**Comment by d3ward** [comment]
@jmh2002 do you still have issues on Facebook with recent builds ?

**Comment by jmh2002** [comment]
Yes this problem still exists with v96.0.4664.46 from the Play Store.

I'm surprised more people haven't raised an issue about it? Maybe everyone is using the Facebook app instead...

It's a pity because this all used to work perfectly with earlier versions of Kiwi Browser. It seems something was changed that broke this.

**Comment by d3ward** [comment]
@jmh2002 sooo what about recent updates with Kiwi v99 ? I just logged in to fb and seems to works everything . Did you figured out if it was a third party bug like dns , vpn , adblock or any extension ?

**Comment by d3ward** [comment]
We consider this to be resolved. Feel free to reopen the issue if it's still there with v112.
