### ISSUE TITLE
Tab Header Not Updating

### ISSUE THREAD

**Issue by ice051128** [kiwibrowser/src.next#871]
**Describe the bug**
There is a major bug with the default tab switcher where the tab header doesn't update itself according to the current page. It has persisted for over 2 months since build 111, is it possible to get a fix?

**To Reproduce**
If you search for anything with the address bar and then click on any website from the results on google search, the tab header will not update properly for the current website.

**Expected behavior**
The tab header should update accordingly so that users can navigate among different tabs easily.

**Screenshots**
You can see it very clearly.
![Screenshot_20220907-045419](https://user-images.githubusercontent.com/49018832/188736703-8d7eff11-74f6-41de-8006-33f83a0a64a4.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - Android Version: A13
 - Kiwi Browser Version: 112.0.5615.137

**Additional context**

**Comment by ice051128** [comment]
![Screenshot_20230601-061230](https://github.com/kiwibrowser/src.next/assets/49018832/854bd71b-5230-4947-8e08-e258041876e3)
It will also show url as tab title as well which is not the correct behavior

**Comment by d3ward** [comment]
With Kiwi v116 this has been fixed.
