### ISSUE TITLE
Discover feed no longer working.

### ISSUE THREAD

**Issue by possom2009** [kiwibrowser/src.next#874]
**Describe the bug**
Discover feed no longer works on Modern homepage. Turned it off and on and changed source, but that didn't fix it.

**To Reproduce**
Open new tab.

**Expected behavior**
A list of various news articles in the Discover feed.

**Smartphone (please complete the following information):**
 - Device: [Amazon Fire HD 10 tablet]
 - Android Version : [Android 9]
 - Kiwi Browser Version 112.0.5615.137

**Additional context**
Discover feed still works if the homepage is set to Classic homepage.

**Comment by jututt** [comment]
Issue confirmed, happens from a month or so, no Kiwi updates in the meantime AFAIK, must be something server-side

**Comment by d3ward** [comment]
Kiwi v116 ( Github release) got this fixed .
