### ISSUE TITLE
TABLET MODE LIKE VIVALDI

### ISSUE THREAD

**Issue by iamamalware** [kiwibrowser/src.next#881]
![android_double-line-tab-stack-new-blog](https://github.com/kiwibrowser/src.next/assets/136218052/36e21477-39b4-4738-801b-9dd23e969bf1)
Please developers I am an old user of kiwi and I was using this browser for long time but when the user interface became too old i quit it
That's why I want request you to add tab mode like Vivaldi browser. Or opera browser along with extension pin mode
     -Namaste-🙏🙏🙏

**Comment by d3ward** [comment]
#146
