### ISSUE TITLE
Automatic builds/releases broken

### ISSUE THREAD

**Issue by joserealdev** [kiwibrowser/src.next#885]
Hello team, I've noticed that last release is from April and Kiwi is already a few versions behind Chromium. Is there any reason of why the auto builds stopped working? Will the project be discontinued? I love it and I would like to be able to continue using it

Thanks for the work

**Comment by JacenBridger** [comment]
FYI, the project will not be discontinued untill the dev explicitly mention that. 
The chromium is not always up-to-date with the latest chromium, but it catches up preety quick often with the latest chromium. There are gaps between updates, sometimes for many months. But it is, what it is.
