### ISSUE TITLE
[Bug Report] [Version 93] Incorrect Pointer Event when address bar is located at the bottom

### ISSUE THREAD

**Issue by cyfung1031** [kiwibrowser/src.next#89]
Demo Site:
https://cyfung1031.github.io/debug/lihkg/v20210725b/index.html

Configuration:
2021.07.20 Kiwi Browser from Google Play (Chromium 93)
Settings -> Accessibility -> "Bottom toolbar" checked
Settings -> Accessibility -> "Toolbar always on screen" unchecked

Description:
In Demo Site, the icon buttons at the bottom shall be clickable. However, Kiwi Browser can just render the buttons but not clickable. 

When the address bar is shown and located in the bottom, the expected pointer event could not happen in kiwi browser, while other browsers can.

When the address bar disappears (i.e. scrolling), the pointer event becomes normal.

![screenshot](https://user-images.githubusercontent.com/44498510/126901296-3bae30fb-e696-4e89-8e11-dbed360465f9.png)

**Comment by KaKi87** [comment]
> Settings -> Accessibility -> "Bottom toolbar" checked
Settings -> Accessibility -> "Toolbar always on screen" unchecked

> When the address bar is disappear (i.e. scrolling), the pointer event becomes normal.

Moreover, when *Toolbar always on screen* is checked, the issue therefore never disappears.

**Comment by ayacnc** [comment]
I found this bug appears on Android11,but on Android10,it's just fine.

**Comment by kiwibrowser** [comment]
Fixed in last build
