### ISSUE TITLE
Can not play videos in GitHub Issues

### ISSUE THREAD

**Issue by Daviteusz** [kiwibrowser/src.next#901]
**Describe the bug**
I'm trying to watch attached videos and they are unplayable in kiwi.

**To Reproduce**
Go to issue, e.g. #900 and try to play video.

**Expected behavior**
Video should be playable

**Screenshots**
https://github.com/kiwibrowser/src.next/assets/11527277/1c3798f3-026f-483a-b1bd-089d971775d5

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - Android Version : A13 QPR3
 - Kiwi Browser Version 116.0.5845.21

**Comment by rahaaatul** [comment]
Can confirm, I tried with other browser (1DM+) and it played. But doesn't play with Kiwi.

Version: `116.0.5845.22`

**Comment by zhch02** [comment]
The translation of your previous message into English is as follows:

"Not only can't I play videos on GitHub, but also on my Huawei HarmonyOS system, I can only play YouTube videos. I can't play videos on other video websites such as 555dy3.com, v.qq.com, iqiyi.com, youku.com, etc. Can you please try these websites? Thank you."

Please note that machine translation may not be 100% accurate.

**Comment by rahaaatul** [comment]
can you give me some specific videos to play and test?

**Comment by rahaaatul** [comment]
I played [this video](https://m.iqiyi.com/v_1tb79lhcrts.html) and it's playing fine, but it does not play in mobile mode (it redirects me to play store to download the app), so I played it in desktop mode.

**Comment by zhch02** [comment]
My device is HarmonyOS 3.0, and I don't know if it's the system. My device opens these websites, and the website videos can't be played, but youtube is fine. I don't know why. I reinstalled the software after updating it, but it didn't work out. Now it's returned to the April version.

**Comment by rahaaatul** [comment]
Can you share a screenshot/screen recording? to better know what is the error.

**Comment by zhch02** [comment]
可以，请等我一下。

**Comment by zhch02** [comment]
就是这样

**Comment by zhch02** [comment]
![Screenshot_20230721_172812_com kiwibrowser browser](https://github.com/kiwibrowser/src.next/assets/132458165/725d1d12-3f47-454f-81e1-4e2b9b2bfdd5)
![Screenshot_20230721_172828_com kiwibrowser browser](https://github.com/kiwibrowser/src.next/assets/132458165/e4265838-0363-4d93-84f9-dabefaf04f4e)
![Screenshot_20230721_172836_com kiwibrowser browser](https://github.com/kiwibrowser/src.next/assets/132458165/b9ad2b68-2785-4f3a-86ee-ac2139405b6c)
我不会上传视频

**Comment by zhch02** [comment]
Uploading lv_0_20230721171631.mp4…

**Comment by rahaaatul** [comment]
Can you try in desktop mode? Or using VPN?

**Comment by zhch02** [comment]
https://github.com/kiwibrowser/src.next/assets/132458165/dbdec473-0c51-4274-b6fa-09c3fd59545a

**Comment by zhch02** [comment]
https://github.com/kiwibrowser/src.next/assets/132458165/f7d1d7e5-df7b-4c10-a3fb-36eb56e3b8bd

**Comment by rahaaatul** [comment]
By the way, can you play with other browsers?

**Comment by zhch02** [comment]
edge浏览器,狐猴浏览器,Iceraven这三个正常

**Comment by zhch02** [comment]
brave,yandex,vivaldi这三个有相同的问题。

**Comment by rahaaatul** [comment]
Then it's not your OS or Network, it's the browser's fault. It's weird that it's working for me.

Do you have other devices you could test the sites on Kiwi browser?

**Comment by zhch02** [comment]
暂时没有别的设备了，我在狐猴浏览器的交流群看到别人的设备都正常，同样有鸿蒙2.0的可以正常播放视频，我在用鸿蒙3.0的最新版本。我想这可能和鸿蒙系统有关系。

**Comment by tortino2** [comment]
confirmed on Kiwi Browser 116.0.5845.24

**Comment by zhch02** [comment]
正在上传 - lv_0_20230722164700.mp4

**Comment by zhch02** [comment]
正在上传 lv_0_20230722164700.mp4…

**Comment by zhch02** [comment]
https://github.com/kiwibrowser/src.next/assets/132458165/caf4684f-ad23-43cf-b7de-ceed97fe7821

**Comment by rahaaatul** [comment]
- What version are you using `github` or `playstore`? 
- Did you try the dev version? see if there's any difference, 

Then we can definitely say it's the OS conflicting with Kiwi.
@zhch02

**Comment by zhch02** [comment]
playstore版本，我再试试dev版本

**Comment by rahaaatul** [comment]
> PlayStore version, I'll try the dev version again

Try the github version too.

**Comment by Daviteusz** [comment]
Some videos can be played, maybe fixed.
