### ISSUE TITLE
Can't bookmark pages anymore

### ISSUE THREAD

**Issue by J1Angler** [kiwibrowser/src.next#908]
After I updated to the latest version, I lost the ability to bookmark pages. The icon is completely missing in incognito, and there's a blank space in the URL bar for the "regular" mode where the bookmarkmicon would be. Clicking on said space does nothing.

**Comment by d3ward** [comment]
This is on tablet right ? We got other users with same issue on tablet that both bookmark and download icon do not work

**Comment by fredgolightly** [comment]
Tab S8 here, my download button does nothing, doesn't appear on Pixel 5. But...I want to hide it on my Tab anyway

**Comment by possom2009** [comment]
Can confirm not working on tablets.

Device: [Amazon Fire HD 10 tablet]
Android Version : [Android 9]
Kiwi Browser Version 116.0.5845.24

Several flags seem to be missing too.

**Comment by possom2009** [comment]
The only way to use the bookmark button is to go to Settings > Tab Switcher and select Desktop. Then after the browser restarts tap on the three dots in the upper right and the bookmark star will be there and you can now bookmark pages again.

**Comment by kiwibrowser** [comment]
Is there still the issue on the latest GitHub build @possom2009  ?

**Comment by possom2009** [comment]
> Is there still the issue on the latest GitHub build @possom2009 ?

I don't know. I'm using the Play Store version.

**Comment by kiwibrowser** [comment]
Ok, let's see when you have Git584502600 or Git584502604 on the Play Store (should appear soon).
I have made a change that may help there

**Comment by possom2009** [comment]
> 

Thanks! I'll check it out when it appears. Also, do you know what's wrong with the tabs? I left a bug report here.

https://github.com/kiwibrowser/src.next/issues/915

**Comment by possom2009** [comment]
Issues with bookmarks and downloading pages fixed on tablets.
