### ISSUE TITLE
Night mode depowered

### ISSUE THREAD

**Issue by jututt** [kiwibrowser/src.next#909]
Kiwi Browser 116.0.5845.24
Night mode lost much of its power with latest 116 releases, most sites that turned dark before (v.112) look now the same as light mode i.e. wikipedia

**Comment by tortino2** [comment]
yes to make it work I had to enable a flag in kiwi://flags (just search for "dark" )

**Comment by jututt** [comment]
Thanks,
Auto Dark Mode for Web Contents,
set flag to Enable, relaunch, all sites went to dark mode, even disabling night mode.
Reset the flag to Default, relaunch, now sites correctly follow option night mode on / off

**Comment by kiwibrowser** [comment]
Should this flag be enabled by default in your opinion ?

**Comment by d3ward** [comment]
Might seems dumb questions, but @jututt can you tell us
- what theme you have set
- is night mode ( kiwi feature ) enabled ?
- what night mode style is set on settings ?

**Comment by jututt** [comment]
Now is back to `default` and dark mode works as intended. Had to switch to `enabled` to make it work.

**Comment by d3ward** [comment]
i see , so now does other styles like amoled works as intended ?

**Comment by jututt** [comment]
option has always remained Amoled, no change there

**Comment by d3ward** [comment]
Great. Thanks for the patience
