### ISSUE TITLE
list view mode on tabs tray can't select tab

### ISSUE THREAD

**Issue by samlux04** [kiwibrowser/src.next#92]
tabs tray on list mode, select tab activate search input and not switching tabs.
also the tabs tray kinda flicker. not smooth.
the overall ui animation also kinda slow, maybe you can fasten it a little bit.
another bug. when the toolbar on the bottom. opening tabs tray will move the toolbar half down. also flicker.

**Comment by d3ward** [comment]
This animations bugs has been fixed ( tested on v98 builds )
