### ISSUE TITLE
"Open in external app" opens in new tab instead

### ISSUE THREAD

**Issue by lje** [kiwibrowser/src.next#920]
**Describe the bug**
In Kiwi 116.x, if I click&hold a link and select "open in external app", the a new tab is opened instead. This is a regression from 112.x where it worked.
I tested with a Youtube link, having NewPipe installed as external app.

**To Reproduce**
Have NewPipe installed, open any page with a Youtube link, touch&hold the link, select "open in external app".

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy S21 FE
 - Android Version : 13
 - Kiwi Browser Version 116.0.5845.27

**Additional context**

**Comment by avgex** [comment]
The same for youtube app, kiwi 116.x opens mobile youtube web page. In Kiwi 112.x, when I click and hold on yt video and select open in externall app, video is launched in youtube app, kiwi 116.x opens m.youtube.com

**Comment by fredgolightly** [comment]
> The same for youtube app, kiwi 116.x opens mobile youtube web page. In Kiwi 112.x, when I click and hold on yt video and select open in externall app, video is launched in youtube app, kiwi 116.x opens m.youtube.com

Have you made sure the youtube app has the open with defaults selected in the app info settings in android? I had to re-add the urls via tickboxes. Works fine with 116 here just clicking links

**Comment by avgex** [comment]
> > The same for youtube app, kiwi 116.x opens mobile youtube web page. In Kiwi 112.x, when I click and hold on yt video and select open in externall app, video is launched in youtube app, kiwi 116.x opens m.youtube.com
> 
> Have you made sure the youtube app has the open with defaults selected in the app info settings in android? I had to re-add the urls via tickboxes. Works fine with 116 here just clicking links

on my Galaxy S22, I do not have tickboxes next to the urls in "Supported web addresses". For youtube app a can only tick "Open supported links" and list all the "Supported web addresse" (youtube.be, m.youtube.com, etc..). I ticked off "Open supported links", then turned it on. Kiwi still opens m.youtube.com insted of native yt app. O my tablet (Galaxy S6 lite) it behaves the same once i upgraded to Kiwi 116.x today. 

As a side note, Chrome behaves differently, I just click on title of the embeded youtube video, and it is opneded in youtube app

**Comment by lje** [comment]
> Works fine with 116 here just clicking links

This works for me as well, as long as "activate external apps" is ticket. But this setting is independent from the "open in external app" context menu. As long as the latter is not working, the former may be used as a workaround.

**Comment by lje** [comment]
Seems to be fixed with 116.0.5845.61

**Comment by C-O-D** [comment]
For me completely broken in 116.0.5845.72.
It always opens stock YouTube app, so I deactivated the app and now it always opens YouTube website.
When I click open with external app none of my YouTube apps (NewPipe, LibreTube) are shown, only browsers.
Android 13; Mi 10
