### ISSUE TITLE
In the case of a group of tabs, every time you open the tab switcher, the whole thing moves up switcher, the whole thing moves up

### ISSUE THREAD

**Issue by UNTRIVAL** [kiwibrowser/src.next#933]
In the case of a group of tabs, every time you open the tab switcher（grid）, the whole thing moves up
![Screenshot_2023-07-26-12-03-53-160_com kiwibrowser browser-edit](https://github.com/kiwibrowser/src.next/assets/108966196/bea1a33e-6036-4e63-bf21-ed757836b449)
![Screenshot_2023-07-26-12-06-19-858_com kiwibrowser browser-edit](https://github.com/kiwibrowser/src.next/assets/108966196/c19a15e4-c1e9-4aac-9975-f4e5d682023f)

**Smartphone (please complete the following information):**
 - Device: [Redmi k50]
 - Android Version : [A13 ]
 - Kiwi Browser Version [ 116.0.5845.28 ]

**Comment by kiwibrowser** [comment]
Your screenshot shows a verification code, so for your security I will hide the picture. Thank you for checking the ticket!
(Yes, the fix is coming in one hour)
