### ISSUE TITLE
Missing new tab button in tab switcher

### ISSUE THREAD

**Issue by amit-katyal** [kiwibrowser/src.next#942]
**Describe the bug**
New tab button is missing in tab switcher menu when it is set to desktop

**To Reproduce**
1. Set toolbar to bottom toolbar
2. In settings, set tab switcher option to desktop (like a computer)
3. Open some tabs
4. Open tab switcher menu, you'll find new tab button missing

**Expected behavior**
It should show new tab button in tab switcher menu when it is set to desktop

**Screenshots**
![Screenshot_20230730-113830](https://github.com/kiwibrowser/src.next/assets/89385446/1fe2e0d3-554a-4bed-b661-0c5d970fc4c5)
![Screenshot_20230730-113843](https://github.com/kiwibrowser/src.next/assets/89385446/8bbce9de-9816-4d69-b09d-ae7f1e0b607f)

**Smartphone (please complete the following information):**
 - Device: Oneplus Nord
 - Android Version : A11
 - Kiwi Browser Version: 116.0.5845.57

**Additional context**
It shows the new tab button in tab switcher menu when, bottom toolbar is disabled.

**Comment by UNTRIVAL** [comment]
+1
