### ISSUE TITLE
How can i get the latest source code of kiwi?

### ISSUE THREAD

**Issue by luanon404** [kiwibrowser/src.next#957]
Hi I am trying to build kiwi browser, but repo https://github.com/kiwibrowser/src stopped updating 3 years ago, I wonder if I can get the latest kiwi code? Or is it discontinued? Thanks.

**Comment by Ibuprophen** [comment]
@luanon404, I believe that the most up-to-date repo is https://github.com/kiwibrowser/src.next/

~Ibuprophen

**Comment by luanon404** [comment]
> @luanon404, I believe that the most up-to-date repo is https://github.com/kiwibrowser/src.next/
> 
> ~Ibuprophen

![IMG_20230805_002441](https://github.com/kiwibrowser/src.next/assets/71830807/c49a406a-2293-4bcf-ac34-acad408e508c)

**Comment by luanon404** [comment]
im believe its not

**Comment by luanon404** [comment]
i think they not public source anymore.
