### ISSUE TITLE
sync with Firefox, or create windows version

### ISSUE THREAD

**Issue by thrylosthyra7** [kiwibrowser/src.next#964]
**Is your feature request related to a problem? Please describe.**
As we can't sync data with chrome, it would be nice to sync another WINDOWS browser. let's say Firefox. or something that is open source. it's really annoying that you can't even view your history or share your passwords.

**Describe the solution you'd like**
as said, a solution would be syncing with another browser, or maybe a kiwi windows version.

**Describe alternatives you've considered**
another alternative could be an extension or an app that would do the trick.

**Additional context**
nothing more.

**Comment by d3ward** [comment]
There is no plan to implement such feature. 
For now with tabs or bookmarks you can use an open source solution like Floccus.
For passwords you can also use an open source solution like Bitwarden, for password is better than saving on browser.
