### ISSUE TITLE
Links opened in new tabs are erased after a while

### ISSUE THREAD

**Issue by Ainz-23** [kiwibrowser/src.next#967]
Idk if anyone else has been having this issue, but it's infuriating. I tend to have a lot of tabs open because I do a lot of reading and I like to open stuff I'm going to read and then go through it tab by tab. Recently if I open a link in a new tab, but don't go to it right away, after a while Kiwi just erases it and all I can ever see on it is the blank new tab screen, even though what I opened was a link. The back button doesn't bring me back either. It saves the link in history so it should know it's there. Idk what to do about it or what's causing it ??? 
 
Android version 13
Phone realme 8i

**Comment by miluoshi** [comment]
The same is happening to me.

Realme 7 Pro, Android 12 
Kiwi 116.0.5845.61

**Comment by kiwibrowser** [comment]
Fixed in upcoming build (.70)

**Comment by Ainz-23** [comment]
> Fixed in upcoming build (.70)

Thanks a lot for fixing the issue as soon as possible. I really appreciate your efforts ☺️
