### ISSUE TITLE
Web page video cannot be played online, there is no prompt or frequently damaged prompt.

### ISSUE THREAD

**Issue by rrejj** [kiwibrowser/src.next#987]
In versions later than Generation 4736345870, the video cannot be properly viewed online and is damaged. In addition, versions after Generation 4736345870 have pop-up windows for Google Framework requirements. So now I can only go back to a version earlier than Generation 4736345870 to watch videos online. Hope developers can pay attention to and solve this problem, ignoring the Google framework needs and fixing the video online, thank you.

**Comment by zhch02** [comment]
我用的鸿蒙4.0设备，遇到同样的问题。
